### ISSUE TITLE
Sample output example

### ISSUE THREAD

**Issue by adulau** [chipsec/chipsec#1]
Chipsec is really a great tool for BIOS-related system forensic. 

It would be nice to add some examples with known bootkits (infected systems):

 - Rovnix
 - Win64/Olmarik / TDSS

Especially to help users to spot any change (or not) in the bios parameter block while they use chipsec.

Thank you

**Comment by c7zero** [comment]
While not solving exactly what's asked in this issue (as we don't deal with MBRs) I think I'll close this one. CHIPSEC has "tools.uefi.blacklist" module now that can check for known bad EFI binaries (e.g. EFI firmware rootkits).

Eventually we'll add raw disk IO. This can be used as OS independent mechanism to read LBAs and extract things like MBR (provided that legacy bootkits don't disappear by then).
