### ISSUE TITLE
bug：chipsec/utilcmd/decode_cmd.py at line126 does not exist method named func（）

### ISSUE THREAD

**Issue by RockySYR** [chipsec/chipsec#1009]
@tweksteen @rountree @hughsie @mtnmts @WilliamLeara

**Comment by RockySYR** [comment]
AND i can't find I can't find where _rom is defined     At chipsec/utilcmd/decode_cmd.py  line79

**Comment by frinzell** [comment]
Does #1022 address your issue?

**Comment by frinzell** [comment]
No response, assume fixed.  Please reopen if needed.
