### ISSUE TITLE
Install script not copying decompression utilities

### ISSUE THREAD

**Issue by 0xfede7c8** [chipsec/chipsec#1020]
In Linux, with the latest version of chipsec when trying to install with:

```bash
sudo python setup.py install
```
or
```bash
sudo python3 setup.py install
```

Then go to `/usr/local/lib/pythonX.X/dist-packages/chipsec-1.5.5-pyX.X.egg/chipsec_tools` (where X.X is your Python version) and the tools are not there (Brotli, Tiano, LZMA).
This makes the modules which use this tools (any UEFI parsing module) to fail.

**Comment by BrentHoltsclaw** [comment]
@0xfede7c8 did you first run build or have prebuilt binaries?  The install option should only copy all files, it should not build them.
