### ISSUE TITLE
Can't build Win7 driver with x86 enviroment command prompt

### ISSUE THREAD

**Issue by hcwang1126** [chipsec/chipsec#104]
At least can't build the driver well on my working machine: Win10, DDK: 7600.16385.1.

The root cause is that the enviroment is specific for WinXP and function KeQueryActiveProcessorCount is not available. Using  x64 command prompt can build the driver without any error.

The document readme might need to update.

**Comment by andrew-furtak** [comment]
My Win10 shows WinXP environment as the only x86 environment available. You need to use environment from Start Menu\Programs\Windows Driver Kits\WDK 7600.16385.1\Build Environments\Windows 7. I'll update the readme file with correct build environment.

**Comment by c7zero** [comment]
Does this resolve the issue?

**Comment by hcwang1126** [comment]
I think so, thanks. -HC

________________________________
寄件者: c7zero <notifications@github.com>
寄件日期: 2017年3月16日 上午 08:22:54
收件者: chipsec/chipsec
副本: hcwang1126; Author
主旨: Re: [chipsec/chipsec] Can't build Win7 driver with x86 enviroment command prompt (#104)


Does this resolve the issue?
