### ISSUE TITLE
Chipsec UEFI Fails for version 1.5.6 - ValueError: Empty module name

### ISSUE THREAD

**Issue by nstarke** [chipsec/chipsec#1040]
Hi,
I attempted to use chipsec `1.5.6` to dump the SPI ROM off a device and was greeted with this stack trace:

```
FS0:\chipsec\> python -^# chipsec_util.py spi dump rom.bin
Traceback (most recent call last):
  File "chipsec_util.py", line 213, in <module>
    sys.exit( main() )
  File "chipsec_util.py", line 208, in main
    chipsecUtil = ChipsecUtil(argv if argv else sys.argv[1:])
  File "chipsec_util.py", line 71, in __init__
    self.import_cmds()
  File "chipsec_util.py", line 127, in import_cmds
    module = importlib.import_module( cmd_path )
  File "\Efi\StdLib\lib\python.27/importlib/__init__.py", line 37, in import_module
    __import__(name)
ValueError: Empty module name
```

I then attempted to use chipsec `1.5.1` and was able to successfully complete the operation.  I am not sure if this is the latest version that works or not.

**Comment by frinzell** [comment]
I'm not able to see that error.  Are you using the most recent Python EFI Shell interpreter?
https://github.com/chipsec/chipsec/tree/master/__install__/UEFI

**Comment by nstarke** [comment]
I tried two different versions of the python StdLib/Tools directories in `chipsec_uefi_x64.zip` - the version at the git HEAD and the version bundled with `1.5.6`.  Those were the two failures.  The success came with the version bundled with `1.5.1`.   Its possible this is platform specific, I suppose.

**Comment by frinzell** [comment]
Can I get a log file using the -d switch?
We can move this to email if it makes it easier, [chipsec@intel.com](chipsec@intel.com)

**Comment by nstarke** [comment]
It's strange; I tried using the `-v` and `-d` switches and I was not able to get any log file written or differing output.  Perhaps since it seems to work on your end we can close this as not reproducible, since I can't offer any additional information?

**Comment by npmitche** [comment]
I'm shooting in the dark, but perhaps try to load the latest python.efi files from 1.5.6 from the __install__ directory? We haven't seen this issue what the old version of python, but it would be good to confirm you're using the latest with 1.5.6.

**Comment by nstarke** [comment]
I believe I have tried this, I used the version of `python.efi` bundled with the `1.5.6` version release and that was one of the failure cases.  

I'm sorry to report that I don't have any additional information to provide.  Would it be acceptable to you for me to close this issue as not reproducible?

**Comment by frinzell** [comment]
Maybe I misread your comment, you need all files in StdLib and Tools.  All within the EFI folder.  Beyond that, it's possible there was some corruption.  Is the error isolated to just that util command?

**Comment by frinzell** [comment]
Closing as not reproducible.  Please reopen if needed.  Thanks!

**Comment by nstarke** [comment]
This was almost surely caused by an incomplete filesystem copy; sorry I did not close it sooner.
