### ISSUE TITLE
Add NVRAM GUID FFF12B8D-7696-4C8B-A985-2747075B4F50

### ISSUE THREAD

**Issue by startergo** [chipsec/chipsec#1054]
NVRAM volume GUID for Apple cMP is **FFF12B8D-7696-4C8B-A985-2747075B4F50** with header "$VSS":
![image](https://user-images.githubusercontent.com/7897244/101068926-580bbd00-3567-11eb-94aa-27dcdb34ede8.png)
Can this be added to 
https://github.com/chipsec/chipsec/blob/f7fe1be07433d8305bcd2b5bb784fef6531c3398/chipsec/hal/uefi_platform.py
MP5,1 NVRAM volume has two $VSS stores.

**Comment by frinzell** [comment]
Added this as an enhancement request.  Thanks.

**Comment by startergo** [comment]
I found that variable defined here:
https://github.com/chipsec/chipsec/blob/f7fe1be07433d8305bcd2b5bb784fef6531c3398/chipsec/hal/uefi_common.py#L91

**Comment by frinzell** [comment]
Closing.  Please reopen if needed.  Thanks!
