### ISSUE TITLE
chipsec\helper\linux\linuxhelper.py line:322 ，Where is fcntl.ioctl declared

### ISSUE THREAD

**Issue by RockySYR** [chipsec/chipsec#1060]
def ioctl(self, nr, args, *mutate_flag):
        return  fcntl.ioctl(self.dev_fh, self._ioctl_base + nr, args)`` @tweksteen @rountree @hughsie @mtnmts @WilliamLeara 

#Where is fcntl.ioctl declared，and would you like to show me this function

**Comment by frinzell** [comment]
Closing as duplicate to #1061.
