### ISSUE TITLE
chipsec/helper/linux/linuxhelper.py line:322 Where is "fcntl.ioctl" declared

### ISSUE THREAD

**Issue by RockySYR** [chipsec/chipsec#1061]
def ioctl(self, nr, args, *mutate_flag):
        return  fcntl.ioctl(self.dev_fh, self._ioctl_base + nr, args)`` @tweksteen @rountree @hughsie @mtnmts @WilliamLeara 

#Where is fcntl.ioctl declared，and would you like to show me this function

**Comment by RockySYR** [comment]
@tweksteen @rountree @hughsie @mtnmts

**Comment by npmitche** [comment]
It's a python library: https://docs.python.org/3/library/fcntl.html

**Comment by frinzell** [comment]
Question seems answered.  Closing.  Please feel free to reopen if needed.  Thanks!
