### ISSUE TITLE
Error when loading kernel module: register_kprobe failed, returned -22

### ISSUE THREAD

**Issue by kedare** [chipsec/chipsec#1154]
Hello.

I have been trying to use Chipsec on Manjaro/Archlinux but I keep getting this error when loading the chipsec kernel module

```
[Tue Apr  6 17:18:51 2021] Chipsec module loaded                                                                                                                                                                   [Tue Apr  6 17:18:51 2021] ** This module exposes hardware & memory access, **                                                                                                                                     
[Tue Apr  6 17:18:51 2021] ** which can effect the secure operation of      **                                                                                                                                     
[Tue Apr  6 17:18:51 2021] ** production systems!! Use for research only!   **                                                                                                                                     
[Tue Apr  6 17:18:51 2021] register_kprobe failed, returned -22
```

So far I could not find a workaround, is this supposed to happen ?

```
Linux 5.10.23-1-MANJARO #1 SMP PREEMPT Thu Mar 11 18:47:18 UTC 2021 x86_64 GNU/Linux

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
```

This happen when using the aur package.

Thanks

**Comment by frinzell** [comment]
Is this using 1.6.1?
Do older releases work?
Thanks!

**Comment by minipli-oss** [comment]
This should be fixed by https://github.com/chipsec/chipsec/pull/1207, specifically commit https://github.com/chipsec/chipsec/pull/1207/commits/a1e5f3d23a36e695aae69defb2e55d445dcc4ec8 which provides an alternative mechanism for symbol resolving on kernels that lack kprobes support.

**Comment by Sae86** [comment]
Hi @minipli-oss, did #1207 fixed the issue?

**Comment by minipli-oss** [comment]
> Hi @minipli-oss, did #1207 fixed the issue?

For me it did, that's why I mentioned it here. But I was hoping for a confirmation from @kedare. As there has been none in over a year now, I guess we can safely close this issue.

**Comment by Sae86** [comment]
Thanks @minipli-oss. Closing this as fixed. @kedare please feel free to reopen if needed.
