### ISSUE TITLE
Wrong target directory for XML configuration

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#12]
Unfortunately, it is not possible to guess the exact directory where the package will be installed. Using virtualenv on Ubuntu, the target directory is "lib/python2.7/site-packages/chipsec/cfg" and not "Lib/site-packages/chipsec/cfg". The correct approach to solve this issue is to use package_data instead of data_files (see https://docs.python.org/2.7/distutils/setupscript.html#installing-package-data). This will copy the *.xml, *.xsd and VERSION files to the expected locations.

Although this seems like the final solution, it is worth noticing that we will now have a VERSION file in the middle of site-packages. Not the cleanest installation... This stems from the current directory layout, especially that the tools/ directory is considered as a package (which is not). Ideally, the chispec_main.py and chipsec_utils.py should be installed as scripts (see https://docs.python.org/2.7/distutils/setupscript.html#installing-scripts) and the VERSION file should simply be removed and the version added to `chipsec/__init__.py` under the variable `__version__` (see PEP 0396).

I've submitted a pull request for the partial fix described in the first paragraph.

**Comment by c7zero** [comment]
Closing to open another issue on VERSION file
