### ISSUE TITLE
CPU pinning doesn't work with Python 2

### ISSUE THREAD

**Issue by minipli-oss** [chipsec/chipsec#1210]
While working on issue #608 via PR #1208, I was wondering why different CPUs are sharing the same GDT while it should be a per-cpu one.

Adding the below diff made me see why:
```diff
diff --git a/chipsec/helper/linux/linuxhelper.py b/chipsec/helper/linux/linuxhelper.py
index e25b698083cf..c8ee95d9de3b 100644
--- a/chipsec/helper/linux/linuxhelper.py
+++ b/chipsec/helper/linux/linuxhelper.py
@@ -692,10 +692,14 @@ class LinuxHelper(Helper):
 
     def set_affinity(self, thread_id):
         try:
+            print("dbg: Setting affinitiy to: " + str(thread_id))
             os.sched_setaffinity(os.getpid(), {thread_id})
             return thread_id
-        except Exception:
+        except Exception as ex:
+            print("dbg: Caught exception: " + str(ex))
             return None
+        finally:
+            print("dbg: Affinitiy now: " + str(self.get_affinity()))
 
     #########################################################
     # (U)EFI Variable API
```

```sh-session
root@box:~# chipsec_util -i gdt 0 | grep Physical   
[cpu0] Physical Address: 0x000000000213C000
[cpu1] Physical Address: 0x000000000213C000
root@box:~# chipsec_util -i gdt 0 | grep dbg
dbg: Setting affinitiy to: 0
dbg: Caught exception: 'module' object has no attribute 'sched_setaffinity'
dbg: Affinitiy now: None
dbg: Setting affinitiy to: 1
dbg: Caught exception: 'module' object has no attribute 'sched_setaffinity'
dbg: Affinitiy now: None
root@box:~# 
```

The os module is lacking the required functions, making the call to `os.sched_setaffinity()` throw an exception that gets catched and basically ignored (the `return None`) making `set_affinity()` be a no-op. Therefore the current thread continues to run on the CPU it's running on and, in turn, gets the same address for the GDT.

In fact, `os.sched_[gs]etaffinity()` is only available in python 3. But `chipsec_util` nor `chipsec_main` do enforce the usage of python 3, just request the ambitious `python` interpreter which is still pointing to python 2.7 on my Debian 11 system:

```
root@box:~# head -1 $(which chipsec_util)
#! /usr/bin/python
root@box:~# python --version
Python 2.7.18
```

IMHO these are the two obvious ways to resolve this regression:
1. Reactivate the python2 compatible `sched_getaffinity` and `sched_setaffinity` wrappers that have been dropped in commit 66f93f1b3d179f09e51d3d3a04707b4e03abad31.
2. Make chipsec python3 only.

**Comment by npmitche** [comment]
Closing due to changes in #1218 and #1237.
