### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by minipli-oss** [chipsec/chipsec#1213]
The repo's README mentions the following:

```
Contact Us
----------

Mailing lists:

 * CHIPSEC users: [chipsec-users](https://groups.google.com/forum/#!forum/chipsec-users)
 * [CHIPSEC discussion list on 01.org](https://lists.01.org/mailman/listinfo/chipsec)
```

However, both links are dead.

The latter should probably be changed to <https://lists.01.org/hyperkitty/list/chipsec@lists.01.org/>, don't know about the google groups one, though.

**Comment by npmitche** [comment]
@johnloucaides Did you make any progress on figuring out what was up with the google group?
