### ISSUE TITLE
linuxhelper.py not compatible with Python 2

### ISSUE THREAD

**Issue by kerneis-anssi** [chipsec/chipsec#1236]
`linuxhelper.py` contains the line `data = buffer[base:base +new_size].tobytes()`. In Python 2, this causes an exception "array.array object has no attribute tobytes" because the method used to be called `tostring()` and has been renamed in Python 3.2. The bug yields a failure of the modules secureboot.variables and uefi.access_uefispec.

It would be reasonable to close this issue as "won't fix" since Python 2 has reached end-of-life, but I thought I'd report it in case you care since the rest of the codebase goes to great length supporting Python 2.

**Comment by npmitche** [comment]
Thank you for reporting. You are correct it's a "won't fix". The reason we go to great lengths to support Python 2 is for UEFI Shell support.

**Comment by frinzell** [comment]
Closing as won't fix.  Python 2 is EOL.
