### ISSUE TITLE
recompile driver on kernel upgrade for linux distro packaging

### ISSUE THREAD

**Issue by johnloucaides** [chipsec/chipsec#126]
For linux distros that package chipsec, we will want them to recompile the driver whenever they update the kernel. This may mean that we should store the driver in a separate place from the code. This issue is to figure out the path forward and resolve.

Some options for now:
 * pass a path for where to put the driver as an option to setup.py
 * call driver makefile each time you run chipsec to ensure it is up to date
 * leave as is (linux distro packages may break when distro updates kernel)

**Comment by archey** [comment]
It might be a good idea to remove the building of kernel module from the build scripts, this would allow pkgers to include it as a seperate pkg or a dependency of the chipsec tool. It could be updated as the kernel updates in each distro, to allow it to run accordingly.

**Comment by tweksteen** [comment]
It is already possible to build the package without building the driver: `python setup.py install --skip-driver` or `pip install --install-option="--skip-driver" chipsec`

**Comment by archey** [comment]
The skip-driver part is fine, its just figuring out a good place to drop the driver to allow distros to build it. I Believe the concensus is going to be drop it into dkms to rebuild it and have it be loaded and unloaded as needed by the tool.

**Comment by c7zero** [comment]
With dkms.conf and --skip-driver install option, I believe we have this issue solved. I intend to close unless there are objections.
