### ISSUE TITLE
Documentation lists "common.smi_lock" module, which doesn't work/exist in 1.7.1?

### ISSUE THREAD

**Issue by throwaway-a** [chipsec/chipsec#1263]
https://chipsec.github.io/Vulnerabilities-and-CHIPSEC-Modules.html shows a "common.smi_lock" module. Attempting to use it yields "ERROR: Exception occurred during import of chipsec.modules.common.smi_lock: 'No module named 'chipsec.modules.common.smi_lock''"

**Comment by Sae86** [comment]
Hi @throwaway-a thanks for bringing this up. I have opened a PR to update our documentation, please run "common.bios_smi" module instead
