### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by skweiler** [chipsec/chipsec#1295]
It looks like there is at least one missing module. chipsec_main.py runs just fine, but it isn't possible to run the module chipsec.modules.tools.uefi.whitelist. I haven't checked, but there may be more modules missing. It looks like the project needs to be updated.

**Comment by frinzell** [comment]
Hi @skweiler, this module was renamed last year to **scan_image.py**
#1018 
Hope this helps.

**Comment by skweiler** [comment]
Hello, @frinzell it appears to. Thank you. However, please see #1296.
