### ISSUE TITLE
Mixed EOL

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#13]
Most of the Python source files are using a mixture of LF and CRLF as end-of-line characters. This turns any contribution to the code into an obstacle course. Please pick one or the other and apply to all the source files.

If you decide to go for the CRLF (Windows option), it is as simple as running:

    find . -name \*.py -exec unix2dos {} \;

Once modified, git diff provides the option `--ignore-space-at-eol` to verify that only EOL characters have been adjusted.

**Comment by c7zero** [comment]
Tracking in PR #85
