### ISSUE TITLE
Wiki Page URL For Install In Linux Is Incorrect

### ISSUE THREAD

**Issue by alexis-evelyn** [chipsec/chipsec#1315]
The link posted in https://github.com/chipsec/chipsec/wiki/Installing-CHIPSEC-in-Linux is incorrect. The link points to https://chipsec.github.io/Install%20in%20Linux.html when it should point to https://chipsec.github.io/installation/Install%20in%20Linux.html.

**Comment by npmitche** [comment]
Updated. Thank you for pointing it out!
