### ISSUE TITLE
Don't run Intel-specific modules on AMD

### ISSUE THREAD

**Issue by kerneis-anssi** [chipsec/chipsec#1318]

**Comment by frinzell** [comment]
We included a lot of updates around this and believe most modules are addressed.  Using 1.8.7, do you see any modules  that should not run on AMD?

**Comment by kerneis-anssi** [comment]
No, this issue is fixed I think. Thanks! I'll send specific PR if I find issues in the future.

Les données à caractère personnel recueillies et traitées dans le cadre de cet échange, le sont à seule fin d’exécution d’une relation professionnelle et s’opèrent dans cette seule finalité et pour la durée nécessaire à cette relation. Si vous souhaitez faire usage de vos droits de consultation, de rectification et de suppression de vos données, veuillez contacter ***@***.*** Si vous avez reçu ce message par erreur, nous vous remercions d’en informer l’expéditeur et de détruire le message. The personal data collected and processed during this exchange aims solely at completing a business relationship and is limited to the necessary duration of that relationship. If you wish to use your rights of consultation, rectification and deletion of your data, please contact: ***@***.*** If you have received this message in error, we thank you for informing the sender and destroying the message.

**Comment by frinzell** [comment]
Thanks!  Closing issue.  Please open an issue if something arises.
