### ISSUE TITLE
Chipsec support for Saphirerapids

### ISSUE THREAD

**Issue by NishilKumar** [chipsec/chipsec#1342]
We are part of HPE Team which works with Saphirerapids Servers.
We were exploring option to run chipsec on Saphirerapids. But can see in help that it is not enabled yet for SPR.
When can we expect this to be enabled for Saphirerapids?

Source Code - https://github.com/chipsec/chipsec

Advanced Options:
  -p {RENOIR,APL,AVN,BDW,BDX,BYT,CFL,CHT,CML,DNV,GLK,HSW,HSX,ICL,ICX,IVB,IVT,JKT,KBL,QRK,RKL,SKL,SKX,SNB,TGLU,WHL}, --platform {RENOIR,APL,AVN,BDW,BDX,BYT,CFL,CHT,CML,DNV,GLK,HSW,HSX,ICL,ICX,IVB,IVT,JKT,KBL,QRK,RKL,SKL,SKX,SNB,TGLU,WHL}
                        explicitly specify platform code
  --pch {PCH_1XX,PCH_2XX,PCH_3XX,PCH_3XXLP,PCH_3XXOP,PCH_495,PCH_4XX,PCH_4XXH,PCH_4XXLP,PCH_5XXH,PCH_5XXLP,PCH_C60X,PCH_C61X,PCH_C620}

**Comment by npmitche** [comment]
Please reach out to us at chipsec@intel.com for information about Intel platform support.
