### ISSUE TITLE
Can't build the chipsec on x86 32-bit GNU/Linux

### ISSUE THREAD

**Issue by citypw** [chipsec/chipsec#139]
Testing platform: Debian 8 + kernel 4.9

> root@debian32-test:/home/shawn/chipsec# python setup.py install
running install
running bdist_egg
running egg_info
creating chipsec.egg-info
writing chipsec.egg-info/PKG-INFO
writing top-level names to chipsec.egg-info/top_level.txt
writing dependency_links to chipsec.egg-info/dependency_links.txt
writing entry points to chipsec.egg-info/entry_points.txt
writing manifest file 'chipsec.egg-info/SOURCES.txt'
reading manifest file 'chipsec.egg-info/SOURCES.txt'
writing manifest file 'chipsec.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
creating build
creating build/lib.linux-i686-2.7
copying chipsec_main.py -> build/lib.linux-i686-2.7
copying chipsec_util.py -> build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/chipsec_tools
copying chipsec_tools/__init__.py -> build/lib.linux-i686-2.7/chipsec_tools
creating build/lib.linux-i686-2.7/chipsec
copying chipsec/__init__.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/file.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/defines.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/module.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/module_common.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/logger.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/command.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/xmlout.py -> build/lib.linux-i686-2.7/chipsec
copying chipsec/chipset.py -> build/lib.linux-i686-2.7/chipsec
creating build/lib.linux-i686-2.7/chipsec_tools/linux
copying chipsec_tools/linux/__init__.py -> build/lib.linux-i686-2.7/chipsec_tools/linux
creating build/lib.linux-i686-2.7/chipsec_tools/windows
copying chipsec_tools/windows/__init__.py -> build/lib.linux-i686-2.7/chipsec_tools/windows
creating build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/__init__.py -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/common.py -> build/lib.linux-i686-2.7/chipsec/cfg
creating build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/ucode_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/__init__.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/mmio_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/pci_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/uefi_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/iommu_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/interrupts_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/ec_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/chipset_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/msgbus_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/acpi_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/decode_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/cmos_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/io_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/mem_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/vmm_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/spi_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/spd_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/cpu_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/spidesc_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/mmcfg_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/msr_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/smbus_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
copying chipsec/utilcmd/desc_cmd.py -> build/lib.linux-i686-2.7/chipsec/utilcmd
creating build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/acpi.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/mmio.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/__init__.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/ec.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/spi.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/tpm.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/uefi.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/iommu.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/vmm.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/hal_base.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/pcidb.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/uefi_common.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/smbus.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/uefi_platform.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/io.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/physmem.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/ucode.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/tpm12_commands.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/msgbus.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/cpuid.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/spi_descriptor.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/cpu.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/acpi_tables.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/pci.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/spi_uefi.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/cmos.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/uefi_search.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/spd.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/iobar.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/paging.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/interrupts.py -> build/lib.linux-i686-2.7/chipsec/hal
copying chipsec/hal/msr.py -> build/lib.linux-i686-2.7/chipsec/hal
creating build/lib.linux-i686-2.7/chipsec/helper
copying chipsec/helper/__init__.py -> build/lib.linux-i686-2.7/chipsec/helper
copying chipsec/helper/oshelper.py -> build/lib.linux-i686-2.7/chipsec/helper
copying chipsec/helper/helpers.py -> build/lib.linux-i686-2.7/chipsec/helper
creating build/lib.linux-i686-2.7/chipsec/modules
copying chipsec/modules/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules
copying chipsec/modules/remap.py -> build/lib.linux-i686-2.7/chipsec/modules
copying chipsec/modules/smm_dma.py -> build/lib.linux-i686-2.7/chipsec/modules
copying chipsec/modules/memconfig.py -> build/lib.linux-i686-2.7/chipsec/modules
creating build/lib.linux-i686-2.7/chipsec/helper/efi
copying chipsec/helper/efi/__init__.py -> build/lib.linux-i686-2.7/chipsec/helper/efi
copying chipsec/helper/efi/efihelper.py -> build/lib.linux-i686-2.7/chipsec/helper/efi
creating build/lib.linux-i686-2.7/chipsec/helper/osx
copying chipsec/helper/osx/__init__.py -> build/lib.linux-i686-2.7/chipsec/helper/osx
copying chipsec/helper/osx/helper.py -> build/lib.linux-i686-2.7/chipsec/helper/osx
creating build/lib.linux-i686-2.7/chipsec/helper/linux
copying chipsec/helper/linux/__init__.py -> build/lib.linux-i686-2.7/chipsec/helper/linux
copying chipsec/helper/linux/helper.py -> build/lib.linux-i686-2.7/chipsec/helper/linux
creating build/lib.linux-i686-2.7/chipsec/helper/win
copying chipsec/helper/win/__init__.py -> build/lib.linux-i686-2.7/chipsec/helper/win
copying chipsec/helper/win/win32helper.py -> build/lib.linux-i686-2.7/chipsec/helper/win
creating build/lib.linux-i686-2.7/chipsec/modules/byt
copying chipsec/modules/byt/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/byt
creating build/lib.linux-i686-2.7/chipsec/modules/tools
copying chipsec/modules/tools/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools
creating build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_ts.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_wp.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/spi_fdopss.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_smi.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/spi_desc.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/rtclock.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/ia32cfg.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/smm.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_kbrd_buffer.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/spi_lock.py -> build/lib.linux-i686-2.7/chipsec/modules/common
copying chipsec/modules/common/smrr.py -> build/lib.linux-i686-2.7/chipsec/modules/common
creating build/lib.linux-i686-2.7/chipsec/modules/snb
copying chipsec/modules/snb/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/snb
creating build/lib.linux-i686-2.7/chipsec/modules/ivb
copying chipsec/modules/ivb/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/ivb
creating build/lib.linux-i686-2.7/chipsec/modules/bdw
copying chipsec/modules/bdw/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/bdw
creating build/lib.linux-i686-2.7/chipsec/modules/hsw
copying chipsec/modules/hsw/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/hsw
creating build/lib.linux-i686-2.7/chipsec/modules/tools/cpu
copying chipsec/modules/tools/cpu/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/cpu
copying chipsec/modules/tools/cpu/sinkhole.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/cpu
creating build/lib.linux-i686-2.7/chipsec/modules/tools/secureboot
copying chipsec/modules/tools/secureboot/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/secureboot
copying chipsec/modules/tools/secureboot/te.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/secureboot
creating build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/pcie_overlap_fuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/common.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/cpuid_fuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/pcie_fuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/msr_fuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/iofuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/venom.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/hypercallfuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm
creating build/lib.linux-i686-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/uefi/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/uefi/blacklist.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/uefi/s3script_modify.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/uefi
creating build/lib.linux-i686-2.7/chipsec/modules/tools/smm
copying chipsec/modules/tools/smm/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/smm
copying chipsec/modules/tools/smm/smm_ptr.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/smm
creating build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/hypercall.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/hypercallfuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/xsa188.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/define.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/xen
creating build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/vbox
copying chipsec/modules/tools/vmm/vbox/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/vbox
copying chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/vbox
creating build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/synth_dev.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/synth_kbd.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/hypercall.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/vmbusfuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/hypercallfuzz.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/vmbus.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/define.py -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
creating build/lib.linux-i686-2.7/chipsec/modules/common/secureboot
copying chipsec/modules/common/secureboot/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/common/secureboot
copying chipsec/modules/common/secureboot/variables.py -> build/lib.linux-i686-2.7/chipsec/modules/common/secureboot
creating build/lib.linux-i686-2.7/chipsec/modules/common/uefi
copying chipsec/modules/common/uefi/__init__.py -> build/lib.linux-i686-2.7/chipsec/modules/common/uefi
copying chipsec/modules/common/uefi/s3bootscript.py -> build/lib.linux-i686-2.7/chipsec/modules/common/uefi
copying chipsec/modules/common/uefi/access_uefispec.py -> build/lib.linux-i686-2.7/chipsec/modules/common/uefi
copying chipsec/VERSION -> build/lib.linux-i686-2.7/chipsec
copying chipsec/WARNING.txt -> build/lib.linux-i686-2.7/chipsec
copying chipsec_tools/linux/TianoCompress.bin -> build/lib.linux-i686-2.7/chipsec_tools/linux
copying chipsec_tools/linux/LzmaCompress.bin -> build/lib.linux-i686-2.7/chipsec_tools/linux
copying chipsec/cfg/jkt.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/skl.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/avn.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/kbl.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/bdw.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/common.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/qrk.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/hsx.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/cht.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/byt.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/hsw.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/template.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/ivt.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/iommu.xml -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/cfg/chipsec_cfg.xsd -> build/lib.linux-i686-2.7/chipsec/cfg
copying chipsec/modules/tools/secureboot/te.cfg -> build/lib.linux-i686-2.7/chipsec/modules/tools/secureboot
copying chipsec/modules/tools/uefi/blacklist.json -> build/lib.linux-i686-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/smm/smm_config.ini -> build/lib.linux-i686-2.7/chipsec/modules/tools/smm
copying chipsec/modules/tools/vmm/hv/initial_data.json -> build/lib.linux-i686-2.7/chipsec/modules/tools/vmm/hv
running build_ext
building 'chipsec.helper.linux.cores' extension
creating build/temp.linux-i686-2.7
creating build/temp.linux-i686-2.7/chipsec
creating build/temp.linux-i686-2.7/chipsec/helper
creating build/temp.linux-i686-2.7/chipsec/helper/linux
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c chipsec/helper/linux/cores.c -o build/temp.linux-i686-2.7/chipsec/helper/linux/cores.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-i686-2.7/chipsec/helper/linux/cores.o -o build/lib.linux-i686-2.7/chipsec/helper/linux/cores.so
building the linux driver
creating /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers
creating /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux
creating /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/i386
copying drivers/linux/i386/cpu.asm -> /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/i386
copying drivers/linux/AUTHORS -> /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux
copying drivers/linux/chipsec_km.c -> /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux
copying drivers/linux/dkms.conf -> /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux
copying drivers/linux/README -> /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux
copying drivers/linux/Makefile -> /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux
copying drivers/linux/WARNING.txt -> /home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux
/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.c:589:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  ucode_start = (unsigned long long)ucode_buf;
                ^
/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.c: In function ‘d_ioctl’:
/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.c:1435:18: error: label at end of compound statement
             case 8:
                  ^
/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.c:1410:36: warning: unused variable ‘second’ [-Wunused-variable]
         unsigned long addr, first, second;
                                    ^
/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.c:1410:29: warning: unused variable ‘first’ [-Wunused-variable]
         unsigned long addr, first, second;
                             ^
/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.c: In function ‘cleanup_module’:
/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.c:1685:9: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘physaddr_t’ [-Wformat=]
         printk(KERN_INFO "auto freeing allocated memory (va = %p, pa = 0x%llx)\n", element->va, element->pa);
         ^
make[2]: *** [/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux/chipsec_km.o] Error 1
make[1]: *** [_module_/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux] Error 2
make: *** [chipsec] Error 2
Traceback (most recent call last):
  File "setup.py", line 206, in <module>
    **extra_kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 22, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 112, in run
    self._build_linux_driver()
  File "setup.py", line 77, in _build_linux_driver
    subprocess.check_output(["make", "-C", build_driver])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['make', '-C', '/home/shawn/chipsec/build/lib.linux-i686-2.7/drivers/linux']' returned non-zero exit status 2

**Comment by tweksteen** [comment]
Definitely a bug, thanks for reporting!
