### ISSUE TITLE
can't build with GCC plugins( e.g: latent_entropy)

### ISSUE THREAD

**Issue by citypw** [chipsec/chipsec#140]
Platform: Debian 8( x86_64) + kernel 4.9

> root@debian8-test:/home/shawn/chipsec# python setup.py install
running install
running bdist_egg
running egg_info
writing chipsec.egg-info/PKG-INFO
writing top-level names to chipsec.egg-info/top_level.txt
writing dependency_links to chipsec.egg-info/dependency_links.txt
writing entry points to chipsec.egg-info/entry_points.txt
reading manifest file 'chipsec.egg-info/SOURCES.txt'
writing manifest file 'chipsec.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying chipsec_main.py -> build/lib.linux-x86_64-2.7
copying chipsec_util.py -> build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/chipsec_tools
copying chipsec_tools/__init__.py -> build/lib.linux-x86_64-2.7/chipsec_tools
creating build/lib.linux-x86_64-2.7/chipsec
copying chipsec/module_common.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/chipset.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/logger.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/module.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/file.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/__init__.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/defines.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/command.py -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/xmlout.py -> build/lib.linux-x86_64-2.7/chipsec
creating build/lib.linux-x86_64-2.7/chipsec_tools/linux
copying chipsec_tools/linux/__init__.py -> build/lib.linux-x86_64-2.7/chipsec_tools/linux
creating build/lib.linux-x86_64-2.7/chipsec_tools/windows
copying chipsec_tools/windows/__init__.py -> build/lib.linux-x86_64-2.7/chipsec_tools/windows
creating build/lib.linux-x86_64-2.7/chipsec/helper
copying chipsec/helper/helpers.py -> build/lib.linux-x86_64-2.7/chipsec/helper
copying chipsec/helper/oshelper.py -> build/lib.linux-x86_64-2.7/chipsec/helper
copying chipsec/helper/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/helper
creating build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/uefi_common.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/cmos.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/io.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/paging.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/cpuid.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/mmio.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/msr.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/tpm12_commands.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/iommu.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/smbus.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/pci.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/interrupts.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/uefi_search.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/spi_uefi.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/spi.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/ec.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/acpi.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/msgbus.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/ucode.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/uefi.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/spd.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/spi_descriptor.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/vmm.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/cpu.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/physmem.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/uefi_platform.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/hal_base.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/iobar.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/pcidb.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/tpm.py -> build/lib.linux-x86_64-2.7/chipsec/hal
copying chipsec/hal/acpi_tables.py -> build/lib.linux-x86_64-2.7/chipsec/hal
creating build/lib.linux-x86_64-2.7/chipsec/modules
copying chipsec/modules/smm_dma.py -> build/lib.linux-x86_64-2.7/chipsec/modules
copying chipsec/modules/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules
copying chipsec/modules/remap.py -> build/lib.linux-x86_64-2.7/chipsec/modules
copying chipsec/modules/memconfig.py -> build/lib.linux-x86_64-2.7/chipsec/modules
creating build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/ec_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/cmos_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/spi_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/acpi_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/decode_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/chipset_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/interrupts_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/pci_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/iommu_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/vmm_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/desc_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/mmio_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/smbus_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/uefi_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/spidesc_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/msr_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/mmcfg_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/spd_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/cpu_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/io_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/mem_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/ucode_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
copying chipsec/utilcmd/msgbus_cmd.py -> build/lib.linux-x86_64-2.7/chipsec/utilcmd
creating build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/common.py -> build/lib.linux-x86_64-2.7/chipsec/cfg
creating build/lib.linux-x86_64-2.7/chipsec/helper/osx
copying chipsec/helper/osx/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/helper/osx
copying chipsec/helper/osx/helper.py -> build/lib.linux-x86_64-2.7/chipsec/helper/osx
creating build/lib.linux-x86_64-2.7/chipsec/helper/efi
copying chipsec/helper/efi/efihelper.py -> build/lib.linux-x86_64-2.7/chipsec/helper/efi
copying chipsec/helper/efi/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/helper/efi
creating build/lib.linux-x86_64-2.7/chipsec/helper/linux
copying chipsec/helper/linux/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/helper/linux
copying chipsec/helper/linux/helper.py -> build/lib.linux-x86_64-2.7/chipsec/helper/linux
creating build/lib.linux-x86_64-2.7/chipsec/helper/win
copying chipsec/helper/win/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/helper/win
copying chipsec/helper/win/win32helper.py -> build/lib.linux-x86_64-2.7/chipsec/helper/win
creating build/lib.linux-x86_64-2.7/chipsec/modules/byt
copying chipsec/modules/byt/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/byt
creating build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_kbrd_buffer.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_wp.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/spi_desc.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/spi_fdopss.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/rtclock.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_smi.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/spi_lock.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/smrr.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/ia32cfg.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/bios_ts.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
copying chipsec/modules/common/smm.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common
creating build/lib.linux-x86_64-2.7/chipsec/modules/ivb
copying chipsec/modules/ivb/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/ivb
creating build/lib.linux-x86_64-2.7/chipsec/modules/snb
copying chipsec/modules/snb/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/snb
creating build/lib.linux-x86_64-2.7/chipsec/modules/hsw
copying chipsec/modules/hsw/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/hsw
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools
copying chipsec/modules/tools/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools
creating build/lib.linux-x86_64-2.7/chipsec/modules/bdw
copying chipsec/modules/bdw/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/bdw
creating build/lib.linux-x86_64-2.7/chipsec/modules/common/uefi
copying chipsec/modules/common/uefi/s3bootscript.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common/uefi
copying chipsec/modules/common/uefi/access_uefispec.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common/uefi
copying chipsec/modules/common/uefi/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common/uefi
creating build/lib.linux-x86_64-2.7/chipsec/modules/common/secureboot
copying chipsec/modules/common/secureboot/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common/secureboot
copying chipsec/modules/common/secureboot/variables.py -> build/lib.linux-x86_64-2.7/chipsec/modules/common/secureboot
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/smm
copying chipsec/modules/tools/smm/smm_ptr.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/smm
copying chipsec/modules/tools/smm/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/smm
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/uefi/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/uefi/blacklist.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/uefi/s3script_modify.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/uefi
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/cpu
copying chipsec/modules/tools/cpu/sinkhole.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/cpu
copying chipsec/modules/tools/cpu/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/cpu
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/pcie_overlap_fuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/iofuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/msr_fuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/cpuid_fuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/venom.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/hypercallfuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/pcie_fuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
copying chipsec/modules/tools/vmm/common.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/secureboot
copying chipsec/modules/tools/secureboot/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/secureboot
copying chipsec/modules/tools/secureboot/te.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/secureboot
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/synth_dev.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/vmbusfuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/define.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/vmbus.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/synth_kbd.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/hypercall.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
copying chipsec/modules/tools/vmm/hv/hypercallfuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/vbox
copying chipsec/modules/tools/vmm/vbox/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/vbox
copying chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/vbox
creating build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/xsa188.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/define.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/__init__.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/hypercall.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/modules/tools/vmm/xen/hypercallfuzz.py -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/xen
copying chipsec/VERSION -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec/WARNING.txt -> build/lib.linux-x86_64-2.7/chipsec
copying chipsec_tools/linux/TianoCompress.bin -> build/lib.linux-x86_64-2.7/chipsec_tools/linux
copying chipsec_tools/linux/LzmaCompress.bin -> build/lib.linux-x86_64-2.7/chipsec_tools/linux
copying chipsec/cfg/cht.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/common.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/hsx.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/qrk.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/bdw.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/jkt.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/iommu.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/kbl.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/skl.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/hsw.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/byt.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/avn.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/ivt.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/template.xml -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/cfg/chipsec_cfg.xsd -> build/lib.linux-x86_64-2.7/chipsec/cfg
copying chipsec/modules/tools/smm/smm_config.ini -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/smm
copying chipsec/modules/tools/uefi/blacklist.json -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/uefi
copying chipsec/modules/tools/secureboot/te.cfg -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/secureboot
copying chipsec/modules/tools/vmm/hv/initial_data.json -> build/lib.linux-x86_64-2.7/chipsec/modules/tools/vmm/hv
running build_ext
building 'chipsec.helper.linux.cores' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/chipsec
creating build/temp.linux-x86_64-2.7/chipsec/helper
creating build/temp.linux-x86_64-2.7/chipsec/helper/linux
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c chipsec/helper/linux/cores.c -o build/temp.linux-x86_64-2.7/chipsec/helper/linux/cores.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/chipsec/helper/linux/cores.o -o build/lib.linux-x86_64-2.7/chipsec/helper/linux/cores.so
building the linux driver
creating /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers
creating /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
copying drivers/linux/dkms.conf -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
copying drivers/linux/README -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
copying drivers/linux/COPYING -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
creating /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux/include
copying drivers/linux/include/chipsec.h -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux/include
creating /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux/amd64
copying drivers/linux/amd64/cpu.asm -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux/amd64
copying drivers/linux/chipsec_km.c -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
creating /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux/i386
copying drivers/linux/i386/cpu.asm -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux/i386
copying drivers/linux/Makefile -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
copying drivers/linux/AUTHORS -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
copying drivers/linux/WARNING.txt -> /home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux
cc1: error: cannot load plugin ./scripts/gcc-plugins/latent_entropy_plugin.so
./scripts/gcc-plugins/latent_entropy_plugin.so: undefined symbol: symtab
make[2]: *** [/home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux/chipsec_km.o] Error 1
make[1]: *** [_module_/home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux] Error 2
make: *** [chipsec] Error 2
Traceback (most recent call last):
  File "setup.py", line 206, in <module>
    **extra_kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 22, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 112, in run
    self._build_linux_driver()
  File "setup.py", line 77, in _build_linux_driver
    subprocess.check_output(["make", "-C", build_driver])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['make', '-C', '/home/shawn/chipsec/build/lib.linux-x86_64-2.7/drivers/linux']' returned non-zero exit status 2

**Comment by tweksteen** [comment]
There seems to be an issue with your GCC plugin itself: 

    cc1: error: cannot load plugin ./scripts/gcc-plugins/latent_entropy_plugin.so
    ./scripts/gcc-plugins/latent_entropy_plugin.so: undefined symbol: symtab

Does it build fine without the plugins enabled?

**Comment by citypw** [comment]
Yes, it's working perfect fine without GCC plugins.

**Comment by tweksteen** [comment]
I'm closing this issue then. Feel free to reopen if you think this issue is related to Chipsec and not your plugin.

**Comment by citypw** [comment]
Hi, this plugin is not "mine" technically;-) Some GNU/Linux distro might ship with some GCC plugins in the future. The latent_entropy was merged( ported from PaX/Grsecurity) in v4.9. Chipsec will face this problem soon or later.

**Comment by tweksteen** [comment]
I agree that we should support this plugin if this is part of the official kernel. However, the error you reported seems to be related to the plugin (or how the plugin is installed) and not to Chipsec itself.
./scripts/gcc-plugins/latent_entropy_plugin.so: undefined symbol: symtab

**Comment by citypw** [comment]
I built & installed kernel v4.9 in the default way. CONFIG_GCC_PLUGIN_LATENT_ENTROPY & CONFIG_GCC_PLUGINS are set in the build config and that's all.
