### ISSUE TITLE
bios_wp.py - Modifying list while in a for loop

### ISSUE THREAD

**Issue by BrentHoltsclaw** [chipsec/chipsec#1412]
Found while testing out semgrep:
   chipsec/modules/common/bios_wp.py
     python.lang.correctness.list-modify-iterating.list-modify-while-iterate
        It appears that `areas_to_protect` is a list that is being modified while in a for loop.
        This will likely cause a runtime error or an infinite loop.
Details: https://sg.run/0Qr5

https://github.com/chipsec/chipsec/blob/de749c01de0b2212bd2e0cccbcdb7f844cb915d4/chipsec/modules/common/bios_wp.py#L93-#L116

**Comment by frinzell** [comment]
Good find!
