### ISSUE TITLE
Add Travis CI test to build driver for Linux (32 bits)

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#142]
Currently, only the 64 bits version of the Linux driver is built on Travis. By adding a test to automatically build the 32 bits version, we will be able to catch bugs similar to #139.

**Comment by BrentHoltsclaw** [comment]
@tweksteen It looks like adding 32 bit support would take some docker magic.  Is this still something that you would like to see within the CI?  I added multi os support and will add python3 support once it becomes integrated into the main branch.
@ErikBjorge @johnloucaides Thoughts?
