### ISSUE TITLE
service chipsec didn't start

### ISSUE THREAD

**Issue by Mimikatz-01** [chipsec/chipsec#1468]
Everything was working fine - but today I got this message

> ERROR: Message: "service 'chipsec' didn't start: Windows cannot verify the digital signature of this file. The last hardware or software change might have installed an incorrectly signed or corrupted file or malware of unknown origin. (577)"

How to solve this?

**Comment by Mimikatz-01** [comment]
bcdedit /set testsigning off  - didn't hellp

**Comment by Sae86** [comment]
Hi @Mimikatz-01! Which version are you using? Is this with the latest version (1.8.4)?

**Comment by Mimikatz-01** [comment]
yes [CHIPSEC] Version : 1.8.4

**Comment by Mimikatz-01** [comment]
I got this problem after windows update

**Comment by Mimikatz-01** [comment]
I figured it out. This is my oversight
