### ISSUE TITLE
Implement option parsing in chipsec_utils.py

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#147]
Currently, there is not proper command line option parsing in chipsec_utils. Only "-n" is manually implemented.  We should implement correct parsing using getopt (similarly to what chipsec_main is doing). 

This includes handling:
* The different verbose modes (`-v-`, `-d`, replacing HAL and UTIL_TRACE global variables)
* Specify a plarform (`-p`)

**Comment by c7zero** [comment]
Closed with #158
