### ISSUE TITLE
Chipset does not support hardware sequencing

### ISSUE THREAD

**Issue by JonathanGoikhman** [chipsec/chipsec#1471]
Hi,
running the tool on Ubuntu VM. When trying to dump SPI content I get the error: HSFS.FDV is 0, hardware sequencing is disabled 
and  Chipset does not support hardware sequencing. 

Searched the manuel and previous issues but couldn't find anything.

**Comment by npmitche** [comment]
Hi Jonathan,
The HSFS.FDV bit is the Flash Descriptor Valid field. If this is 0, sequencing does not make sense and cannot be trusted.  Chipsec is primarily designed for bare metal platforms, not VMs.
