### ISSUE TITLE
Build fails on Fedora 36 (-Werror in LzmaEnc.c)

### ISSUE THREAD

**Issue by kerneis-anssi** [chipsec/chipsec#1473]
On Fedora 36, installing the recommended dependencies with `dnf` and running `python setup.py build_ext -i` fails with the following warning treated as an error:

```
Sdk/C/LzmaEnc.c: In function ‘LzmaEnc_CodeOneMemBlock’:
Sdk/C/LzmaEnc.c:2641:19: error: storing the address of local variable ‘outStream’ in ‘*p.rc.outStream’ [-Werror=dangling-pointer=]
 2641 |   p->rc.outStream = &outStream.vt;
      |   ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
Sdk/C/LzmaEnc.c:2624:28: note: ‘outStream’ declared here
 2624 |   CLzmaEnc_SeqOutStreamBuf outStream;
      |                            ^~~~~~~~~
Sdk/C/LzmaEnc.c:2624:28: note: ‘pp’ declared here
```

Removing `-Werror` from chipsec_tools/compression/Makefiles/header.makefile works around the issue. `gcc --version` returns `gcc (GCC) 12.0.1 20220413 (Red Hat 12.0.1-0)`.

**Comment by npmitche** [comment]
Should be fixed with PR https://github.com/chipsec/chipsec/pull/1487
