### ISSUE TITLE
Poor list formatting in PDF manual.

### ISSUE THREAD

**Issue by vi** [chipsec/chipsec#1482]
> https://github.com/chipsec/chipsec/blob/main/chipsec-manual.pdf

> Warning
> Chipsec should only ...
> ... reasons for that:
> 1\. ...
> 1\. ...
> 1\. ...

Instead of "1.", "2.", "3.". Looks like it was improperly converted from Markdown.

**Comment by npmitche** [comment]
On page 9. Thanks for spotting this.

**Comment by Sae86** [comment]
> On page 9. Thanks for spotting this.

Fix for this in PR #1484
