### ISSUE TITLE
Implement *_EFI_variable for OSX helper

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#149]
This includes:
* EFI_supported
* list_EFI_variables
* get_EFI_variable
* set_EFI_variable
* delete_EFI_variable

**Comment by c7zero** [comment]
In addition to _EFI_variable functions, implement read/write IO ports and read/write MSR. 

EFI_supported should probably be just "return True" when _EFI_variables are implemented.

Make sure modules which are currently skipped on macOS are can run on macOS.

**Comment by npmitche** [comment]
Closing as OSX Support is deprecated.
