### ISSUE TITLE
Refactor the logging code to use Python's default classes

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#151]
This is a ticket to keep track of the refactoring of the logging code. What should be done:

* Refactor logger.py. Create a default logger class that extends logging.Logger. Create three Handlers: console, log file and XML output. Move the coloring code to a Formatter class (we may want to reuse existing code such as [coloredlogs](https://coloredlogs.readthedocs.io)).

* Update all the calling code. Add a `self.logger = logging.getLogger(__name__)` to automatically populate the location of the log. (No more "[modules]" in the log messages themselves). There should be no more conditional call for logging in the code (i.e., if logger().VERBOSE:...)

* Update chipsec_main and chipsec_utils to use and configure the new logging flags. (e.g., HAL can be replaced by a [filter](https://docs.python.org/2/library/logging.html#filter-objects) on the calling site).

**Comment by ErikBjorge** [comment]
Done.  Please open a new issue for any bugs you find.
