### ISSUE TITLE
os crash (kernel panic) during chipsec_main.py test execution

### ISSUE THREAD

**Issue by amouhk** [chipsec/chipsec#1524]
Hi guys,
chipsec version used : 1.8.5 and 1.8.6.
During the exection of the test `python3.8 chipsec_main.py`, the test stop at "Running module: chipsec.modules.common.wsmt" then my operation system (RHEL 8.5) crashes.

I do not have any issue with the previous release (last release tested sucessfully 1.7.3).
By follow where the test stops at I find out the code has been modify to support WSMT module on all operating systems.
Do you thing this can be the root cause ? Does anyone have the same issue ?
How to by pass WSMT module test if it is the root cause ?

Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz

@assafcarlsbad 
@BrentHoltsclaw

**Comment by BrentHoltsclaw** [comment]
@amouhk Please run the command with all logging options enabled and post the output of where the crash is occurring.  There have been problems in the past with memory access when searching for the acpi tables, but within logging it's hard to speculate.  
`chipsec_main.py --vv -m common.wsmt`

**Comment by BrentHoltsclaw** [comment]
chipsec_main will run all files within the modules.common directory with the .py extension.  A module can be bypassed if by removing the file from the directory or changing the extension of the file.

**Comment by npmitche** [comment]
Hi amouhk,
We are currently moving the test module into tools (#1525) so it won't run under chipsec_main by default while we continue to look into this issue. As Brent mentioned, the issue comes from our search for the acpi tables. We are exploring other ways of finding the tables. Ultimately the issue is the platform is panicking when we poke at protected memory.

**Comment by amouhk** [comment]
Hi all,
Thank you all for looking into this issue. I will bypass this module by renaming the file  into order to use v1.8.6.

**Comment by amouhk** [comment]
Test sucessfully with v1.8.8 and v1.9.0
