### ISSUE TITLE
The manual says Python 2 is deprecated, but still uses Python 2 for the Linux build instructions

### ISSUE THREAD

**Issue by hamishmb** [chipsec/chipsec#1536]
Hi there,

I noticed when building this today that your manual says Python 2 is deprecated, but it still uses Python 2 in the build instructions for Linux. I tried using Python 3 (3.8.10) instead during the build, but it failed. I'm using Linux Mint 20.3 (Ubuntu 20.04 LTS base) with Linux 5.15.0-41 if that's useful information.

Note that I had success then running Chipsec with Python 3 after the build.

**Comment by npmitche** [comment]
Yeah, we still have some floating python2 references that we're working on cleaning up. Did you try the build commands found here: https://chipsec.github.io/installation/Install%20in%20Linux.html ?

Can you provide logs for the build failure you're seeing?

**Comment by hamishmb** [comment]
Hmm, that's interesting, it's working now, both for the latest commit and v1.8.6. Nevermind.
