### ISSUE TITLE
Linux: Build and install instructions are split across multiple places in the user manual

### ISSUE THREAD

**Issue by hamishmb** [chipsec/chipsec#1537]
The Linux build and install instructions are split across multiple places in the manual - this is fairly unclear and makes it hard to know how to run the finished build.

In retrospect, it seems obvious a setup.py install is needed, but considering a kernel module is involved, this isn't immediately apparent.

**Comment by npmitche** [comment]
Can you reference which sections specifically are confusing?

**Comment by hamishmb** [comment]
This section includes the build instructions: [https://chipsec.github.io/installation/Install%20in%20Linux.html](https://chipsec.github.io/installation/Install%20in%20Linux.html)

The install instructions for Linux, however, are instead only here: [https://chipsec.github.io/installation/Using-CHIPSEC-with-Kali-Linux.html?highlight=setup%20py%20install](https://chipsec.github.io/installation/Using-CHIPSEC-with-Kali-Linux.html?highlight=setup%20py%20install).

**Comment by hamishmb** [comment]
Cheers :)
