### ISSUE TITLE
python368 urllib.request import error - no module named _socket

### ISSUE THREAD

**Issue by charge007** [chipsec/chipsec#1565]
Hi

Trying to import urllib.request or socket fails with the following issue :

`
import socket

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "FS0:\Efi\StdLib\lib\python36.8\socket.py", line 49, in <module>

    import _socket

ModuleNotFoundError: No module named '_socket'
`

**Comment by frinzell** [comment]
Hi, are you building the Python 368 clean from the EDK2-LIBC repo?

**Comment by frinzell** [comment]
Ah, I think I see, you are simply trying to import urllib.request?
This does not appear in the list of [tested library modules ](https://github.com/intel-innersource/applications.validation.advancedsystemtools.products.python-efi/blob/main/Python/Python-3.6.8/Py368ReadMe.txt) (end of doc).  May have to approach the [Python 3.6.8](https://github.com/intel-innersource/applications.validation.advancedsystemtools.products.python-efi/tree/main/Python/Python-3.6.8) code maintainer.  We've seen library issues in the past that were due to an unexpected environment (ie the shell).

**Comment by charge007** [comment]
Correct, import socket fails as well.
I tried adding more stuff to sys.path but it doesnt help.
Is there any other way of getting these libs to work in uefi shell ? 
Thanks

**Comment by frinzell** [comment]
The [Python 3.6.8](https://github.com/intel-innersource/applications.validation.advancedsystemtools.products.python-efi/tree/main/Python/Python-3.6.8) code maintainer would be in a better position to address this.  Recommend filing this with the [TianoCore Bugzilla](https://bugzilla.tianocore.org/).  For reference: here is the [uuid.py issue](https://bugzilla.tianocore.org/show_bug.cgi?id=3899) that was recently fixed.  Hope this helps.

**Comment by frinzell** [comment]
EDK2-LIBC BZ issue created:
https://bugzilla.tianocore.org/show_bug.cgi?id=4406

**Comment by frinzell** [comment]
@charge007 to enable socket support, you will need to build the EFI Python using step 6 in from the [Py368ReadMe.txt](https://github.com/tianocore/edk2-libc/blob/master/AppPkg/Applications/Python/Python-3.6.8/Py368ReadMe.txt)

As described in the readme, you will need to enable the commented out code in these files:
https://github.com/tianocore/edk2-libc/blob/master/AppPkg/Applications/Python/Python-3.6.8/PyMod-3.6.8/Modules/config.c
https://github.com/tianocore/edk2-libc/blob/master/AppPkg/Applications/Python/Python-3.6.8/Python368.inf

You will have to build using the MSVS tool chain.

Also, recommend using the latest EDK2-LIBC code, all CHIPSEC added support was ported to it just recently.  No need to merge in any files from this repo.

**Comment by frinzell** [comment]
Closing this as not a CHIPSEC tool issue.  The Tianocore BZ ticket will remain open and I'll continue working with the dev team to see what can be done.  Until then, following the build steps described in the Py368ReadMe.txt should give the support needed.  Feel free to reopen or follow up as needed.  Thanks.

**Comment by charge007** [comment]
Thank you very much sir

בתאריך יום ה׳, 13 באפר׳ 2023, 19:18, מאת Aaron Frinzell ‏<
***@***.***>:
