### ISSUE TITLE
Wrong PEP number in Python code style documentation

### ISSUE THREAD

**Issue by fishilico** [chipsec/chipsec#1600]
Hello,
While reading the documentation about the Python code style (https://github.com/chipsec/chipsec/blob/1.9.1/docs/sphinx/contribution/code-style-python.rst, https://chipsec.github.io/contribution/code-style-python.html), I followed the link

```text
PEP 598 | TypedDict: Type Hints for Dictionaries with a Fixed Set of Keys
```

This goes to <https://peps.python.org/pep-0598/>, "PEP 598 – Introducing incremental feature releases". This is not the right PEP.

The one named "TypedDict: Type Hints for Dictionaries with a Fixed Set of Keys" is PEP 589: <https://peps.python.org/pep-0589/>. I suppose that the reference needs to be fixed.

Anyway, thanks for maintaining this table of supported PEP! It is very clear and helpful :smiley:

**Comment by frinzell** [comment]
Thanks for the find!  Seems I superimposed two numbers.
