### ISSUE TITLE
[!] WARNING: chipsec.modules.common.uefi.access_uefispec

### ISSUE THREAD

**Issue by ycui9** [chipsec/chipsec#162]
the warning could be found with CRB BIOS, detail log as below.
Is it normal behavior?

[WARNING]

[!] WARNING: chipsec.modules.common.uefi.access_uefispec
[*] running module: chipsec.modules.common.uefi.access_uefispec

[*] Module path: chipsec/modules/common/uefi/access_uefispec.pyc

[x][ =======================================================================

[x][ Module: Access Control of EFI Variables

[x][ =======================================================================

[*] Testing UEFI variables ..

[!] Found two instances of the variable ConOut.

[*] Variable ConOut (NV+BS+RT)

[*] Variable ConOut (BS)

[!]   Missing attributes:NV+RT

[!] Found two instances of the variable ConIn.

[*] Variable ConIn (NV+BS+RT)

[*] Variable ConIn (BS)

[!]   Missing attributes:NV+RT

 

 

[-] Variables with attributes that differ from UEFI spec:

    ConOut

    ConIn

**Comment by johnloucaides** [comment]
This is probably not a big deal, especially for ConIn and ConOut variables. In fact,  However, the expected values are defined in the UEFI spec Table 11, which shows NV, BS, and RT for these variables. Note that the test only returns warning, indicating that manual analysis is required to confirm the issue.
