### ISSUE TITLE
Colorized logging within log files

### ISSUE THREAD

**Issue by BrentHoltsclaw** [chipsec/chipsec#1635]
Found when using the -l flag or reading logging files within the logs directory that colorized txt is being applied.

With some basic research on the topic may want to consider moving from overriding `logging.LogRecord` to creating a custom formatter (`logging.Formatter`) and applying it to the `StreamHandler`.

May be related to #1629

**Comment by npmitche** [comment]
Should be fixed with https://github.com/chipsec/chipsec/pull/1646. Please re-open if not the case.
