### ISSUE TITLE
Failure to update/retrieve EFI module children attributes

### ISSUE THREAD

**Issue by platomav** [chipsec/chipsec#1637]
When [update_efi_tree()](https://github.com/chipsec/chipsec/blob/53bbf5f9c095135cc7e9dfb14e67bbab6a834d20/chipsec/hal/spi_uefi.py#L316) is called recursively to update the attributes of a module which contains children, it is possible for the children attributes to be partially updated (effectively skipped) because a premature "return" occurs when a UI section is encountered. This means that the children modules may have missing (i.e. None) value for (parent) GUID.

![2 ARKE v1 7 2 -- 1 System BIOS with BiosGuard v1 7 2](https://user-images.githubusercontent.com/11527726/212162256-cfeda773-7a7d-423d-8844-5aeac41c0e79.jpg)

For some reason, update_efi_tree() function appears to have two purposes: 1) Update EFI tree, but also 2) Return the name (ui_string) of a given module. It should only be doing the former and separate the returning of a module's name to a different function.

Either way, it seems that the bug can be fixed by replacing the premature "return" statement with a "ui_string" variable assignment instead, which is then properly returned at the end of the update_efi_tree() function.

Before:

https://github.com/chipsec/chipsec/blob/53bbf5f9c095135cc7e9dfb14e67bbab6a834d20/chipsec/hal/spi_uefi.py#L329

After:

https://github.com/platomav/chipsec/blob/ffe8293385deac50a4c481a650c4d9e7af5a35cf/chipsec/hal/spi_uefi.py#L329

Steps to reproduce:

`chipsec_main.py --skip_config -i -n -m tools.uefi.scan_image -a generate "2 ARKE v1.7.2 -- 1 System BIOS with BiosGuard v1.7.2.json" "2 ARKE v1.7.2 -- 1 System BIOS with BiosGuard v1.7.2.bin"`

Look for "SecCore" module with SHA1 of "e07ea555c40b690fb88bb328709946eb5a1ff6a0" and (parent) GUID "1BA0062E-C779-4582-8566-336AE8F78F09".

[2 ARKE v1.7.2 -- 1 System BIOS with BiosGuard v1.7.2.zip](https://github.com/chipsec/chipsec/files/10405353/2.ARKE.v1.7.2.--.1.System.BIOS.with.BiosGuard.v1.7.2.zip)

**Comment by npmitche** [comment]
Fix merged. It will be included in the next release! Thanks!
