### ISSUE TITLE
[*] SKIPPED: chipsec.modules.common.smm on Atom

### ISSUE THREAD

**Issue by justinjohnson1** [chipsec/chipsec#173]
SMRAM enabled and locked is skipped on Atom chipsets (BayTrail). This test should not be skipped as SMRAM is supported and the configuration must be tested.

Related is the smm_dma module, again skipped on Atom chipsets but TSEG and SMRAM configurations should be checked.

**Comment by BartekLew** [comment]
No, there is no D_LCK, D_OPEN nor TSEG bits on Atom. SMRAM protection is non-standard and not documented in public documentation, so probably nothing can be done here.

**Comment by frinzell** [comment]
Old and appears answered. Closing. Reopen if needed.
