### ISSUE TITLE
Cannot Setup CHIPSEC

### ISSUE THREAD

**Issue by Authey** [chipsec/chipsec#1732]
Hi,

I tended to use iofuzz module on a linux kernel launched by QEMU to test, but I cannot setup the chipsec since a CalledProcessError is raised as below.
![1](https://user-images.githubusercontent.com/55642617/229365693-a5d9d52a-2eeb-4826-88d4-0fd420862c42.png)
I think this is because the linux kernel has no headers in the system, but when I attempted to install the dependency, it said the package cannot be located, as below.
![2](https://user-images.githubusercontent.com/55642617/229365821-1a179ff9-fa75-47a4-9196-64f49a8cd50f.png)
I wonder what caused that and do you have any idea to solve this?

Best regards,

Tianyi

**Comment by drAliRahnema** [comment]
i have this problem in ubuntu and kali and docker and python docker...

**Comment by npmitche** [comment]
Without knowing more about your setup, it seems likely that you're missing the headers and missing the headers would produce an error like this. You could try building your own kernel and exporting the header files accordingly: https://www.kernel.org/doc/html/latest/kbuild/headers_install.html 

Closing issue as it's technically a setup issue, not an issue with the CHIPSEC framework.
