### ISSUE TITLE
Logs folder existing in Linux causes FileExistsError.

### ISSUE THREAD

**Issue by aflaiggfairless-phoenix** [chipsec/chipsec#1742]
I've encountered an issue where if Chipsec is run from a current working directory that contains a folder named "Logs" with a capital L, it will error out in Linux. I believe this has something to do with a discrepancy with how Python is detecting if a directory exists or not as far as capitalization of directories goes, as in Windows this issue does not exist. Linux allows for two folders to be named the same in the same directory, as it cares about capitalization in folder names, whereas Windows does not make this distinction. Because of this, it seems that the function to see if a "logs" (lowercase) folder exists returns false, but when it tries to make the folder it errors out as the os.mkdir() function appears to care about capitalization.  

Since this appears to be part of a default logging system in Chipsec, it would be nice to have an argument to optionally disable default logging as there are other ways to manually specify a lot output file (`-l` for text logs and `-x` for XML logs). 
https://github.com/chipsec/chipsec/blob/2c42ead1fac233f6038a5483e1d241891be6b028/chipsec/logger.py#L49
![image](https://user-images.githubusercontent.com/89812761/231239959-eb7ead1c-ab45-4883-b7cc-4524e6597123.png)

**Comment by Sae86** [comment]
Hi @aflaiggfairless-phoenix,
I tried to reproduce the issue in a Linux system by creating a folder called Logs and then running Chipsec and I wasn't able to get the same behaviour.
Can you please give me more details on your Linux distro and system configuration? 
Thanks!
Sara
