### ISSUE TITLE
Missing support for LZMAF86 compression

### ISSUE THREAD

**Issue by platomav** [chipsec/chipsec#1747]
LZMAF86 is a compression format used in UEFI images, officially supported by EDK2 through GUID D42AE6BD-1352-4BFB-909A-CA72A6EAE889:

https://edk2-docs.gitbook.io/edk-ii-build-specification/5_meta-data_file_specifications/52_tools_def_txt [1]

It is basically a conversion layer on top of a regular LZMA compressed stream, which:

> can improve the compression ratio if the input file is IA32 or X64 PE image. Note: If X64 PE image is built based on GCC44, it may not get the better compression. [1]

Chipsec is not currently aware of the difference between LZMA and LZMAF86 compressed sections, which causes file corruption:

<img src="https://user-images.githubusercontent.com/11527726/232747477-da0003ed-5551-4e00-9996-3f81769521ae.jpg" width=70% height=70%>

UEFITool already has support for LZMAF86 detection and proper extraction (https://github.com/LongSoft/UEFITool/issues/197):

<img src="https://user-images.githubusercontent.com/11527726/232747722-153f2f17-85b3-491b-a18b-b703bc1863ce.png" width=70% height=70%>

To add support for LZMAF86, you can check for the equivalent GUID and then use EDK2's "LzmaCompress" utility, as such:

`LzmaCompress -q -d --f86 LZMAF86_Compressed.bin -o LZMAF86_Decompressed.bin`

The source code for "LzmaCompress" can be found here:

https://github.com/tianocore/edk2/tree/master/BaseTools/Source/C/LzmaCompress

The reference code for LZMAF86 can be found at the official LZMA SDK (subfolder "C" > Lzma86*, Bra86*):

https://www.7-zip.org/sdk.html

You can find sample UEFI images with LZMAF86 compressed sections from HPE:

- https://support.hpe.com/connect/s/softwaredetails?language=en_US&softwareId=MTX-b1ffc5df57db42a1b558565848
- https://support.hpe.com/connect/s/softwaredetails?language=en_US&softwareId=MTX_76853ab004dc4f4d85a3f229ce

I have attached one sample UEFI image w/ LZMAF86 as well as the compressed and uncompressed section using UEFITool and LzmaCompress, for reference (zip archive containing a rar archive):

[LZMAF86_rar.zip](https://github.com/chipsec/chipsec/files/11260770/LZMAF86_rar.zip)

**Comment by BrentHoltsclaw** [comment]
#1758 appears to work with the limited dataset, can you please verify?

**Comment by platomav** [comment]
@BrentHoltsclaw 

Thank you for the effort so far! I'm having trouble verifying whether Chipsec can now properly parse the LZMAF86 section. When it parses the attached sample file (i.e. "H08_1.84_10_23_2020.signed.flash.bin") via:

``` bash
python ./chipsec_main.py --skip_config --no_driver -n -m tools.uefi.scan_image -a generate H08_1.84_10_23_2020.signed.flash.json H08_1.84_10_23_2020.signed.flash.bin`

it does not appear to traverse the volume in question. It detects only 85 efi binaries, because that's how many are included outside the LZMAF86 section. If I give it as input the pre-extracted section (i.e. LZMAF86_Decompressed_UEFITool.bin), it detects an additional 473 binaries, which is correct. Meaning, at the sample file, Chipsec should be detecting a total of 558 efi binaries, not 85.

The referenced samples are included in the attached archive of the ticket.

As for the limited dataset, I can now verify that LZMAF86 is used by HPE in at least 800 different BIOS/UEFI update packages.

**Comment by BrentHoltsclaw** [comment]
Interesting I generated the following:
```
[*] Running module: chipsec.modules.tools.uefi.scan_image
[*] Module arguments (3):
['generate', 'H08_1.84_10_23_2020.signed.flash.json', 'H08_1.84_10_23_2020.signed.flash.bin']
[x][ =======================================================================
[x][ Module: Simple list generation/checking for (U)EFI firmware
[x][ =======================================================================
[*] Reading firmware from 'H08_1.84_10_23_2020.signed.flash.bin'...
[*] Generating a list of EFI executables from firmware image...
[*] Found 559 EFI executables in UEFI firmware image 'H08_1.84_10_23_2020.signed.flash.bin'
[*] Creating JSON file 'C:\tmp\tmp\testing\H08_1.84_10_23_2020.signed.flash.json'...
```
[H08_1.84_10_23_2020.signed.flash.zip](https://github.com/chipsec/chipsec/files/11334803/H08_1.84_10_23_2020.signed.flash.zip)

Did you run setup.py prior to your run?

**Comment by platomav** [comment]
Weird, I did run setup.py first, but I'm seeing the following:

![Screenshot from 2023-04-26 19-15-54](https://user-images.githubusercontent.com/11527726/234639723-90755c1d-2b36-49b6-89ae-98e4b2aae114.jpg)

![Screenshot from 2023-04-26 19-15-31](https://user-images.githubusercontent.com/11527726/234639748-25049ea4-b763-4e22-b635-d815ae5e5bd1.jpg)

**Comment by BrentHoltsclaw** [comment]
@platomav thanks for the pointer.
Missed in setup.py linux and windows both needed to be updated.  Was able to replicate and fix.  When you have time please check again.

**Comment by platomav** [comment]
@BrentHoltsclaw 

Excellent, It now works:

![Screenshot from 2023-04-26 20-42-30](https://user-images.githubusercontent.com/11527726/234661100-4bf8fa7d-6b2c-4070-ad8c-dc0f8f790393.png)

I can also verify that the EFI binaries are correctly detected/hashed now. For example:

- StaticSkuDataDxeNeonCityEPRP (45055A79-B385-4705-A3AC-11CE99A1CB47)
    - UEFITool --> 4FA3BEA454AC784671799747EE6F82C73F6A1A5594E39D21CD382A290C5C3D57
    - Chipsec --> 4FA3BEA454AC784671799747EE6F82C73F6A1A5594E39D21CD382A290C5C3D57

**Comment by platomav** [comment]
Did a quick check using the 2nd sample (i.e. U30_1.42_06_20_2018.signed) and Chipsec found 521 EFI binaries. I picked one random EFI binary within the LZMAF86 section and compared the result of UEFITool vs Chipsec:

- PciPlatformDxe (E2441B64-7EF4-41FE-B3A3-8CAA7F8D3017)
    - UEFITool --> 6256A2FB679A3D5C504C82582D9F9BAC8342D00932786CA7D9B6BD8141CC5AF6
    - Chipsec --> 6256A2FB679A3D5C504C82582D9F9BAC8342D00932786CA7D9B6BD8141CC5AF6

Looks good on the 2nd LZMAF86 sample image as well.

**Comment by platomav** [comment]
Support for LZMAF86 was added in release 1.11.0 (https://github.com/chipsec/chipsec/commit/00ba41226e76bd1492fb9ef7c194e207ab29ea20)
