### ISSUE TITLE
'No module named _lzma' error

### ISSUE THREAD

**Issue by zeeshansyed27** [chipsec/chipsec#1756]
I've been trying to run chipec_util uefi command in UEFI shell and I'm getting this error . Please help me resolve this issue I'm new to python and chipsec framework. I've attached the screenshot below.
![image](https://user-images.githubusercontent.com/43026021/233921241-cbfb4d8f-04e4-4488-98a2-1174b7711442.png)

**Comment by frinzell** [comment]
Related:
[edk2-libc : Py3 UEFI port _lzma module missing from implementation](https://bugzilla.tianocore.org/show_bug.cgi?id=4411)

**Comment by zeeshansyed27** [comment]
> Related: [edk2-libc : Py3 UEFI port _lzma module missing from implementation](https://bugzilla.tianocore.org/show_bug.cgi?id=4411)

@frinzell Thanks for the link. Also, my system crashes when I run 'python368 chipsec_util.py cpu info' command. Do you have any idea on this?

**Comment by GelsonFilho** [comment]
Hello, follow below, for comparison and documentation of the bug.

In my case, I tried running "python chipsec_util.py uefi var-list" and also got similar errors. The same command, if run in an OS environment (in my case I used Linux Mint 21.1), works normally. The problem happens only when the command is executed in UEFI environment. I'm using the latest version to date (1.10.4).

However "python368 chipsec_util.py cpu info" worked normally returning me the cpu information, I believe that the errors are not necessarily related.

**Comment by npmitche** [comment]
@zeeshansyed27  Can you open a new issue for the `cpu info` failure and add as much details as you can?

For this issue specifically, can you try this patch: https://github.com/chipsec/chipsec/pull/1767

**Comment by npmitche** [comment]
#1767 has been merged in and release is planned for later this week. Closing.

**Comment by zeeshansyed27** [comment]
@npmitche Thanks for your help. I don't get this error now but I'm getting another set of errors
