### ISSUE TITLE
Adding a new chipset

### ISSUE THREAD

**Issue by pgh15** [chipsec/chipsec#18]
One of my test laptops has a Pentium N3700 chip which is apparently from the Braswell family and provokes an error: Platform is not supported (Unsupported Platform: VID = 0x8086, DID = 0x2280)

Can you tell me how I would go about adding support for this chipset and/or chipset family?

**Comment by c7zero** [comment]
Added Braswell SoC detection. The error should be gone. Will be adding Braswell platform config file. For now, can copy BYT.xml to BSW.xml (most of the registers should be similar but may still be errors)
