### ISSUE TITLE
AttributeError: "NoneType" object has no attribute "get_info"

### ISSUE THREAD

**Issue by platomav** [chipsec/chipsec#1888]
Hello,

I encountered the following crash at the latest commit (existed before too but with a slightly different crash point):

![Screenshot from 2023-07-06 13-24-35](https://github.com/chipsec/chipsec/assets/11527726/6ccfe2df-9f6c-46f0-b0e0-80b5a32e3d01)

Would it be possible to add a test or similar which attempts to run Chipsec main with the various possible parameter combinations? For example: "-skip_config -i -n". This should help to avoid this kind of parameter combination crash in future releases.

**Comment by BrentHoltsclaw** [comment]
I am getting similar issues when using `chipsec_util.py -n --skip-config -nl uefi decode` command.  Doing some debugging it appears the cause of the issue is from #1838.

**Comment by platomav** [comment]
Based on https://github.com/chipsec/chipsec/pull/1796#issuecomment-1699928873, this should have been fixed at the latest release.
