### ISSUE TITLE
chipsec-master\chipsec\helper\win\win32helper.py Error: shutil is not defined

### ISSUE THREAD

**Issue by zeroDay0** [chipsec/chipsec#189]
got an error when running "chipsec_main.py -m tools.uefi.whitelist" on windows 7 and windows 10.
adding "import shutil" to chipsec-master\chipsec\helper\win\win32helper.py fixes the problem

Latest commit 4ba7c50

**Comment by ErikBjorge** [comment]
Good catch.  Will fix this today.

**Comment by ErikBjorge** [comment]
This should be fixed with the merge of PR 190 that was merged today.

**Comment by ErikBjorge** [comment]
Closing this issue with fix PR #190.  Please reopen if the problem was not resolved.
