### ISSUE TITLE
write_mmio_reg type mismatch

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#19]
Both [Linux](https://github.com/chipsec/chipsec/blob/master/source/tool/chipsec/helper/linux/helper.py#L316) and [Windows](https://github.com/chipsec/chipsec/blob/master/source/tool/chipsec/helper/win/win32helper.py#L573
) helpers expect an integer for the parameter 'value' of write_mmio_reg. This is what is being sent from the upper layers (HAL).

The [EFI helper](https://github.com/chipsec/chipsec/blob/master/source/tool/chipsec/helper/efi/efihelper.py#L138
) however, expect a string/buffer instead. Because of this, commands such as 'spi info' will fail.

**Comment by c7zero** [comment]
Fixed
