### ISSUE TITLE
chipsec_util uefi var-list error

### ISSUE THREAD

**Issue by codedreamercat** [chipsec/chipsec#1919]
I encountered the following issue at the latest commit.

python chipsec_util.py -d uefi var-list

################################################################
################################################################
[CHIPSEC] Version  : 1.12.0
[CHIPSEC] Arguments: -d uefi var-list

[*] [DEBUG] [helper] OS: Windows 10 10.0.19045
[*] [DEBUG] [helper] Found driver in D:\chipsec-main\chipsec-main\chipsec\helper\windows\windows_amd64\chipsec_hlpr.sys

WARNING: *******************************************************************
WARNING: Chipsec should only be used on test systems!
WARNING: It should not be installed/deployed on production end-user systems.
WARNING: See WARNING.txt
WARNING: *******************************************************************

[*] [DEBUG] [helper] service control manager opened (handle = <PySC_HANDLE:2894967278720>)
[*] [DEBUG] [helper] driver path: 'D:\chipsec-main\chipsec-main\chipsec\helper\windows\windows_amd64\chipsec_hlpr.sys'
[*] [DEBUG] [helper] Service 'chipsec' created (handle = 0x2A2097F0AA0)
[*] [DEBUG] [helper] service 'chipsec' started
[*] [HAL] [cpuid] in: EAX=0x00000001, ECX=0x00000000
[*] [DEBUG] [helper] Opened device '\\.\chipsec_hlpr' (handle: 00000268)
[*] [HAL] [cpuid] out: EAX=0x000906A3, EBX=0x08800800, ECX=0x7FFAFBFF, EDX=0xBFEBFBFF
[*] [DEBUG] [*] Loading device buses..
[!]            Results from this system may be incorrect.
WARNING: Not loading configurations. Platform will remain unknown.

[CHIPSEC] OS      : Windows 10 10.0.19045 AMD64
[CHIPSEC] Python  : 3.11.0 (64-bit)
[CHIPSEC] Helper  : WindowsHelper (\??\D:\chipsec-main\chipsec-main\chipsec\helper\windows\windows_amd64\chipsec_hlpr.sys)
[CHIPSEC] Platform: Unrecognized Platform
[CHIPSEC]    CPUID: FFFFF
[CHIPSEC]      VID: FFFF
[CHIPSEC]      DID: FFFF
[CHIPSEC]      RID: FF
[CHIPSEC] Executing command 'uefi' with args ['var-list']

[CHIPSEC] Enumerating all EFI variables via OS specific EFI Variable API..
[*] [DEBUG] [helper] -> NtEnumerateSystemEnvironmentValuesEx( infcls=2 )...
ERROR: NtEnumerateSystemEnvironmentValuesEx failed (GetLastError = 0x0)
ERROR: *** NTSTATUS: C0000001
ERROR: An error occured during the execution of the command!
ERROR: Please run with the debug option for further details
Traceback (most recent call last):
  File "D:\chipsec-main\chipsec-main\chipsec\command.py", line 36, in run
    self.func()
  File "D:\chipsec-main\chipsec-main\chipsec\utilcmd\uefi_cmd.py", line 214, in var_list
    efi_vars = self._uefi.list_EFI_variables()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chipsec-main\chipsec-main\chipsec\hal\uefi.py", line 475, in list_EFI_variables
    return self.helper.list_EFI_variables()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chipsec-main\chipsec-main\chipsec\helper\windows\windowshelper.py", line 785, in list_EFI_variables
    raise WinError()

**Comment by npmitche** [comment]
Closing because #2103 resolves the error. Will continue to look into a way of trying to enumerate efi variables in windows, but TBD.
