### ISSUE TITLE
Error message should be shown when compression utilities are missing

### ISSUE THREAD

**Issue by platomav** [chipsec/chipsec#1925]
Hello,

I noticed that Chipsec does not inform the user when a Tiano, LZMAF86 etc compression dependency is missing or has not been built.

So if it's forgotten by accident, it silently fails to process UEFI images with compression correctly.

I suggest an error message to be shown when a Tiano, LZMAF86 etc dependency is needed but is missing. Probably the same for LZMA, Brotli etc, but I think these are python imports, so they'll probably crash outright? If these are also ignored silently, the user should be aware.

**Comment by npmitche** [comment]
It was on purpose because those packages are not present in the UEFI shell and we didn't want people to be concerned about it. With that said, it might make sense to check if you're in an OS and if you are, report a warning/error. We'll look into it.
