### ISSUE TITLE
Add documentation or script for creating UEFI python build

### ISSUE THREAD

**Issue by crass** [chipsec/chipsec#1928]
Based on reading the [build documentation for UEFI Python](https://github.com/tianocore/edk2-libc/blob/master/AppPkg/Applications/Python/Python-3.6.8/Py368ReadMe.txt#L59) the prebuilt UEFI Python in this repo probably needed to have non-default modules configured to be built in. Please provide a script or documentation on how this prebuilt was generated.

Blibbet on the mailing list [posted 3 years ago](https://lore.kernel.org/oe-chipsec/856ed774-1177-2836-c57d-2abc80201df8@gmail.com/) pretty sums up my thoughts on this:
```
Wasn't there some special CHIPSEC-centric options needed to build Python
with? If so, that should be clarified better in build docs.

(Granted, it sucks having a security tool ship a pre-compiled Python
binary in their source tree, built in an unknown manner, with no
checksums, and no reproducable builds, and have the tool rely on this
for determining platform security. But that's another issue...)
```

**Comment by npmitche** [comment]
@Sae86 Can you document the process when you find the time to go through it?

**Comment by npmitche** [comment]
FYI, EDK-Libc just created github actions scripts to compile. You can see them here: https://github.com/tianocore/edk2-libc/actions

**Comment by jpshivakavi** [comment]
We have recently created github actions to build Python interpreter for UEFI using VS2019 and GCC tool chains.
There is also a pre-built release made available through the edk2-libc repo at [https://github.com/tianocore/edk2-libc/releases/tag/v3.6.8.1](https://github.com/tianocore/edk2-libc/releases/tag/v3.6.8.1).

There are also step by step build instructions available for GCC tool chain in this [document](https://github.com/tianocore/edk2-libc/blob/master/AppPkg/Applications/Python/Python-3.6.8/GCCCompilationBKMs.rst)
