### ISSUE TITLE
Service chipsec didn't start: The parameter is incorrect. (87)

### ISSUE THREAD

**Issue by p692584k** [chipsec/chipsec#1984]
Chipsec version: 1.12.4-p0072
OS: Win 11 Pro 23H2

When I type "python chipsec_main.py" or "sc start chipsec", it cause fail.
It shows "The parameter is incorrect.".
Do you know what method I can solve it?

**Comment by npmitche** [comment]
Can you email a copy of the full log to with the failure to chipsec@intel.com? We will be able to help you further.
