### ISSUE TITLE
Please make a source release on PyPi

### ISSUE THREAD

**Issue by scudette** [chipsec/chipsec#20]
Without a PyPi release it is difficult to have a direct dependency on this project. Although it is sometimes possible to have a pip[ dependency (e.g. in requirementst.txt)  on a github checkout, because the setup.py in this project is not at the top level this makes it a little more complicated.

It would be very helpful if you could also support PyPi (just a matter running setup.py register, setup.py upload).

Thanks kindly
Michael.

**Comment by destijl** [comment]
+1. We're going to have to release grr-chipsec on pypi to work around this.

@tweksteen FYI

**Comment by c7zero** [comment]
Tracked by PR #101

**Comment by c7zero** [comment]
pip install chipsec
