### ISSUE TITLE
macOS helper doesn't work in v1.10.5 and v1.10.6

### ISSUE THREAD

**Issue by kambala-decapitator** [chipsec/chipsec#2095]
In case one wants to use the driver/helper functionality in the latest v1.10.x on macOS, the fix can be found here: https://github.com/kambala-decapitator/chipsec/commit/57acd6d5feb20c71fd32b2633e4afa580d124e98

I know that macOS helper had been removed in v1.11.0, so feel free to close the issue. I've created it just that the fix could be found by others.

**Comment by npmitche** [comment]
Appreciate the link. Will close as you are correct, we are no longer supporting macOS in it's current form.
