### ISSUE TITLE
Chipsec fails to detect Computrace EFI binaries within UEFI image

### ISSUE THREAD

**Issue by platomav** [chipsec/chipsec#2197]
Hello,

As a continuation of https://github.com/chipsec/chipsec/issues/1790, I would like to focus on a specific sample which I know should contain at least 455 EFI binaries, while Chipsec is able to detect only 450:

`233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.cap`

Specifically, using the "scan_image" module, Chipsec detects 450 EFI binaries. There are at least 5 more which are not detected, related to "Computrace" and apparently stored within a **padding** section:

``` json
{
  "de4a46a4dbf04b40694687c5f3d826db265362973f6fc1740d54a46277d9d5f8": {
    "sha1": "59d7be2ead77825ad9f2a24ff8b93521c57fffc9",
    "guid": "8FEEECF1-BCFD-4A78-9231-4801566B3567",
    "name": "AbsoluteComputraceInstaller"
  },
  "399e5355ee4eed2331fefb3e49864da7d0d8c170ade413bea478a14469b540c2": {
    "sha1": "7e9d6cc0f5f28a020dbba47ecf07febbb0adb405",
    "guid": "4EFC51DA-23A6-4790-A292-4985C7F5CDEF",
    "name": "ComputraceEnablerDxe"
  },
  "e8ed47ff9d955bbb4fc349a7ecb5d5b8474cc20a3e32333f477c8bad433aa503": {
    "sha1": "cb06916d485b5dee6bcea0c70560539e8280edef",
    "guid": "4589CBF3-03F9-4998-9D6F-26343C69562A",
    "name": "ComputraceLoader"
  },
  "d77a47563aa18fcbdb92856cde52ea56531ee667b3dc91b09362ad67ca57e15c": {
    "sha1": "f190b200b1260cdbd3d9cbbdb4dcab9d929f4168",
    "guid": "18578E75-D073-4203-90D2-8788A871E44D",
    "name": "LenovoComputraceSmiServices"
  },
  "ef97bc7d42db1f91567f4dce4df19d783d7b7cb247c1c020067d428d50303f8e": {
    "sha1": "b3d4c94a06b1b5fefee629eaedcc94e4e9baa717",
    "guid": "AC60ED9F-523E-4F5B-94CA-3961346A00BA",
    "name": "LenovoVariableInitDxe"
  }
}
```

The area to look into should be:
- chipsec.chipsec.hal.spi_uefi
  - build_efi_tree (FV)
  - build_efi_file_tree (FILE)
  - build_efi_modules_tree (SECTION)
  - efi_data_search (new logic written as part of #1790)

Looking into the discussions I had previously with @BrentHoltsclaw, it appears that this sample was correctly detected as having 455 EFI binaries, but for some reason that is no longer occurring (or never did outside that MR, regression):
- https://github.com/chipsec/chipsec/issues/1790#issuecomment-1553325595

As a dirty test, I attempted to modify “chipsec.hal.spi_uefi” > “efi_data_search” to brute-force all 3 methods. This is something that @BrentHoltsclaw had mentioned as a possible solution, with the caveat that you would need to merge the 3 trees at different levels:
- https://github.com/chipsec/chipsec/issues/1790#issuecomment-1631297477

Effectively, I extended one list with the results from “build_efi_tree”, “build_efi_file_tree” and “build_efi_modules_tree” but nothing changed. Many duplicates (expected without merging of the trees at different levels) but no recovery of the 5 Computrace binaries.

I also played a bit with the “EFI_FV_FILETYPE_FFS_PAD” logic within “build_efi_file_tree”. I was wondering if there is an issue there with the data buffer or starting offset which is sent to the "efi_data_search" method. One weird test I did would yield 452 instead of 450, but these 2 were not related to the Computrace ones. Maybe even false positives? Not sure.

Could you please look into this issue with the provided sample so that we can come up with a solution to detect all (455 ?) EFI binaries within this sample (attached below)? I'm tagging the people who assisted in the previous #1790 ticket (@BrentHoltsclaw, @npmitche), just in case.

[233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.zip](https://github.com/user-attachments/files/15825904/233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.zip)

**Comment by BrentHoltsclaw** [comment]
Apologies for the delay.  After reviewing the image, it appears that the padding section is located here:

![image](https://github.com/chipsec/chipsec/assets/29214623/dd9b605e-63ad-4223-9040-3ea4adb1aa4b)

Debugging the code it appears that the problem is how the FV is handled specifically EfiSystemNvDataFvGuid (FFF12B8D-...)
![image](https://github.com/chipsec/chipsec/assets/29214623/3f18b7ab-1bae-4e71-a7ef-784a9dea7510)

```
def build_efi_tree(data: bytes, fwtype: str) -> List['EFI_MODULE']:
    fvolumes = []
    fv = NextFwVolume(data)
    while fv is not None:
        fv.calc_hashes()

        # Detect File System firmware volumes
        if fv.Guid in EFI_PLATFORM_FS_GUIDS or fv.Guid in EFI_FS_GUIDS:
            fwbin = build_efi_file_tree(fv.Image, fwtype)
            for i in fwbin:
                fv.children.append(i)

        # Detect NVRAM firmware volumes
        elif fv.Guid in EFI_NVRAM_GUIDS:  # == VARIABLE_STORE_FV_GUID:
            fv.isNVRAM = True
            try:
                fv.NVRAMType = identify_EFI_NVRAM(fv.Image) if fwtype is None else fwtype
            except Exception:
                logger().log_warning(f"Couldn't identify NVRAM in FV {{{fv.Guid}}}")

        fvolumes.append(fv)
        fv = NextFwVolume(data, fv.Offset, fv.Size)

    return fvolumes
```

When the FV is identified as NVRAM, it assigns the NVRAMType and moves on.

**Comment by BrentHoltsclaw** [comment]
Post running with #2212 
```
[*] Found 455 EFI executables in UEFI firmware image '233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.cap
[*] Found 3 duplicate executables
```

**Comment by platomav** [comment]
Awesome work Brent! 👏

Thank you for the investigation. Yes, it seems that Lenovo stuffed those Computrace binaries within a NVRAM volume. Goes to show how useful it is to be able to scan Volumes, Files and Sections in a more broad (i.e. UEFI-spec breaking) manner.

I tested #2212 with all "Non-UEFI" samples, as attached at https://github.com/chipsec/chipsec/issues/1790#issuecomment-1861865700 and can confirm that your fixes now allow detection of those 5 hidden Computrace modules:

![Screenshot 2024-07-03 003933](https://github.com/chipsec/chipsec/assets/11527726/f4e4e68d-23f3-4f00-8224-ef856dee8ad1)

![Screenshot 2024-07-03 004001](https://github.com/chipsec/chipsec/assets/11527726/0b3b63fa-65f1-4487-bf34-2ab81ab4ecaa)

Here are the final results from those 15 "Non-UEFI" samples (including the "233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.cap" one from this issue):

``` json
{
    "06b5447e03cc848bde4d9eea8f07fb48d8669aff_oem.cap.json": 14,
    "0ed790e4195dae17187f7700f1f89f9e7b0cba43_SHW4.Cap.json": 145,
    "0ed790e4195dae17187f7700f1f89f9e7b0cba43_oem.cap.json": 14,
    "233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.cap.json": 455,
    "233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.cap_Padding_Non-empty_Padding.pad.json": 5,
    "25e4b598db924041b98f9743bf403fb8997465cb_SHW4.Cap.json": 145,
    "25e4b598db924041b98f9743bf403fb8997465cb_oem.cap.json": 14,
    "2f23b45580eacbade578a3c5568dd9e2bec260fb_SHW4.Cap.json": 145,
    "2f23b45580eacbade578a3c5568dd9e2bec260fb_oem.cap.json": 14,
    "3c44f4d5c08d903ee25e387997abb9ac0fb5f10a_SHW4.Cap.json": 144,
    "3c44f4d5c08d903ee25e387997abb9ac0fb5f10a_oem.cap.json": 14,
    "6d271ea0a7c4b0846404790fd9a7791bb3781be2_R101acer.Cap.json": 165,
    "7a94369304134768d01f6c46248dad37ded0d492_SHW4.Cap.json": 144,
    "804f2283a39bef45a9addb9dcd3a8761ff02a313_SHW4.Cap.json": 145,
    "804f2283a39bef45a9addb9dcd3a8761ff02a313_oem.cap.json": 14
}
```

[Non_UEFI_Results_2024-07-02.zip](https://github.com/user-attachments/files/16074650/Non_UEFI_Results_2024-07-02.zip)
