### ISSUE TITLE
Chipsec logger error: "sh: 1: color: not found"

### ISSUE THREAD

**Issue by platomav** [chipsec/chipsec#2213]
Hello,

Upon attempting to run Chipsec modules, there is an error shown at the top:

``` sh
sh: 1: color: not found
```

It seems to stem from "chipsec/library/logger.py"

![Screenshot from 2024-07-03 19-22-26](https://github.com/chipsec/chipsec/assets/11527726/f2ef34d5-92ae-4a3e-b1a9-561c5f1fc9a4)

An os.system() call is performed for a "color" command, which does not seem to pre-exist by default.

Tested under Linux x64 (Ubuntu 22.04).

**Comment by MichaelCurrie** [comment]
please don't include code as an image.  You should include it like this:
[chipsec/library/logger.py#L103](https://github.com/chipsec/chipsec/blob/9f84abac9cab41c02b8d946e07419990395f7969/chipsec/library/logger.py#L103)

```python
class chipsecStreamFormatter(logging.Formatter):
    try:
        is_atty = sys.stdout.isatty()
    except AttributeError:
        is_atty = False
    # Respect https://no-color.org/ convention, and disable colorization
    # when the output is not a terminal (eg. redirection to a file)
    mPlatform = platform.system().lower()
    if is_atty and os.getenv('NO_COLOR') is None and (("windows" == mPlatform) or "linux" == mPlatform):
        os.system('color')
        colors = {
            'GREY':'\033[90m',
            'RED':'\033[91m',
            'GREEN':'\033[92m',
            'YELLOW':'\033[93m',
            'BLUE':'\033[94m',
            'PURPLE':'\033[95m',
            'CYAN':'\033[96m', 
            'WHITE':'\033[97m',
            'END':'\033[0m' }
    else:
        colors = {}
```
