### ISSUE TITLE
Python setuptools required for building EfiCompressor is incompatible with EWDK

### ISSUE THREAD

**Issue by ArtemBaranov** [chipsec/chipsec#2223]
Python's setuptools library from windows_requirements.txt requires Visual Studio installed and it can't be used with Enterprise WDK. It always searches for C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe and waits for its output. Since Visual Studio isn't installed (its files are located in the corresponding EWDK folder), building EfiCompressor always fails with error 

building 'EfiCompressor' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Upd: "python setup.py build" output was added

**Comment by ArtemBaranov** [comment]
See https://github.com/pypa/setuptools/blob/main/setuptools/msvc.py line 74, _msvc14_find_vc2017

**Comment by jun2zhou** [comment]
@ArtemBaranov which MSVC version you are using, would you please try to use the more recent versions test it?
you can refer the versions we are using in the actions ci environments.
https://github.com/chipsec/chipsec/actions/runs/10170877550/job/28130834523
![image](https://github.com/user-attachments/assets/d0532060-979f-4b3a-90b1-6068cf872d74)

https://github.com/chipsec/chipsec/actions/runs/10170877550/job/28130837941
![image](https://github.com/user-attachments/assets/72831e38-3797-4238-88ba-41a9a4570668)
