### ISSUE TITLE
windows: UMDF-based driver

### ISSUE THREAD

**Issue by skochinsky** [chipsec/chipsec#223]
Currently a big obstacle to chipsec's usage on Windows is having to enable test signing (which requires reboot and is just cumbersome). It seems UMDF can be used to sidestep this requirement, since it uses an already-signed kernel driver and only the INF file needs to be signed (AFAIK one could use a self-signed root cert). I'm not sure all necessary operations can be done with UMDF (e.g. SMI could be tricky), but even a subset of functionality could be useful.

**Comment by npmitche** [comment]
This is a conscious decision at this point to divert malicious use of chipsec.
