### ISSUE TITLE
PT support 

### ISSUE THREAD

**Issue by abazhaniuk** [chipsec/chipsec#225]
Will be great to have Processor Tracer support in CHIPSEC.
Can be integration with:
https://github.com/01org/processor-trace
with documentation: https://software.intel.com/en-us/blogs/2013/09/18/processor-tracing
for Windows: https://github.com/intelpt/WindowsIntelPT  
Documentation for PT in Intel SDM

**Comment by npmitche** [comment]
No plans to implement PT support inside CHIPSEC.
