### ISSUE TITLE
Register access should raise an exception if register type not defined.

### ISSUE THREAD

**Issue by ErikBjorge** [chipsec/chipsec#244]
If a configuration file defines a register type that cannot be handled by a register access method the method should raise an exception.  Currently the register access fails silently and returns a register value of zero.

__Create new exception class:__
RegisterTypeNotDefined

__Example Message:__
Access method for register of type <type> not defined.

**Comment by BrentHoltsclaw** [comment]
@ErikBjorge did you fix this with RegisterTypeNotFoundError or do we need a RegisterTypeNotDefined?

**Comment by ErikBjorge** [comment]
Yes, this should be fixed with the addition of `raise RegisterTypeNotFoundError` to the `read_register`/`write_register` functions.  Closing issue.
