### ISSUE TITLE
"Error: cannot copy tree 'drivers/osx': not a directory" on MacOS pip install

### ISSUE THREAD

**Issue by ThePuceMoose** [chipsec/chipsec#262]
When running "pip2 install chipsec" the install fails with message "Error: cannot copy tree 'drivers/osx': not a directory"

A previous issue #221  stated this was because setuptools is not installed, however running "pip2 list" shows setuptools (36.2.7)

Python 2.7.13 was installed through Homebrew, and xcode-select v.2347 is installed.
OS: macOS Sierra v10.12.5

**Comment by BrentHoltsclaw** [comment]
The pip installer does not contain the driver/osx directory which is why you are seeing this issue.  Please download the source from github to install.  We are currently working on a fix.

**Comment by ErikBjorge** [comment]
We have discontinued pip support for now until we can successfully support all OS versions.  Closing issue.
