### ISSUE TITLE
Support for Lenovo Phoenix updates

### ISSUE THREAD

**Issue by abazhaniuk** [chipsec/chipsec#270]
For samples: Thinkpad updates, e.g. this one for x220:
https://download.lenovo.com/pccbbs/mobiles/8duj28us.exe
Tools:
https://github.com/dscharrer/innoextract
http://freecode.com/projects/cabextract/

Some details: https://github.com/theopolis/uefi-firmware-parser/issues/53

**Comment by PerezFederico** [comment]
Can you give me a brief insight about how would you like this implemented?

**Comment by abazhaniuk** [comment]
Update from Fede: chipsec is parsing FL1 and FL2 formats.
