### ISSUE TITLE
decompression on windows 

### ISSUE THREAD

**Issue by abazhaniuk** [chipsec/chipsec#274]
Two issues with decompression on windows:
1. Working through legacy API and LzmaCompress.exe ,  TianoCompress.exe
2. Decompression not processing all files. for example: 
[P11-B2.zip](https://github.com/chipsec/chipsec/files/1247235/P11-B2.zip) 
to reproduce issue need to decode on windows and linux file: P11-B2.CAP

**Comment by ErikBjorge** [comment]
Need to check to see if this is resolved in latest version of CHIPSEC

**Comment by BrentHoltsclaw** [comment]
Appears to be working within the latest version of Chipsec.  Closing issue.  Please reopen if you are not getting the same results.
