### ISSUE TITLE
Chipsec fails to support Intel ApolloLake platform?

### ISSUE THREAD

**Issue by DeniseChien** [chipsec/chipsec#276]
To check "...\cfg\apl.xml", observed:

<bar desc="SPI Controller Register Range" enable_bit="1" size="0x200" mask="0xFFFFFE00" width="4" reg="0x54" fun="0" dev="0x1F" bus="0" name="SPIBAR"/>

i.e., the Chipsec read SPIBAR by **bus="0" dev="0x1F" fun="0" reg="0x54"**
But, Intel ApolloLake SPIBAR actually is **bus 0 / dev 13 / fun 2 / reg 0x10**

**Comment by ErikBjorge** [comment]
Thanks for the report.  We will get that fixed.
