### ISSUE TITLE
fall to Creating a Bootable Linux USB with Fedora 20

### ISSUE THREAD

**Issue by tc8831** [chipsec/chipsec#278]
I try to Creating a Bootable Linux USB with Fedora 20,  after finish the "6. Build the Linux driver for running system", there is not a file named "run.sh" to continue the 7th step. Is it created by the makefile used in the 6th step?

**Comment by abazhaniuk** [comment]
We need update: https://github.com/chipsec/chipsec/wiki/Creating-a-Bootable-Linux-USB-with-Fedora-20

**Comment by ErikBjorge** [comment]
Closing, wiki instructions have been updated at the link below.
https://github.com/chipsec/chipsec/wiki/Installing-CHIPSEC-in-Linux
