### ISSUE TITLE
Duplication of module selection

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#291]
Before being executed, modules are selected by:
- Loading module within the correct architecture directory ("bdw", "hsw", etc)
- Verifying the return value of the `is_supported` method.

These two selections seems to duplicate. If a module is restricted to a specific architecture, this should be written in the `is_supported` method. I'd like to only support the second option to simplify the loading of modules.

Thoughts?

**Comment by BrentHoltsclaw** [comment]
#747 should fix this issue.

**Comment by frinzell** [comment]
Closing as inactive.  Please reopen if needed.
