### ISSUE TITLE
UserWarning: The version specified ('1.3.3h') is an invalid version

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#295]
Full message: "UserWarning: The version specified ('1.3.3h') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details."

This is using the current version with `python setup.py install`. I quickly went through this PEP and indeed, we should probably be using something like `1.3.3dev1`.

**Comment by ErikBjorge** [comment]
I will make that change after the next release.  I am fine with using the dev1 tag.
