### ISSUE TITLE
BDW.XML update.

### ISSUE THREAD

**Issue by ccabobchen** [chipsec/chipsec#296]
About BDW.XML any update? Because run "sw_seq.py" on Broadwell-U platform always fail. Anybody knows update this file schedule.?

 Thank you for your help!

**Comment by ErikBjorge** [comment]
Please send the failing verbose log file to chipsec@intel.com so we can debug the issue.

**Comment by ccabobchen** [comment]
HI!
    Attached fail log file.

Thanks

BobChen

**Comment by ccabobchen** [comment]
Thanks for sending the log file.  It seems that you may have not used all the correct parameters so we just got a normal chipsec log file.  Please run the following command.

python chipsec_main.py -v -m tools.sw_seq -l sw_seq.log

This should run the tools.sw_seq module and export the results to sw_seq.log.  It will also enable verbose output so we can double check the register definitions being used.

Thanks,
-Erik

From: Bob.Chen [mailto:Bob.Chen@advantech.com.tw]
Sent: Tuesday, October 10, 2017 5:41 PM
To: chipsec <chipsec@intel.com>
Cc: Author <author@noreply.github.com>; chipsec/chipsec <reply@reply.github.com>; chipsec/chipsec <chipsec@noreply.github.com>
Subject: RE: [chipsec/chipsec] BDW.XML update. (#296)

HI!
    Attached fail log file.

Thanks

BobChen

**Comment by ccabobchen** [comment]
HI! Erik:
              Use command “python chipsec_main.py -v -m tools.sw_seq -l sw_seq.log” still fail and attached the log file.

Thanks
BobChen


From: Bjorge, Erik C [mailto:erik.c.bjorge@intel.com]
Sent: Wednesday, October 11, 2017 8:52 AM
To: Bob.Chen; chipsec
Cc: Author; chipsec/chipsec; chipsec/chipsec
Subject: RE: [chipsec/chipsec] BDW.XML update. (#296)

Thanks for sending the log file.  It seems that you may have not used all the correct parameters so we just got a normal chipsec log file.  Please run the following command.

python chipsec_main.py -v -m tools.sw_seq -l sw_seq.log

This should run the tools.sw_seq module and export the results to sw_seq.log.  It will also enable verbose output so we can double check the register definitions being used.

Thanks,
-Erik

From: Bob.Chen [mailto:Bob.Chen@advantech.com.tw]
Sent: Tuesday, October 10, 2017 5:41 PM
To: chipsec <chipsec@intel.com<mailto:chipsec@intel.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>; chipsec/chipsec <reply@reply.github.com>; chipsec/chipsec <chipsec@noreply.github.com<mailto:chipsec@noreply.github.com>>
Subject: RE: [chipsec/chipsec] BDW.XML update. (#296)

HI!
    Attached fail log file.

Thanks

BobChen

**Comment by ccabobchen** [comment]
Hi,

A 0x00 PREFIX is simply undefined.  Treat it as a warning.  As a warning, recommendation is to evaluate its proper operation from a security point-of-view for your system.

Hope this helps.

Thanks,

Aaron

From: Bob.Chen [mailto:Bob.Chen@advantech.com.tw]
Sent: Tuesday, October 10, 2017 8:06 PM
To: Bjorge, Erik C <erik.c.bjorge@intel.com>; chipsec <chipsec@intel.com>
Cc: Author <author@noreply.github.com>; chipsec/chipsec <reply@reply.github.com>; chipsec/chipsec <chipsec@noreply.github.com>
Subject: RE: [chipsec/chipsec] BDW.XML update. (#296)

HI! Erik:
              Use command “python chipsec_main.py -v -m tools.sw_seq -l sw_seq.log” still fail and attached the log file.

Thanks
BobChen


From: Bjorge, Erik C [mailto:erik.c.bjorge@intel.com]
Sent: Wednesday, October 11, 2017 8:52 AM
To: Bob.Chen; chipsec
Cc: Author; chipsec/chipsec; chipsec/chipsec
Subject: RE: [chipsec/chipsec] BDW.XML update. (#296)

Thanks for sending the log file.  It seems that you may have not used all the correct parameters so we just got a normal chipsec log file.  Please run the following command.

python chipsec_main.py -v -m tools.sw_seq -l sw_seq.log

This should run the tools.sw_seq module and export the results to sw_seq.log.  It will also enable verbose output so we can double check the register definitions being used.

Thanks,
-Erik

From: Bob.Chen [mailto:Bob.Chen@advantech.com.tw]
Sent: Tuesday, October 10, 2017 5:41 PM
To: chipsec <chipsec@intel.com<mailto:chipsec@intel.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>; chipsec/chipsec <reply@reply.github.com>; chipsec/chipsec <chipsec@noreply.github.com<mailto:chipsec@noreply.github.com>>
Subject: RE: [chipsec/chipsec] BDW.XML update. (#296)

HI!
    Attached fail log file.

Thanks

BobChen
