### ISSUE TITLE
Chipsec error on Legacy Win7 OS

### ISSUE THREAD

**Issue by BigBigNemo** [chipsec/chipsec#306]
May i knon if this tool support on legacy Win7 OS? We encounter some errors when run this tool on Legacy Win7 OS, no problem with UEFI W7 or W10 OS. Thanks.

ERROR: chipsec.modules.common.secureboot.variables
ERROR: chipsec.modules.common.uefi.access_platform
ERROR: chipsec.modules.common.uefi.access_uefispec

**Comment by skochinsky** [comment]
The cited modules require UEFI mode, so it's normal that they fail in legacy boot.

**Comment by ErikBjorge** [comment]
These modules should be skipped if run on a system booting in legacy mode.

**Comment by BrentHoltsclaw** [comment]
Addressed within PR #515.  Please reopen if there are farther concerns.
