### ISSUE TITLE
TypeError: decompress_data() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#310]
Running `chipsec_util decode image.bin` raises (tested on Chipsec 1.3.4):

      [...] linux/helper.py", line 1071, in decompress_file
      data = self.decompress_data( self.decompression_oder_type2, CompressedFileData )
    TypeError: decompress_data() takes exactly 4 arguments (3 given)

This works fine on version 1.3.3.

**Comment by PerezFederico** [comment]
I added this bug. I will fix it.

**Comment by ErikBjorge** [comment]
This missing parameter should be fixed in v1.3.5.
