### ISSUE TITLE
platforms support

### ISSUE THREAD

**Issue by Jayukie** [chipsec/chipsec#317]
Can it support the server platform？  And which server platform can it support ?  Thanks !

**Comment by ErikBjorge** [comment]
Currently CHIPSEC supports the following server platforms based on the following Xeon processors.

Xeon v1 (JKT)
Xeon v2 (IVT)
Xeon v3 (HSX)
Xeon v4 E3 (BDW)
Xeon v4 E5/E7 (BDX)
Xeon v5 E3 (SKL)
Xeon v6 E3 (KBL)

If you have more questions related to server platform support please send mail to chipsec@intel.com.

**Comment by Jayukie** [comment]
OK ,Thanks!
