### ISSUE TITLE
Where's PreRelease Repository Moving?

### ISSUE THREAD

**Issue by u1218** [chipsec/chipsec#318]
Hi Sir,

Before, we download PreRelease version from another repository, but it seems already removed currently.
Does anyone know where can let me get PreRelease version CHIPSEC?

Thanks.

**Comment by ErikBjorge** [comment]
Please send a mail to chipsec@intel.com for support with this issue.

**Comment by u1218** [comment]
OK, I think maybe my account didn't apply the access right, thank you for the answer.
