### ISSUE TITLE
uefi.uefivar_fuzz freezes after starting test case

### ISSUE THREAD

**Issue by YungRaj** [chipsec/chipsec#320]
While running in EFI shell, the **uefi.uefivar_fuzz module** freezes when it starts the first test case. Tried numerous versions of CHIPSEC, but that did not change anything.

>> python chipsec_main.py -m tools.uefi.uefivar_fuzz -a all,10

Ran the tool with this command to fuzz all variables with 10 test cases.

I ran CHIPSEC normally without any arguments to see if any modules were missing or errors occurred and it behaved fine. Because of this, I assume it is something specific to this module.

Tried on numerous MacBook Pro's in EFI, and the result did not change.

**Comment by npmitche** [comment]
Closing as we don't support macbooks any more and on current platforms and versions of chipsec this is not reproducible.
