### ISSUE TITLE
Question about PCI enumeration

### ISSUE THREAD

**Issue by marcosdiazr** [chipsec/chipsec#321]
Hi,
 In http://wiki.osdev.org/PCI#Enumerating_PCI_Buses. it says: 
Please note that if you don't check bit 7 of the header type and scan all functions, then some single-function devices will report details for "function 0" for every function.

But here:
https://github.com/chipsec/chipsec/blob/b0f400a27c296f40b54e6aff1723bd6ab3f654a6/chipsec/hal/pci.py#L292

I can see that all combinations of bus, dev, fun are checked. Just wanted to know if this is correct and why.
Thanks!

**Comment by ErikBjorge** [comment]
We check every possible location just in case a non-compliant device is present.  PCI spec states that all devices must implement function 0 but some devices may hide function 0.  This can lead to other functions being missed when enumerating per the PCI spec.  The drawback is that you may end up with other side-effects like single function device may be found/mirrored on multiple functions.

We may want to update this code to have multiple enumeration modes.  One that does the current complete scan and another that scans per the PCI specification.  Both methods can be useful.
