### ISSUE TITLE
Question about Skylake/Kabylake Servier variants

### ISSUE THREAD

**Issue by martingalvan** [chipsec/chipsec#326]
Hi everyone, I have a question regarding the Skylake Server and Kabylake Server architectures. It looks like these Server variants are seen by Chipsec as the same as regular SKL/KBL, and aren't included in the CHIPSET_FAMILY_XEON array:

https://github.com/chipsec/chipsec/blob/master/chipsec/chipset.py#L112

Some modules (e.g. smm_dma) have a check for the current arch not being a Server one. If it is, then the module isn't supported. Therefore, this might be a bug.

Another thing I noticed is that DID 0x1618 (Broadwell Server) is marked as BDW, but in the following line another Broadwell Server is marked as BDX:

https://github.com/chipsec/chipsec/blob/master/chipsec/chipset.py#L180

Could we confirm whether these are bugs?

**Comment by frinzell** [comment]
This depends on which Server you are referring to.  Certain server tests expect certain registers or features to be present, not all server types will have them.   The Broadwell server mentioned is an E3 that aligns with the client register definitions and will generally run as such.

**Comment by abazhaniuk** [comment]
Hi @frinzell is any E3 servers uses PC (big core) SoC/chipset?
