### ISSUE TITLE
Lenovo System x3550 M5 SPI dump

### ISSUE THREAD

**Issue by abazhaniuk** [chipsec/chipsec#337]
In Haswell server Lenovo System x3550 M5 SPI dump is dumping only NVRAM porting of the SPI memory.
Check dump:  [firmware_x3550.zip](https://github.com/chipsec/chipsec/files/1665531/firmware_x3550.zip)
Also having issues by reading it over flashrom as well: 
[lenovo-x3550-flashrom-failed.txt](https://github.com/chipsec/chipsec/files/1665543/lenovo-x3550-flashrom-failed.txt)

**Comment by skochinsky** [comment]
I suspect it's correct. I downloaded the update  from Lenovo: https://datacentersupport.lenovo.com/be/en/products/SERVERS/SYSTEM-X/SYSTEM-X3550-M5/5463/downloads/DS501263

And the `SPSFullME.bin` file look very close to your dump (a single VSS Store in the BIOS region). According to the XML it's placed in "DataStore":

```
        <file location="DataStore" size="0x800000" source="image" label_offset="0x563f2" label_size="0x4" platform="D" volume="892caae047df4c34a575d146cec4c69e" name="SPSFullME.bin" />
```

So probably you need to do some extra action to get access to the flash chip with the UEFI code:

```
        <file location="0x0FFFFFFF00600000" size="0x10420" source="image" volume="247CC44267A4b34e995CBC5FDF315BD9" name="CAPSULE_OEM_A.scap" />
        <file location="0x0FFFFFFF00800000" size="0xE6240" source="image" volume="247CC44267A4b34e995CBC5FDF315BD9" name="CAPSULE_A.scap" />
        <file location="0x0FFFFFFF00000000" size="0x398DF0" source="image" volume="00000000000000000000000000000000" name="CAPSULE_PLATFORM_A.scap" />
        <file location="0x0FFFFFFF00700000" size="0x498" source="image" volume="00000000000000000000000000000000" name="CAPSULE_DXE_A.scap" />

```

Maybe the `TrustedCodeUpdateDriver` in the capsules has the magic sauce (my guess is you need to toggle some GPIOs to connect the real chip)  but it's probably not chipsec's problem.

**Comment by abazhaniuk** [comment]
Thanks
