### ISSUE TITLE
Improve User Experience 

### ISSUE THREAD

**Issue by johnloucaides** [chipsec/chipsec#347]
We have had a number of people get confused by some of the results and logged messages from various modules. In order to improve the clarity of these messages, we listed the messaging in a single place on the wiki:
https://github.com/chipsec/chipsec/wiki/Interpreting-Results

Please use this issue to give feedback on how the messages could be changed to be more clear.

**Comment by akashdeep-aulakh** [comment]
Looks good, thanks!

**Comment by ErikBjorge** [comment]
Support has been added to the core but not all tests have been updated to correctly return NOT APPLICABLE.

**Comment by frinzell** [comment]
Closing as an ongoing task/improvement. Reopen if needed.
