### ISSUE TITLE
Kernel module does not load in Fedora running kernel v4.15.4-300 and above

### ISSUE THREAD

**Issue by ettermyra** [chipsec/chipsec#363]
When loading the CHIPSEC kernel module in Fedora kernel 4.15.4-300 and above the error "Unknown symbol in module" is produced. This applies to at least version 1.3.6RC1 and 1.3.5 of CHIPSEC.

When loading in Fedora kernel 4.14.16 it all works just fine! Unfortunately I do not know what has changed from one kernel version to another...Some patches related to Meltdown and Spectre?...just specualting since I have not read the release notes for the kernel.

**Comment by johnloucaides** [comment]
I'll try this when I get to my Fedora system, but can you copy/paste which symbol is "unknown"?

**Comment by ettermyra** [comment]
Oh! Sorry about that! =P Here goes (dmesg):
Unknown symbol valid_mmap_phys_addr_range (err 0)

**Comment by petersandor** [comment]
I'm experiencing the same issue on Arch 4.15.12-1

**Comment by ErikBjorge** [comment]
Thanks for the information @petersandor.  I am going to have @BrentHoltsclaw take a look at it.

**Comment by BrentHoltsclaw** [comment]
I created a pull request Fix for issue #363.  If you have time, could you check to see if it fixes your issue.

**Comment by ettermyra** [comment]
Tried the suggested fix and initial results indicate that it works fine. Will do some more testing...

**Comment by johnloucaides** [comment]
Are we ok to get this merged? Kinda annoying to have Fedora broken. ;-)

**Comment by ErikBjorge** [comment]
It was merged on the 17th.

**Comment by johnloucaides** [comment]
My bad. It wasn't this error that I noticed. It was that Fedora 27 now needs *another* dependency (elfutils-libelf-devel). Sorry.

I've updated the linux install instructions here: https://github.com/chipsec/chipsec/wiki/Installing-CHIPSEC-in-Linux

**Comment by ettermyra** [comment]
Sorry for the delay!
All seem to be working just fine! Closing this issue.
Thanks!
