### ISSUE TITLE
PREFast Defect Log and misc items

### ISSUE THREAD

**Issue by DropBearWare** [chipsec/chipsec#375]
Who's the appropriate contact to discuss bits around the win7 driver for Chipsec pertaining to:

- PREFast defect log ( line 127 gets flagged for sprintf usage )
127      for( i = 0; i < r; i++ ) line_ptr += sprintf( line_ptr, "%02X ", b[m*8 + i] );

- paths to move away from test-signing hack
- transpiling chipsec with say Nuitka vs current py2exe ( which also has issues )

**Comment by DropBearWare** [comment]
@johnloucaides -  It's Arun Koshy here from the mail-thread from Ron a week or so ago.

**Comment by DropBearWare** [comment]
@ErikBjorge -- happy to help @BrentHoltsclaw if he needs any more info though I suspect he'll probably be able to repro without much drama.

Thanks for clarifying the signing posture.. makes sense. Re transpiling, will email after a few more experiments.

Huge props to the team for building this ! Thanks to all involved for their hard work !

**Comment by ErikBjorge** [comment]
Closing unless additional support is needed.
