### ISSUE TITLE
No output when execute chpsec_util.main(['uefi', 'tables'])

### ISSUE THREAD

**Issue by rhapsodyjay** [chipsec/chipsec#377]
![image](https://user-images.githubusercontent.com/38524075/39292128-154b3566-48ea-11e8-96d9-f645075b7b4e.png)
I get above results but found nothing generated in my Chipsec folder.
Anything missed??

**Comment by ErikBjorge** [comment]
I will take a look at this today and provide any feedback on this issue.

**Comment by ErikBjorge** [comment]
I did a quick test of this and did not see an issue.  It looks like chipsec is not finding any of the UEFI tables and that explains the missing output.

Is this running in a VM?  Can you provide me with more system configuration data?

**Comment by rhapsodyjay** [comment]
No, it runs on Win10 x64 RS3 on Intel CFL-S chipsets with secure boot disabled.

**Comment by rhapsodyjay** [comment]
Hi Erik,

I dumped the info as below.
[tables.txt](https://github.com/chipsec/chipsec/files/2003069/tables.txt)

**Comment by ErikBjorge** [comment]
So that is very interesting.  It looks like the script found the IBI SYST signature but the field verification did not succeed.  It looks like we just don't have the 2.6 version information.  I will submit a patch for this today.

**Comment by ErikBjorge** [comment]
Please check to see if change #385 fixes the problem.

**Comment by ErikBjorge** [comment]
Thanks for testing.  We will get this committed soon.

**Comment by ErikBjorge** [comment]
Change merged.  Please reopen the issue if this issue shows up again.
