### ISSUE TITLE
Why can't I use command like this?

### ISSUE THREAD

**Issue by rhapsodyjay** [chipsec/chipsec#379]
Sorry to ask a dumb question..
As below picture, why can't i use the cihpsec commands as the examples format?
Did I missed something?
![image](https://user-images.githubusercontent.com/38524075/39294416-90abc8f0-48f0-11e8-822a-29efc3066a47.png)

**Comment by ErikBjorge** [comment]
This is because you are running inside the python interpreter command prompt.  Please use the following command line format directly from your OS command prompt.

python chipsec_util.py ucode id
