### ISSUE TITLE
Unsupported platform - CFL-S

### ISSUE THREAD

**Issue by rhapsodyjay** [chipsec/chipsec#380]
![image](https://user-images.githubusercontent.com/38524075/39416672-a8d69dd6-4c03-11e8-84b2-5f2f02e5e93b.png)

**Comment by ErikBjorge** [comment]
I will look into why the device ID is missing for this processor.  For now you can add -p CFL to your command options to force the CFL configuration.

`chipsec_main.main(['-p', 'CFL'])`

**Comment by rhapsodyjay** [comment]
Thanks Bjorge!

**Comment by ErikBjorge** [comment]
See PR #425 for a fix

**Comment by ErikBjorge** [comment]
PR #425 has been merged.  If detection of this platform is still an issue please reopen this issue.
