### ISSUE TITLE
chipsec installation on windows 10 is not happening

### ISSUE THREAD

**Issue by bikashdash** [chipsec/chipsec#382]
hello Security folks.
I am unable to run chipsec on Windows 10
my system is windows 10, latest version of DDK and Vs 2017
The main problem is I am unable to build the driver itself

Any solution to this ?

**Comment by BrentHoltsclaw** [comment]
We currently support WDK 7600.16385.1 (http://www.microsoft.com/en-us/download/details.aspx?id=11800) as referenced within the drivers/win7 directory.

**Comment by BrentHoltsclaw** [comment]
Updating build support for the driver is on the roadmap

**Comment by bikashdash** [comment]
Thanks @BrentHoltsclaw  for the update. Waiting for win 10 update :)
