### ISSUE TITLE
It cannot find the Prerelease – p0007 contains latest sw_seq.py test module

### ISSUE THREAD

**Issue by kenckien200** [chipsec/chipsec#387]
Hi:
CHIPSEC 1.3.5 – p0007 contains latest sw_seq.py test module based on Tech team guidance.

Prerelease – p0007
https://github.com/otcshare/chipsec-prerelease/releases/tag/p0007

But i can not find the files "tools.sw_seq" via the link.

Can you share the file to me.

Best Regards
Ken

**Comment by ErikBjorge** [comment]
All issues for chipsec-prerelease need to be filed in that project.  Please file the issue on that repository or send mail to chipsec@intel.com
