### ISSUE TITLE
install and run for the first time

### ISSUE THREAD

**Issue by liad344** [chipsec/chipsec#39]
when writing "sc create chipsec binpath=<PATH_TO_CHIPSEC_SYS> type= kernel DisplayName="Chipsec driver" as the manual says to do to run chipsec
on cmd , it says "access is denied" why? and what does it mean?

**Comment by bryongloden** [comment]
Greetings @liad344. How are you

**Comment by liad344** [comment]
I’m fine , and you@bryongloden  ?

**Comment by bryongloden** [comment]
Yeah <3. I'm alright

**Comment by liad344** [comment]
and about the problem? ..anyone?

**Comment by tweksteen** [comment]
Are you running the command as Administrator? The current code does automatically create and start the service if required. Have you tried to run chipsec_main.py directly?

**Comment by liad344** [comment]
Hi ,i do run this aa administrator , ill try to run chipsec_main.py
directly
בתאריך 30 ביונ' 2016 10:35,‏ "Thiébaud Weksteen" <notifications@github.com>
כתב:

**Comment by c7zero** [comment]
Note that you need to reboot Windows with driver signature enforcement turned off. Check the manual on how to do that

**Comment by c7zero** [comment]
Closing the issue
