### ISSUE TITLE
Core dump in chipsec_main

### ISSUE THREAD

**Issue by jurekb** [chipsec/chipsec#395]
[jb@myhost chipsec-git]$ git describe --long --tags
v1.3.6rc1-18-g96cf2f3
[jb@myhost chipsec-dkms-git]$ git describe --long --tag
v1.3.6rc1-18-g96cf2f3

The dmesg was obtained after running chipsec_main.

Problems:
1. ERROR: Unsupported Platform
2. core dump

**Comment by jurekb** [comment]
[debug.log](https://github.com/chipsec/chipsec/files/2020543/debug.log)
[dmesg.log](https://github.com/chipsec/chipsec/files/2020544/dmesg.log)

**Comment by ErikBjorge** [comment]
The reason for the unsupported platform message is that we tend not to support older platforms prior to the release of CHIPSEC.  It looks like this is a 965 platform and we do not have plans to add support at this time.  If someone submits a configuration file for this chipset we would be willing to add it to the tool.

Also note that running chipsec_main with the -i command line option will not provide reliable results as appropriate register definitions will not be loaded by the tool.  This can lead to invalid results and crashes.

We are looking at the error you encountered as it is not clear why the failure is happening.  Based on the test output it should be doing an MMIO read of the SPI controller.  When we look at the dmesg output it looks like an MSR read is occurring.  We will continue to look at this as you may have found an interesting bug in our driver code.

We do have one question.  Did you run dmesg immediately after running chipsec to collect the log data?  It looks like you did but we just wanted to check to make sure they are a matched set of logs.

**Comment by jurekb** [comment]
Actually I built chipsec from the latest source (the package version descriptions in Arch Linux AUR repo were fixed, old and incorrect). I corrected the original ticket.

As requested I also obtained very latest source and tried to build chipsec:
[jb@myhost chipsec-current]$ git describe --long --tag
v1.3.6rc1-19-ged76b7b

I could not get a clean compile run with python3:
$ python -V
Python 3.6.5
[jb@myhost chipsec-current]$ python setup.py build_ext -i
$
[chipset-bad-compile.log](https://github.com/chipsec/chipsec/files/2023963/chipset-bad-compile.log)

I succeeded with python2:
$ python2 -V
Python 2.7.15
[jb@myhost chipsec-current]$ python2 setup.py build_ext -i
[jb@myhost chipsec-current]$ sudo -u root python2 chipsec_main.py -i -d -v -l new-driver.log
[*] Ignoring unsupported platform warning and continue execution
Segmentation fault
$
[new-driver.log](https://github.com/chipsec/chipsec/files/2023970/new-driver.log)
[dmesg-new-driver.log](https://github.com/chipsec/chipsec/files/2023971/dmesg-new-driver.log)

**Comment by ErikBjorge** [comment]
We will look at the log information and see if we can debug the issue.

Currently we only support Python 2.7.x.  We are working on enabling Python 3.6 support in the future.

**Comment by BrentHoltsclaw** [comment]
@jurekb I have modified our driver to give additional output to help with debugging the issue.  Could you please replace the linux driver with the included file and recompile as above.  Afterwards could you run chipsec in two ways
`sudo python chipsec_main.py -i -d -v -l dbg-driver.log`
`sudo python chipsec_main.py -i -d -v -l dbg-bioswp.log -m common.bios_wp`

[chipsec_km.zip](https://github.com/chipsec/chipsec/files/2024330/chipsec_km.zip)

**Comment by jurekb** [comment]
Compilation:
[compile-with-chipsec_km.log](https://github.com/chipsec/chipsec/files/2025087/compile-with-chipsec_km.log)

[jb@myhost chipsec-current]$ sudo -u root python2 chipsec_main.py -i -d -v -l dbg-driver.log
[sudo] password for root: 
[*] Ignoring unsupported platform warning and continue execution
Segmentation fault
$
[dbg-driver.log](https://github.com/chipsec/chipsec/files/2025095/dbg-driver.log)
[dmesg-dbg-driver.log](https://github.com/chipsec/chipsec/files/2025097/dmesg-dbg-driver.log)

[jb@myhost chipsec-current]$ sudo -u root python2 chipsec_main.py -i -d -v -l dbg-bioswp.log -m common.bios_wp
[sudo] password for root: 
[*] Ignoring unsupported platform warning and continue execution
$
[dbg-bioswp.log](https://github.com/chipsec/chipsec/files/2025112/dbg-bioswp.log)
[dmesg-dbg-bioswp.log](https://github.com/chipsec/chipsec/files/2025117/dmesg-dbg-bioswp.log)

**Comment by jurekb** [comment]
@BrentHoltsclaw 
"f you would like to run a full run, either disable the test by deleting it from the directory ..."
Do you mean deleting tests/software/test_msr.py ? Or some other test ?

**Comment by ErikBjorge** [comment]
Because your platform is not supported by chipsec the results may not be accurate.  The use of the -i flag is really only for running specific tools in unsupported environments and not for general testing.  In many cases the tests may be reading incorrect registers or checking for features that were not yet available in that processor/chipset generation.

An in depth investigation of the results would be required to determine what results could be trusted and what results can't.

**Comment by ErikBjorge** [comment]
Closing issue unless further support is required.
