### ISSUE TITLE
Chipsec doesn't decode Acer KBL firmware image

### ISSUE THREAD

**Issue by abazhaniuk** [chipsec/chipsec#399]
[firmware_acer.zip](https://github.com/chipsec/chipsec/files/2078160/firmware_acer.zip)
It is firmware from Acer Predator GX-792

chipsec extracted 66 DXE/PEI files. 
uefi-firmware-parser ~300 
I think some FV was not decoded, maybe related to https://github.com/chipsec/chipsec/issues/367

**Comment by ErikBjorge** [comment]
Seems like it may be the same as #398 as well.

**Comment by skochinsky** [comment]
My guess would be the LZMA-compressed nested volume.

**Comment by BrentHoltsclaw** [comment]
Can you try pulling https://github.com/brentHoltsclaw/chipsec/tree/uefi_decompress and see if it fixes your issue?

**Comment by BrentHoltsclaw** [comment]
@abazhaniuk @johnloucaides Did you get a chance to verify whether the decode functionality fixes the issue and that it does not cause any other issues?

**Comment by ErikBjorge** [comment]
This should be fixed in the latest release using the updated decompression code.  Please reopen if the failure continues.
