### ISSUE TITLE
Reading PhysMem has problems in HEAD but not in release 1.3.6 rc1

### ISSUE THREAD

**Issue by HackingThings** [chipsec/chipsec#431]
Tried to read over 1024 bytes of memory using HEAD and got the good ol' "ioctl string too long" error, did the same thing on the same platform with Release 1.3.6 RC1 and had no issues.

**Comment by ErikBjorge** [comment]
This is the same issue as #410.  I have a partial solution but continue to find additional bugs due to how memory is mapped.

**Comment by HackingThings** [comment]
Duplicate issue with #410
