### ISSUE TITLE
module_template is executed when running chipsec_main

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#46]
Although this module is automatically skipped because the `is_supported` method returns `False`, the output of the overall tests is confusing as it will appear in the 'Skipped' section.

A simple filtering when loading the modules to ignore the name 'module_template' would fix this.

**Comment by c7zero** [comment]
There's probably no need for module_template.py anymore. There are plenty existing modules to use as templates. I'm leaning toward removing it.

**Comment by c7zero** [comment]
Closed with PR #64
