### ISSUE TITLE
can't use chipsec_util without driver

### ISSUE THREAD

**Issue by skochinsky** [chipsec/chipsec#467]
driver seems to be required even for commands which should not need it. This is on Windows 8.1, both  on fresh Git copy and pip package:

```
chipsec_util.py help
ERROR: Could not load helper for 'Windows' environment (unsupported environment?)
Traceback (most recent call last):
  File "C:\Work\git\chipsec\chipsec_util.py", line 265, in <module>
    sys.exit( main() )
  File "C:\Work\git\chipsec\chipsec_util.py", line 260, in main
    chipsecUtil = ChipsecUtil(argv if argv else sys.argv[1:])
  File "C:\Work\git\chipsec\chipsec_util.py", line 83, in __init__
    self._cs = cs()
  File "C:\Work\git\chipsec\chipsec\chipset.py", line 925, in cs
    _chipset = Chipset(helper())
  File "C:\Work\git\chipsec\chipsec\helper\oshelper.py", line 478, in helper
    _helper  = OsHelper()
  File "C:\Work\git\chipsec\chipsec\helper\oshelper.py", line 109, in __init__
    raise OsHelperError( "Could not load helper for '%s' environment (unsupported environment?)" % os_system, errno.ENODEV )
chipsec.helper.oshelper.OsHelperError: Could not load helper for 'Windows' environment (unsupported environment?
)```

Adding `-i` or `-n` has no effect. Only `-h` succeeds.

**Comment by skochinsky** [comment]
by running `win32helper.py` separately and adding `get_helper()` call I got some clues:

```Traceback (most recent call last):
  File "C:\Work\git\chipsec\chipsec\helper\win\win32helper.py", line 949, in <module>
    print get_helper()
  File "C:\Work\git\chipsec\chipsec\helper\win\win32helper.py", line 946, in get_helper
    return Win32Helper( )
  File "C:\Work\git\chipsec\chipsec\helper\win\win32helper.py", line 275, in __init__
    raise DriverNotFound
NameError: global name 'DriverNotFound' is not defined
```

still, missing driver should not prevent utility from working, especially for non-hardware functionality.

**Comment by ErikBjorge** [comment]
I found this bug as well and need to start scrubbing the commands to handle this correctly.  Do you have any specific commands that are causing you more of a problem than others?  I could start working on those first.

**Comment by skochinsky** [comment]
well, I wanted at least to use `dump` to unpack an SPI image. Also IIRC the variable reading should work without a driver via `GetFirmwareEnvironmentVariableEx` and friends and should not need the driver.

**Comment by HackingThings** [comment]
Adding the DAL aspect to this bug. 
Intel Python example below:

Python 2.7.16 |Intel Corporation| (default, May 16 2019, 11:45:21) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
Deprecation WARNING: Intel(R) support for Python 2.7 ends after 2019
>>> import ipccli
>>> ipccli.settings.IPC_PATH = "C:\IntelSWTools\tools\OpenIPC_1.1917.3733.100\Bin"
>>> ipc= ipccli.baseaccess()
Connecting to IPC API....
IPC-CLI: 1.1917.1173.100, OpenIPC:Main (rev 634415) : 1.1917.3733.100
Initializing IPC API....

Info - OpenIPC using automatic configuration
Info - DCI: A DCI device has been detected, attempting to establish connection
Info - DCI: Target connection has been fully established
Info - Added new debug port 0 using probe plug-in 'OpenDCI'
Info - Detected BXTP_CLTAPC D0 on JTAG chain 0 at position 0
Warning - No TAP devices detected on JTAG chain 1
>>> import chipsec_util
>>> chipsec_util.main(['spi','info'])
ERROR: Could not load helper for 'Windows' environment (unsupported environment?)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "chipsec_util.py", line 260, in main
    chipsecUtil = ChipsecUtil(argv if argv else sys.argv[1:])
  File "chipsec_util.py", line 83, in __init__
    self._cs = cs()
  File "chipsec\chipset.py", line 936, in cs
    _chipset = Chipset(helper())
  File "chipsec\helper\oshelper.py", line 478, in helper
    _helper  = OsHelper()
  File "chipsec\helper\oshelper.py", line 109, in __init__
    raise OsHelperError( "Could not load helper for '%s' environment (unsupported environment?)" % os_system, errno.ENODEV )
chipsec.helper.oshelper.OsHelperError: Could not load helper for 'Windows' environment (unsupported environment?)

**Comment by BrentHoltsclaw** [comment]
@HackingThings it looks like the helper is not being loaded. Please see #691 and let me know if it fixes the issue

**Comment by HackingThings** [comment]
Sadly, the issue persists... :(

**Comment by BrentHoltsclaw** [comment]
Are you getting the same error?

**Comment by HackingThings** [comment]
Bump.
UEFI decode will not work without a driver

```
..\chipsec-1.10.1> python chipsec_util.py -n uefi decode image.bin

################################################################
##                                                            ##
##  CHIPSEC: Platform Hardware Security Assessment Framework  ##
##                                                            ##
################################################################
[CHIPSEC] Version  : 1.10.1
[CHIPSEC] Arguments: -n uefi decode image.bin

[CHIPSEC] API mode: using OS native API (not using CHIPSEC kernel module)
ERROR: 65535
```

**Comment by npmitche** [comment]
We'll get there soon ™️

Stay tuned.

**Comment by npmitche** [comment]
This https://github.com/chipsec/chipsec/pull/1832 does the initial step in running util without a driver. I'm going to do some more work before merging it in to re-work the utils to better handle it. Once I do that we'll merge this in. Timeline is in the next few months, dependent on work schedule.
