### ISSUE TITLE
new spi jedec command broken on platforms before Skylake

### ISSUE THREAD

**Issue by wrffrz** [chipsec/chipsec#489]
There was recently some new functionality added to send a SPI cycle to read the JEDEC chip id with the function  in hal/spi.py:get_SPI_JEDEC_ID().

This functionality depends on the FCYCLE field in the Hardware Sequencing Control register supporting the Read JEDEC ID command with value 6.

However, before Skylake, this field was only two bits wide and did not support this command.

Here's the description of this field from the Lynx Point chipset datasheet:

2:1 | FLASH Cycle (FCYCLE)—R/W.
This field defines the Flash SPI cycle type generated to the FLASHwhen the FGO bit is set as defined below:
00 = Read (1 up to 64 bytes by setting FdBC)
01 = Reserved
10 = Write (1 up to 64 bytes by setting FdBC)
11 = Block Erase

If we're attempting to set FCYCLE to 6 and sending a flash cycle on platforms before Skylake, this could be cutting off the upper bit and sending a write cycle instead.

**Comment by frinzell** [comment]
The is_supported() _should_ catch this when looking for FDV and fail in the Lynx Point case.  Are you seeing different?

**Comment by wrffrz** [comment]
Here's the output I get when I try to run this on a Sandybridge/CougarPoint platform:

[*] Platform: Desktop 2nd Generation Core Processor (Sandy Bridge CPU / Cougar Point PCH)
          VID: 8086
          DID: 0100
[*] PCH     : Default PCH
          VID: 8086
          DID: 1C52

chipsec_util -v spi jedec appears to be sending the spi cycle:

[CHIPSEC] Executing command 'spi' with args ['jedec']

[pci] reading B/D/F: 0/31/0, offset: 0xF0, value: 0xFED1C001
[mmio] SPIBAR: 0x00000000FED1F800 (size = 0x200)
[spi] SPI MMIO base: 0x00000000FED1F800 (assuming below 4GB)
[spi] Reading SPI flash controller registers definitions:
      HSFC   offset = 0x0006
      HSFS   offset = 0x0004
      FADDR  offset = 0x0008
      FDATA0 offset = 0x0010
[pci] reading B/D/F: 0/31/0, offset: 0xF0, value: 0xFED1C001
[mmio] SPIBAR: 0x00000000FED1F800 (size = 0x200)
[mmio] 0xFED1F800 + 0x00000004 = 0x0000E008
[spi] > send SPI cycle 0xD to address 0x00000000..
[mmio] write 0xFED1F800 + 0x00000008 = 0x00000000
[mmio] 0xFED1F800 + 0x00000008 = 0x00000000
[spi] FADDR: 0x00000000
[spi] SPI cycle GO (DBC <- 0x04, HSFC <- 0xD)
[mmio] write 0xFED1F800 + 0x00000007 = 0x00000004
[mmio] write 0xFED1F800 + 0x00000006 = 0x0000000D
[mmio] 0xFED1F800 + 0x00000006 = 0x0000000C
[spi] HSFC: 0x000C
[spi] wait for SPI cycle ready/done..
[mmio] 0xFED1F800 + 0x00000004 = 0x0000000B
[spi] clear FDONE/FCERR/AEL bits..
[mmio] write 0xFED1F800 + 0x00000004 = 0x00000007
[mmio] 0xFED1F800 + 0x00000004 = 0x00000008
[spi] HSFS: 0x08
[spi] < SPI cycle done
[mmio] 0xFED1F800 + 0x00000010 = 0xFFFFFFFF
    JEDEC ID: 0xFFFFFF

[CHIPSEC] (spi jedec) time elapsed 0.001

I've also tried this on Jaketown, Haswell, and Broadwell-E and on each of these it appears to be sending the SPI cycle.

**Comment by wrffrz** [comment]
Also, FDV just says whether the flash descriptor is valid which can certainly be the case for Cougar Point, Panther Point, Lynx Point, and Wildcat Point even those don't support the JEDEC command in the HSFC.FCYCLE field.

**Comment by frinzell** [comment]
This should prevent writing FCYCLE when it shouldn't.  Please give it a try.

**Comment by frinzell** [comment]
@wrffrz Can this be closed as fixed?

**Comment by wrffrz** [comment]
Yes, this should be sufficient to prevent trying to write a too-large value into FCYCLE with older architectures.  With the Skylake arch changes, the FCYCLE field was increased in size when it was moved from the previous HSFC register into the combined HSFS register.
