### ISSUE TITLE
CHIPSEC must not assume PCI bus numbers of devices on server platforms

### ISSUE THREAD

**Issue by ErikBjorge** [chipsec/chipsec#505]
Server platforms may place PCI devices on different buses than what is assumed by CHIPSEC.  Examples include the bus number of the PCH or PCI devices on processors other than socket 0.

CHIPSEC should update the PCI HAL to determine the correct bus for these devices.  @elicn suggests reading MSR 0x300 to resolve this issue.

Thanks @elicn for pointing this issue out.

**Comment by frinzell** [comment]
Some routines are written that I need to get reviewed and tested.  Testing will take the longest since there are proposed changes to some of the core routines.

**Comment by frinzell** [comment]
PR #566 submitted and open for review.

**Comment by BrentHoltsclaw** [comment]
Chipsec should now support this feature.  Closing issue.   Please reopen if problem exists.
