### ISSUE TITLE
Chipsec doesn't correctly parse Lenovo Yoga 2 Pro UEFI firmware image

### ISSUE THREAD

**Issue by wrffrz** [chipsec/chipsec#543]
I've got a Lenovo Yoga 2 Pro which is a Hawell laptop and chipsec has a couple problems decoding the firmware image from this system.

First, when we run chipsec_util.py to decode the image, it crashes trying to parse a variable name using utf16:

> $ python /nas/jesse/tools/chipsec/chipsec_util.py decode spidump.bin
>
> ################################################################
> ##                                                            ##
> ##  CHIPSEC: Platform Hardware Security Assessment Framework  ##
> ##                                                            ##
> ################################################################
> [CHIPSEC] Version 1.3.7
> [CHIPSEC] API mode: using OS native API (not using CHIPSEC kernel module)
> [CHIPSEC] Executing command 'decode' with args ['spidump.bin']
>
> [CHIPSEC] Decoding SPI ROM image from a file 'spidump.bin'
> [CHIPSEC] Found SPI Flash descriptor at offset 0x0 in the binary 'spidump.bin'
> Traceback (most recent call last):
>   File "/nas/jesse/tools/chipsec/chipsec_util.py", line 232, in <module>
>     sys.exit( main() )
>   File "/nas/jesse/tools/chipsec/chipsec_util.py", line 228, in main
>     return chipsecUtil.main()
>   File "/nas/jesse/tools/chipsec/chipsec_util.py", line 195, in main
>     comm.run()
>   File "/nas/jesse/tools/chipsec/chipsec/utilcmd/decode_cmd.py", line 122, in run
>     spi_uefi.decode_uefi_region(_uefi, pth, fname, fwtype)
>   File "/nas/jesse/tools/chipsec/chipsec/hal/spi_uefi.py", line 558, in decode_uefi_region
>     _uefi.parse_EFI_variables( nvram_fname, region_data, False, fwtype )
>   File "/nas/jesse/tools/chipsec/chipsec/hal/uefi.py", line 358, in parse_EFI_variables
>     decode_EFI_variables( efi_vars, nvram_pth )
>   File "/nas/jesse/tools/chipsec/chipsec/hal/uefi.py", line 234, in decode_EFI_variables
>     parse_efivar_file(var_fname, data, AUTH_SIG_VAR)
>   File "/nas/jesse/tools/chipsec/chipsec/hal/uefi_common.py", line 1021, in parse_efivar_file
>     parse_auth_var(var, var_path)
>   File "/nas/jesse/tools/chipsec/chipsec/hal/uefi_common.py", line 971, in parse_auth_var
>     var_name = codecs.decode(db[tof:tof+name_size], 'utf-16')
>   File "/usr/lib/python2.7/encodings/utf_16.py", line 16, in decode
>     return codecs.utf_16_decode(input, errors, True)
> UnicodeDecodeError: 'utf16' codec can't decode bytes in position 28-29: illegal encoding
> $

Although we get this error from chipsec, we're still able to extract 43 .TE files and 14 .PE32 files from the image:

> $ find spidump.bin.dir -iname '*.te' -o -iname '*.pe32' -o -iname '*.efi' | wc -l
> 58
> $

However, it actually has a lot more than that.

One of the sections that chipsec identifies as a RAW section is 12MB and contains a UEFI Firmware Volume:

> $ find . -name '*_S_RAW' -ls
>  73382072      1 -rw-rw-r--   1 jesse    jesse          76 Mar 22 22:31 ./1_400000-7FFFFF_BIOS.bin.dir/FV/02_7A9354D9-0468-444A-81CE-0BF617D890DF.dir/60_1BA0062E-C779-4582-8566-336AE8F78F09.FV_SECURITY_CORE.dir/02_S_RAW
>  73382067      1 -rw-rw-r--   1 jesse    jesse           0 Mar 22 22:31 ./1_400000-7FFFFF_BIOS.bin.dir/FV/02_7A9354D9-0468-444A-81CE-0BF617D890DF.dir/60_1BA0062E-C779-4582-8566-336AE8F78F09.FV_SECURITY_CORE.dir/00_S_RAW
>  73381309   3549 -rw-rw-r--   1 jesse    jesse    12582924 Mar 22 22:31 ./1_400000-7FFFFF_BIOS.bin.dir/FV/00_7A9354D9-0468-444A-81CE-0BF617D890DF.dir/00_4A538818-5AE0-4EB2-B2EB-488B23657022.FV_DXE_CORE.dir/00_S_COMPRESSION.dir/00_S_RAW
> $ xxd ./1_400000-7FFFFF_BIOS.bin.dir/FV/00_7A9354D9-0468-444A-81CE-0BF617D890DF.dir/00_4A538818-5AE0-4EB2-B2EB-488B23657022.FV_DXE_CORE.dir/00_S_COMPRESSION.dir/00_S_RAW | head -10
> 00000000: 3132 3334 3536 3738 3941 0d0a 0000 0000  123456789A......
> 00000010: 0000 0000 0000 0000 0000 0000 d954 937a  .............T.z
> 00000020: 6804 4a44 81ce 0bf6 17d8 90df 0000 c000  h.JD............
> 00000030: 0000 0000 5f46 5648 ff8e ffff 4800 b14b  ...._FVH....H..K
> 00000040: 0000 0001 0300 0000 0000 4000 0000 0000  ..........@.....
> 00000050: 0000 0000 504f b7ab 2dfd 7240 a321 cafc  ....PO..-.r@.!..
> 00000060: 7297 7efa a284 0640 220e 00f8 0600 001b  r.~....@".......
> 00000070: 0708 0000 e40d 0010 4d5a 0000 0000 0000  ........MZ......
> 00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
> 00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
> $

If we then use chipsec_util.py uefi decode to extract that 00_S_RAW section, we get 234 more EFI executables:

> $ cp ./1_400000-7FFFFF_BIOS.bin.dir/FV/00_7A9354D9-0468-444A-81CE-0BF617D890DF.dir/00_4A538818-5AE0-4EB2-B2EB-488B23657022.FV_DXE_CORE.dir/00_S_COMPRESSION.dir/00_S_RAW .
> $ python /nas/jesse/tools/chipsec/chipsec_util.py -n uefi decode 00_S_RAW
>   ...
> $ find 00_S_RAW.dir -iname '*.efi' | wc -l 
>     234
> $

**Comment by wrffrz** [comment]
[spidump.zip](https://github.com/chipsec/chipsec/files/2998730/spidump.zip)

**Comment by ErikBjorge** [comment]
Thanks for the report and providing the failing flash image.  We will take looks at this and see what it will take to fix.  Also appreciate the debug information in the issue report.

**Comment by BrentHoltsclaw** [comment]
Looked into why the image is not being extracted properly and found that the section type is unknown/reserved, which means CHIPSEC is not doing anything to try to decode it.  Can add logic to try and decode unknown/reserved sections, but should that be default behavior?

For the decode issue will put in a try, except and print out a warning which will be within the uefi.lst file.

**Comment by hughsie** [comment]
If it helps, master also fails for firmware.bin inside b76ea728bd1e305c285fbda742159c92a8d44924-Lenovo-ThinkPad-T480s-SystemFirmware-1.30.cab -- this time with `SPI Flash descriptor region is not valid` -- if you want a *ton* of uefi firmware images for testing please just ask and I can send you links.

**Comment by BrentHoltsclaw** [comment]
A collection of uefi firmware images would be helpful, especially if you have some known issues.

**Comment by hughsie** [comment]
Okay, here's a long list:

    145f75656a32ac86daecab9c74730f10c74895c7-Lenovo-ThinkPad-T580P52s-SystemFirmware-0.1.14.cab
    4a08092190ffa09fed1a7375af9402273b52d804-Lenovo-ThinkPad-A475-SystemFirmware-1.14.cab
    d537d51a050c61f7fbb8d38ac266526dbd133166-Lenovo-ThinkPad-A275-SystemFirmware-1.15.cab
    70fb868eee2d1a6480128c908c880d758a6ff3f1-Lenovo-ThinkPad-P1X1Extreme-SystemFirmware-0.1.15.cab
    ab85ae6b34b6ef1fd9d556e56ec6c48fa8c69909-Lenovo-ThinkPad-T480-SystemFirmware-1.16.cab
    28f665a9bae6024e286c1dc9d016e3a4ad0dbdd3-Lenovo-ThinkPad-P52P72-SystemFirmware-1.17.cab
    36e2b22d7296403e8d0ca51b74058af18048d8af-Lenovo-ThinkPad-X280-SystemFirmware-1.19.cab
    f56458ba52f3c0bca4ab883e9b8a112b970ef5f7-Lenovo-ThinkPad-P71-SystemFirmware-1.24.cab
    dfc6d62e3e26d4d54a656a36c00768985179ce7d-Lenovo-ThinkPad-T470p-SystemFirmware-1.24.cab
    064c5aa3256d43f5ed7c931447c20418203fab2f-Lenovo-ThinkPad-X1Yoga3nd-SystemFirmware-0.1.24.cab
    2745a26ac883b9c171522bb16e1c628632932b20-Lenovo-ThinkPad-T480s-SystemFirmware-1.25.cab
    769be80680bf15ee51a3782e664041900c45de76-Lenovo-ThinkPad-X1Carbon6th-SystemFirmware-1.27.cab
    c910d903f6d7ac628ce5bdd5285824dee60ef397-Lenovo-ThinkPad-T470s-SystemFirmware-1.28.cab
    eef567d2363ca313d077c679ac379e52c2334fd4-Lenovo-ThinkPad-X1Yoga2nd-SystemFirmware-0.1.29.cab
    e867f209ab9af8a055a53d578c82228368a36144-Lenovo-ThinkPad-T560P50s-SystemFirmware-1.29.cab
    292eed28994234bf591e24addd4402d4135525e8-Lenovo-ThinkPad-L480-SystemFirmware-1.29.cab
    931b215c56ee380e4bd7dd611baccc46851e2cfb-Lenovo-ThinkPad-X270-SystemFirmware-1.32.cab
    2b2f0a343bdc7a2861e20779c3f12f9bd3c46d5f-Lenovo-ThinkPad-X1Carbon5th-SystemFirmware-1.34.cab
    dd1fdf1ac801f502ca5e00a3a79c025544704474-Lenovo-ThinkPad-T570P51s-SystemFirmware-0.1.35.cab
    6c4063e5972ee0de9870f1b63b7fd7310a0c179d-Lenovo-ThinkPad-L570-SystemFirmware-0.1.35.cab
    46c382fbcc171b023b66b0f579a7f7ff31d90ff9-Lenovo-ThinkPad-T460s-SystemFirmware-1.37.cab
    8366a0a2f694f2e67e8d629c3cd5b078c10d6535-Lenovo-ThinkPad-T460-SystemFirmware-1.37.cab
    3c6d0c91e496c35435e6165b660ed2d3d3510415-Lenovo-ThinkPad-X1Carbon4th-X1Yoga1st-SystemFirmware-1.38.cab
    f9abd647920da7d0b9d178ed3bfb93516cc9e390-Lenovo-ThinkPad-X260-SystemFirmware-1.40.cab
    9833ac83b1454a6391613d6927ecdc38e53e7a94-Lenovo-ThinkPad-T460s-SystemFirmware-1.42.cab
    9d9750f0e6d5c378cdd8f7eecde0eb8538a98c19-Lenovo-ThinkPad-L560-SystemFirmware-1.43.cab
    ba8248caf4f6a9a00080c75eabf09c7bf429abc0-Lenovo-ThinkPad-P51-SystemFirmware-1.45.cab
    886b60736445329b5ddc1797ddb013c0b49501f4-Lenovo-ThinkPad-T470-SystemFirmware-1.52.cab
    1c03e1b5491094429129b3eef952816c21777281-Lenovo-ThinkPad-P50-SystemFirmware-1.52.cab
    f91876dff5d0ac439364e466814cee8c5df01a4a-Lenovo-ThinkPad-L470-SystemFirmware-1.68.cab
    995cc47a2f491d6fc700089984da6662bcca17da-Lenovo-ThinkPad-P70-SystemFirmware-2.25.cab
    f617a912dc6eba4766de675bffe1e58a7ca9bae9-Lenovo-ThinkPad-T460p-SystemFirmware-2.26.cab
    071423c257f8305d67cd81fddbbc644046988fbd-M60_0241.cab
    3c9bf9b60b418e9914c9e8a5a63853ebf6fbb6d6-firmware.XPS_7760_Precision_5720_AIO_2.2.0.wu.cab
    d53c52f3a62ef1230ffd306dbc20a375cc9d2141-firmware_Precision_Tower_3620_2.3.5.wu.cab
    f4f334a82d19f40cc7ce7416f15e68702872184c-firmware_Precision_Tower_3420_2.3.5.wu.cab
    a1a6e10beb96281fa78c62a7d967c8c3a1cf7430-DellTpm2.0_Fw1.3.1.0.cab
    6573e95f3482252d28863d1ed199c44aa0fa377f-Lenovo-ThinkPad-T580andP52s-ConsumerMEFirmware-11.8.55.3510.cab
    97e72530051a8c17626e7168e5a007cfac07b6a7-Lenovo-ThinkPad-T580andP52s-CorporateMEFirmware-11.8.55.3510.cab
    9748e46730f66d51aae658e3eb24acc4e3ac9ab1-Lenovo-ThinkPad-X1Yoga3rd-ConsumerMEFirmware-11.8.55.3510.cab
    6089fae9264d8649b572e118fc66350e16464945-Lenovo-ThinkPad-X1Yoga3rd-CorporateMEFirmware-11.8.55.3510.cab
    530d6cde82f5152396edcff4099fefe3e98072a9-Lenovo-ThinkPad-T570andP51s-ConsumerMEFirmware-11.8.55.3510.cab
    e31314a77b858ac4478a29e1665df2e4d539ec36-Lenovo-ThinkPad-T570andP51s-CorporateMEFirmware-11.8.55.3510.cab
    3703fa845dcb19e5f7ae77bdab70479970c2569d-Lenovo-ThinkPad-T480s-ConsumerMEFirmware-11.8.55.3510.cab
    3da421eb27b392a3941c09b1cf7976ccd3c28b1e-Lenovo-ThinkPad-T480s-CorporateMEFirmware-11.8.55.3510.cab
    9c0d1765507c95851b31d5b4b3f139eb22115f1d-Lenovo-ThinkPad-X1Carbon6th-ConsumerMEFirmware-11.8.55.3510.cab
    dd546ac2dc869a1b7dc66d0eefe1636124e0727c-Lenovo-ThinkPad-X1Carbon6th-CorporateMEFirmware-11.8.55.3510.cab
    d854a371fccaa0304e001e10598ee82d88e0232f-Lenovo-ThinkPad-T480-ConsumerMEFirmware-11.8.55.3510.cab
    a2e10f4044223318f66d18015f9e12ae23b6faf9-Lenovo-ThinkPad-T480-CorporateMEFirmware-11.8.55.3510.cab
    c46722e51001648be9ba0a451c6e1498f154d0ff-Lenovo-ThinkPad-P51-ConsumerMEFirmware-11.8.55.3510.cab
    b2f92767d757abd51cee851f097cb3cff5ebc220-Lenovo-ThinkPad-P51-CorporateMEFirmware-11.8.55.3510.cab
    bd160ccdaa40a6db2b310045d6652f7e60c2bf5d-Lenovo-ThinkPad-P71-ConsumerMEFirmware-11.8.55.3510.cab
    d6a0d17380c25470b515f9f18ccdb08b10ec1bde-Lenovo-ThinkPad-P71-CorporateMEFirmware-11.8.55.3510.cab
    fbf02e9ec3b8b5c652083c2ebe5d1d04537998f2-Lenovo-ThinkPad-T470-ConsumerMEFirmware-11.8.55.3510.cab
    a8bf4cd55b3e10898e6d7dc48bad96bc5247e6b8-Lenovo-ThinkPad-T470-CorporateMEFirmware-11.8.55.3510.cab
    87259b19bf31731007132ed99178876b439a772c-Lenovo-ThinkPad-T470s-ConsumerMEFirmware-11.8.55.3510.cab
    7ec8fb79882ca0d589b3c0d5552b5dd36599b667-Lenovo-ThinkPad-T470s-CorporateMEFirmware-11.8.55.3510.cab
    f55b12c7e639de36a50854e9ccb4c6c1d0c08268-Lenovo-ThinkPad-X1Carbon5th-ConsumerMEFirmware-11.8.55.3510.cab
    34763cc167964294e0928a72b0a3d77d78601068-Lenovo-ThinkPad-X1Carbon5th-CorporateMEFirmware-11.8.55.3510.cab
    029a79e7448beccc5db995b39a2a65661a0cbbe1-Lenovo-ThinkPad-X1Yoga2nd-ConsumerMEFirmware-11.8.55.3510.cab
    22e2c60ceb2bb350e47c9ac8c3b780938e32e158-Lenovo-ThinkPad-X1Yoga2nd-CorporateMEFirmware-11.8.55.3510.cab
    ab465eb1ad0f366c38b3d97c9f0e1dc06b890e09-Lenovo-ThinkPad-X280-ConsumerMEFirmware-11.8.55.3510.cab
    93cfc9f6961f046fbf12d14be1b9e9c9588461d2-Lenovo-ThinkPad-X280-CorporateMEFirmware-11.8.55.3510.cab
    e043f5b7852d94c2a0751e6d2b1f635bee88888b-Lenovo-ThinkPad-T460s-ConsumerMEFirmware-11.8.55.3510.cab
    3f0d8325ba5bac89c20e6d6d1a94476d0f8190e6-Lenovo-ThinkPad-T460s-CorporateMEFirmware-11.8.55.3510.cab
    5897d0443d57476061042f0749f7cdedf1ab493d-Lenovo-ThinkPad-X1Yoga1st-ConsumerMEFirmware-11.8.55.3510.cab
    32436b5d7381d49e1af045c4d58458d3ab5f17c7-Lenovo-ThinkPad-X1Yoga1st-CorporateMEFirmware-11.8.55.3510.cab
    2195c81a529033a5d23bf789c1d9295a9209fa66-Lenovo-ThinkPad-T560andP50s-MEFirmware-11.8.55.3510.cab
    9f717f783a0df21160465908c5b271cd999fc4fb-Lenovo-ThinkPad-P50-MEFirmware-11.8.55.3510.cab
    35d4de6122f22556ba85545fff2b6683d30434e0-Lenovo-ThinkPad-L570-ConsumerMEFirmware-11.8.55.3510.cab
    4dbe13efc930ac15980abc4c23e01745b93a2763-Lenovo-ThinkPad-L570-CorporateMEFirmware-11.8.55.3510.cab
    2e253d0f7a742ef45dc72c219b726fb4aa4a2407-NEC-VersaProTypeVM-ConsumerMEFirmware-11.8.55.3510.cab
    a1ee05bcccc329ad218675a5c79d78678af5c356-Lenovo-ThinkPad-P70-MEFirmware-11.8.55.3510.cab
    414b4de05f411ca00c2c7b7f08c3d2e1c153c9e6-Lenovo-ThinkPad-P52-CorporateMEFirmware-12.0.10.1127.cab
    07bec2cd0be871dfbac9c4413bf2c83c7434c06a-Lenovo-ThinkPad-P72-ConsumerMEFirmware-12.0.10.1127.cab
    9aa40184aeca71cee24bcd173265eff5e433ae8f-Lenovo-ThinkPad-X1andP1Extreme-ConsumerMEFirmware-12.0.6.1120.cab
    96bf8891ff4fb1ccf0d0a2ed4191147653f072de-Lenovo-ThinkPad-X1andP1Extreme-CorporateMEFirmware-12.0.6.1120.cab
    00ed67a47ed2faa89e50f1e481e2459a1f5a539b-Lenovo-ThinkPad-P1andX1Extreme-CorporateMEFirmware-12.0.6.1120.cab
    a42c75ea638394d9e46465f4288e146e079ed2fd-Lenovo-ThinkPad-P1andX1Extreme-ConsumerMEFirmware-12.0.6.1120.cab
    5825a56a9199d275343e1bbfda04bb422a443332-Lenovo-ThinkStation-P520-P520c-SystemFirmware-S03KT20A.cab
    aab72512cd89a9ca7914d5bc993c3632cfa52ffe-Lenovo-ThinkStation-P920-SystemFirmware-S05KT29A.cab
    b1fa04c6e1e417b76bf6433e0e9b4062b27a93a6-Lenovo-ThinkStation-P720-SystemFirmware-S04KT29A.cab
    8d6defc3804cfdba23cb0105a50247f139e8301c-Lenovo-M625Q-SystemFirmware-M1WKT30A.cab
    17d4d7ba02fb7ed8024f98f21868868d5b8e3a13-Lenovo-ThinkStation-P720-SystemFirmware-S04KT33A.cab
    33a420345e2deaea0c2fe3fc6f7a284fb90e2d74-linaro-socionext-developerbox-37.cab
    fd8e59e04380724a508ccc5589aca98d5a5d47dd-firmware.OptiPlex_7450_AIO_1.0.0.wu.cab
    343f358a9e89c946d2c7a00d9cf2048decb418ab-firmware.OptiPlex_5250_AIO_1.0.0.wu.cab
    5a0f1d4b4cfc369b99ade04b31cfec5629d506e4-firmware.OptiPlex_3050_AIO_1.0.0.wu.cab
    79d462a2e9c40e11704c8fddf32ede6b94ea0eeb-firmware.Latitude_5x80H_1.0.0.cab
    4a2180e192f31ac3895ac5ff97ff90f4fcbb94cd-firmware.Latitude_5x80U_1.0.0.cab
    8aa6ae7f952e08c40c3645cd43f8f6852f2eeef2-firmware.cab
    4ab464b1842d0adc924f1d220b6f4df481946d0b-firmware_Caracalla_010000.wu.cab
    22c8df134c2c9497b3e3723819e757dbdd7d8623-Bighorn_100_Signed_1152921504627520111.cab
    e703b8a0d610a3fd72549d21d893544e14d43989-Grizzly_100_HDD_Signed_1152921504627520238.cab
    90a28b009a3b73ece6e47f2e48e1061ecd7b9302-Bighorn_100_HDD_Signed_1152921504627520544.cab
    7971c70664bd39072605ac50ebc785e58caca4aa-Signed_1152921504627508879.cab
    d906ceaaa7d59ce12f56e2aba23266805cf6e6bf-Signed_1152921504627510694.cab
    43dd95aaeb419742aff1251b17b784e8daafc4b4-Signed_1152921504627510580.cab
    19c49a7911f97a9ec2e9d98dbc10710efa4972df-Signed_1152921504627510692.cab
    ddec90b9bd2b6d27701ff437610d64cc4b3685f6-Signed_1152921504627510628.cab
    4620c73fae10e115e5a5ac7f01cd4c917da682e7-firmware_Latitude_3300_1.0.0.wu.cab
    4e0de129ae0fa1066507552c4e7e70aa53ab2f3f-Signed_1152921504627868622.cab
    fcfb9d6ee586fcae707ae99d60c07b3b5de64a9e-firmware.cab
    258cb0ad5cac256c36328e808fb868b209c120e3-firmware_EmbeddedBoxPC3000_1.0.1.wu.cab
    0031b27f734c454b4322070541c01884c9d07e80-firmware.OptiPlex_5050_1.0.1.wu.cab
    2fa5c88bffac21d517e6072283421529c3469934-firmware.OptiPlex_3050_1.0.1.wu.cab
    6bb9f67938cf9fba7a9af08d940c17ba715c1b09-firmware.cab
    3aa624c6c7d880b0c19605da96e427316437b051-firmware_OptiPlex_5055_Ryzen_CPU_1.0.1.wu.cab
    e713672b4091184687d7df211a358a0e5a77c742-firmware.Latitude_5X91_Precision_3530_1.0.1.wu.cab
    315e1023eb73b2e56299cd490c9d8c6074e1fad5-firmware.Latitude_5x90_1.0.2.wu.cab
    0cd789964ca36173036d4bfe9ee9c946e725be6a-BisonX_Biosn_102_Signed_1152921504627541074.cab
    0ca1bdbaa6348bc28d51cf040eee0455b0adaa56-BisonX_Bison_102_HDP_Signed_1152921504627541051.cab
    1f1860e10d828583646cb8d77c503d1148bc2a77-Cougar_102_Signed_Signed_1152921504627541138.cab
    b3cd48d63f128da86b41d611d04b4cb9cae95e67-Cougar_102_HDP_Signed_1152921504627541140.cab
    a0b40f427e015e67cb773adabd97cf37d579c6e9-Elk_102_Signed_1152921504627541053.cab
    8e235c4ee5b3cac0e6115436d61ad714f30f0843-Elk_102_HDP_Signed_1152921504627541056.cab
    f4a310edc5c1a03b630ac4d58abaae71ec747e47-XPS_9560_Precision_5520_1.0.3.cab
    9f91eb2a21b2dd4c97a9d2cb666a1ec624389289-firmware.cab
    9dcbe6419cb201be83bb4b6c31e02c9df7386ab2-firmware.cab
    8410e17d7f9923c24fdf949da727c12a4ff0e033-Precision_3930_1.0.3_firmware.wu.cab
    31408324adb009ac6d4df06def2f0b9ef1289833-Wyse_5070_firmware.wu.cab
    152f78543d3fe885960178ca4e2b41fd975774d8-Precision_3630_1.0.4_firmware.wu.cab
    64288a7a512318a1b4002d9f6cd28f0953f7fbfe-firmware.Precision_3430_1.0.5.wu.cab
    2fb5d0f8991ce4b9dc76cfc457d8682d2531909e-firmware.Precision_3430_1.0.5_HDP.wu..cab
    fdffa502b4ebc3d60359d133e842c667a3d4b351-firmware.cab
    446754c8a454ba64a0eb6cc41e74024dff4b489e-OptiPlex_5055_APU_1.0.10.wu.cab
    637428a177a5aee61ff6a66f10c70c79f56a8134-XPS_9365_1.0.21_BIOS.wu.cab
    22ddb32ec0df746a51d951269fbdf8f06ed9b0f7-Lenovo-ThinkStation-P330-System-Firmware-M1VKT1BA.cab
    e540233044d3afd506dfb6720d807e2c6c4ca516-P61_0170.cab
    f6323e6ff9a92122d4e72089078e64c6161b3344-P60_0171.cab
    76171aa507d42a676cff3d3a75dc312d6c06c732-firmware.OptiPlex_7050_1.1.0.wu.cab
    f68f9980cd28243c7a266016f00063a42dc16281-firmware_G5_5587_G7_7588_Vostro_7580_1.1.0_wu.cab
    8fbdd9c25174b627ed8e4bdac4ee210bfd7aa3f8-firmware_OptiPlex_5055_A-Series_1.1.2.wu.cab
    e997e3e3b89f6bfbd87d8401b4db0bb4359a1999-firmware.cab
    fb4796159200a6667829ab0fc3584d5bb957eef6-Precision_5820T_1.1.3.wu.cab
    cf0f011542bdc824e2e3f42e0847c35f8cce9d38-Precision_7x20T_1.1.5.wu.cab
    3ef300e6eb15d8673cdad2703020203f8184aba6-firmware.cab
    6e3b3250a289eac825528cc252455a05241cd004-Q50_010108.cab
    93d92eb7b94d02bbb58ae50653c2329d2f11aae2-firmware (1).cab
    2d9571961f949dea074f495cbebd50c2aee39aa5-firmware.cab
    611ef8c767c7d06884eab0b0d6c95872e436eb20-Signed_1152921504627342028.cab
    93c0e040c4738920a9f8a22d30381b028e900cbb-Signed_1152921504627455480.cab
    54ef0a9685a67b3328c05d3959e722005d44f063-OptiPlex_7760_7460_AIO_BIOS_1.2.0.cab
    288d799c68ba59063ff178ce24bafb1a5e131271-firmware_Wyse_3040_BIOS_1.2.1.wu.cab
    386cb4efa7ed75e0ca8133e9dec85b5750638b19-Precision 5530, XPS 9570 BIOS 1.2.2.cab
    95b37375ce6af8a15abffe11155601a7d2ba03ba-firmware.cab
    44eed1c98b13faa8833e7c549a7825e19b729124-firmware.Latitude_7x80_1.2.9.wu.cab
    174243fc1da6a81fd9d132aada71187d5b24e469-firmware.OptiPlex_7440_AIO_1_3_9_LVFS.cab
    b1dc029e73adf4dbaa149f0340bbce918da67ccc-Signed_1152921504627733243.cab
    99c920e2ceb8792cf729edd038498ec3497c84ee-firmware.cab
    3971f4a83d1019cb6b3144ef720560b619218279-firmware.cab
    3baa399ca9deb57a14dde90b022ed58838a74cbf-firmware.OptiPlex_7050_1.5.2_HDP.wu.cab
    e0855b3835a39736a64845d3d1cb6f01b2e588fa-firmware.OptiPlex_5050_1.5.2_HDP.wu.cab
    241d25f610d6271fa4d21e36393cdab7a0273616-firmware.OptiPlex_7450_AIO_China_Hdd_Deluxe_1.5.2.wu.cab
    ce74cecaf018605d74853d492a628070373ae84a-firmware.OptiPlex_5250_AIO_China_Hdd_Deluxe_1.5.2.wu.cab
    39b31e9e22b5dc73013b4d4de81d3ee45aeb8268-firmware.Precision_7x30_1.5.2.wu.cab
    765ce51544940a383a1ab3b2f7e924c1cdf71054-firmware_OptiPlex_3050_AIO_China_Hdd_Delux_1.5.4.wu.cab
    956da8682f1ef342d12630649fa4b105deb28797-firmware.OptiPlex_7040_1.5.7.wu.cab
    fc963111f8d530880e023ac38fdc6e35e9c6b43b-firmware.Opti3040.1.5.7.cab
    50e35ff171ec85b00d1fa796f78196722cc504fb-firmware.OptiPlex_3240_AIO_1.5.12.wu.cab
    d5492c3575fe572973703d9ed006447f6747b4f5-Signed_1152921504627730043.cab
    2dc6130cd109062d7d1fe1a64c1eea9a56ecfbc5-firmware.cab
    7eb92640401318f481caab8d74ac436fceb167f0-firmware.wu.cab
    16dae563738cdb52b27b320dcd7bd87815681085-Dell_G5_5587_G7_7588_Vostro_7580_1.8.0.cab
    efef3c8c4f3cc8c367fa6112a454edc9e4e368c0-firmware_Precision_7x20_1.8.4.wu.cab
    36defd59ece1cff5a2a3e66dd340b9f2fd4613fd-firmware_OptiPlex_5040_1.9.2.wu.cab
    2dcc099ca46050fe549ed3c44520a41a2f2ca4ef-firmware_Latitude_7370_1.9.3.wu.cab
    56a045df3eb323191365f274f8ad03bd97e247f3-firmware_Latitude_E7x70_1.11.3.wu.cab
    6215e95bd8c53dddad1742d54e0a0299b6aeb54f-firmware_Precision_7x10_1.12.4.wu.cab
    f7375df3c5f903f55ffd64e9ce891da3aa535355-DellTpm1.2_Fw5.81.2.1.cab

Each can be prepended with `https://fwupd.org/downloads/` if you want to download it. You probably only need one ThinkPad firmware, for example, but I don't mind if you want them all to do some kind of validation. The cab files can be extracted using `gcab -x` but you'll need to create a directory for each archive as inside most of the firmware capsules will be called `firmware.bin`. If you need a hand, ask.

**Comment by ErikBjorge** [comment]
Wow, thanks for the list and providing the link.  We will be looking at them.

**Comment by BrentHoltsclaw** [comment]
@hughsie can you please review pull request #544, to verify that it handles your concerns.

**Comment by hughsie** [comment]
@BrentHoltsclaw using your branch I still get:

[CHIPSEC] Found SPI Flash descriptor at offset 0x858891 in the binary 'firmware.bin'
ERROR: SPI Flash descriptor region is not valid

That's using firmware.bin from b76ea728bd1e305c285fbda742159c92a8d44924-Lenovo-ThinkPad-T480s-SystemFirmware-1.30.cab

**Comment by BrentHoltsclaw** [comment]
Which util command are you using?  I've been working on fixing chipsec_util.py uefi decode binaryname.  It appears that chipsec_util.py decode binaryname is indeed broken at this time.  I'll look into fixing that one up as well.

**Comment by hughsie** [comment]
`chipsec_util decode firmware.bin -n`

**Comment by BrentHoltsclaw** [comment]
After a discussion with @ErikBjorge chipsec_util decode expects to find a valid spi flash descriptor.  I updated the logging to indicate that chipsec_util uefi decode should be used when the spi flash descriptor is invalid or cannot be found.  Sound reasonable?

**Comment by hughsie** [comment]
> chipsec_util uefi decode

Works for me! Now all we need is for Python 3 support to be merged and I can do something interesting on the LVFS :)

**Comment by frinzell** [comment]
Closing as fixed.
