### ISSUE TITLE
Kabylake DID 0x5918 added twice

### ISSUE THREAD

**Issue by gibarrasch** [chipsec/chipsec#549]
Hi, I see the DID '0x5918' twice, 
 - First with the description: "Mobile 7th Generation Core Processor (Kabylake H)" (https://github.com/chipsec/chipsec/blob/master/chipsec/chipset.py#L177) 
 
 - And then with the description "Intel Xeon Processor E3 v6 (Kabylake CPU)" (https://github.com/chipsec/chipsec/blob/master/chipsec/chipset.py#L209)

**Comment by ErikBjorge** [comment]
Nice catch.  This should not cause any functional issues because the both point to the KBL platform configuration.  It does need to be cleaned up.  I will check to what description matches the actual ID (most likely it is the Xeon description).

**Comment by ErikBjorge** [comment]
Nice catch.  This should not cause any functional issues because the both point to the KBL platform configuration.  It does need to be cleaned up.  I will check to what description matches the actual ID (most likely it is the Xeon description).

**Comment by frinzell** [comment]
Closing as fixed.  Please reopen if needed.
