### ISSUE TITLE
MMCFG in VTBAR

### ISSUE THREAD

**Issue by gibarrasch** [chipsec/chipsec#550]
Hi, Sorry this is not an actual issue I just want to understand better the need of MMCFG type of register, i saw for instance that the VTBAR definition is override for old servers as follow:

 bdx.xml
register name="VTBAR" type="mmcfg" bus="0" dev="5" fun="0" offset="0x180" size="4" desc="VT BAR Register"

hsx.xml
register name="VTBAR" type="mmcfg" bus="0" dev="5" fun="0" offset="0x180" size="4" desc="VT BAR Register"

ivt.xml
register name="VTBAR" type="pcicfg" bus="0" dev="5" fun="0" offset="0x180" size="4" desc="VT BAR Register"

jkt.xml
register name="VTBAR" type="pcicfg" bus="0" dev="5" fun="0" offset="0x180" size="4" desc="VT BAR Register"

Why bdx and hsx need to use the memory mapped instead of doing a direct pcicfg access, whereas jkt and ivt can perform a direct pci read? does it have a reason or both options can be used interchangeable?

**Comment by gibarrasch** [comment]
Is it because pcicfg only allow us to read the PCI configuration space (the first 256 bytes)? if it is, i assume that ivt and jkt should be mmcfg instead. am i right?

**Comment by frinzell** [comment]
Good catch.  IVT and JKT XML should be 'mmcfg'.

**Comment by frinzell** [comment]
PR #551 created and ready for review.

**Comment by BrentHoltsclaw** [comment]
This issue appears to be fixed.  Please reopen if farther clarification is needed or the issue persists.
