### ISSUE TITLE
MMCFG miss-definitions

### ISSUE THREAD

**Issue by gibarrasch** [chipsec/chipsec#553]
Hi Guys, about MMCFG registers I think there are some miss-definitions for some architectures:

**Avoton:**
It doesn't define any override so it uses the common.xml definition of MMCFG bar:

common.xml

_bar name="MMCFG"    bus="0" dev="0"    fun="0" reg="0x60" width="8" mask="0x7FFFFFF000" size="0x1000" enable_bit="0" desc="PCI Express Register Range"_

But I think it should define and use the BECREG as the other atoms:

_bar name="MMCFG"   register="BECREG" base_field="ECBASE" size="0x10000000" enable_bit="ECENABLE" desc="PCI Express Register Range"_

**Ivytown and Jaketown:**
It doesn't define any override so it uses the common.xml definition of MMCFG bar too.

Looking into the Xeon E5 v2 datasheet.

mmcfg_base is in bus: 0, device: 5, function: 0, offset 0x84.

But, I couldn't find datasheets to verify it for every Ivytown and Jaketown.

**Comment by ErikBjorge** [comment]
We will have to dig into the documentation to verify the correct registers.  Thanks for finding these issues.

**Comment by Sae86** [comment]
Haven't found any documents for Avoton but I agree it should be consistent among Atoms.
