### ISSUE TITLE
chipsec_util spd detect doesn't print the detected SPDs without verbose flag

### ISSUE THREAD

**Issue by wrffrz** [chipsec/chipsec#557]
Running "chipsec_util.py spd detect" doesn't actually print out the results of any SPDs that were detected unless you include the verbose flag, which results in way more detail than most people want.

> $ sudo python chipsec_util.py spd detect
> 
> ################################################################
> ##                                                            ##
> ##  CHIPSEC: Platform Hardware Security Assessment Framework  ##
> ##                                                            ##
> ################################################################
> [CHIPSEC] Version 1.3.7
> ****** Chipsec Linux Kernel module is licensed under GPL 2.0
> [CHIPSEC] API mode: using CHIPSEC kernel module API
> [CHIPSEC] Executing command 'spd' with args ['detect']
> 
> [CHIPSEC] Searching for DIMMs with SPD..
> [CHIPSEC] (spd) time elapsed 0.004
> $

It says that it's searching for DIMMs with SPD, but no results are printed.

However, if you add the -v flag, there's a lot more output including DIMMs that were detected:

> $ sudo python chipsec_util.py -v spd detect
> 
> ################################################################
> ##                                                            ##
> ##  CHIPSEC: Platform Hardware Security Assessment Framework  ##
> ##                                                            ##
> ################################################################
> [CHIPSEC] Version 1.3.7
> [CHIPSEC] Loaded command-line extensions:
>    ['io_cmd', 'vmem_cmd', 'ucode_cmd', 'chipset_cmd', 'spi_cmd', 'msgbus_cmd', 'spd_cmd', 'reg_cmd', 'mmcfg_cmd', 'mem_cmd', 'vmm_cmd', 'interrupts_cmd', 'mmio_cmd', 'deltas_cmd', 'tpm_cmd', 'msr_cmd', 'ec_cmd', 'igd_cmd', 'spidesc_cmd', 'smbus_cmd', 'cmos_cmd', 'acpi_cmd', 'cpu_cmd', 'iommu_cmd', 'uefi_cmd', 'pci_cmd', 'decode_cmd', 'desc_cmd']
> [helper] Linux Helper created
> Module /dev/chipsec loaded successfully
> ****** Chipsec Linux Kernel module is licensed under GPL 2.0
> [helper] Linux Helper started/loaded
> [CHIPSEC] API mode: using CHIPSEC kernel module API
> [pci] reading B/D/F: 0/0/0, offset: 0x00, value: 0x01008086
> [pci] reading B/D/F: 0/31/0, offset: 0x00, value: 0x1C528086
>   [ lots of lines snipped ]
> [spd][0xAE] DRAM Device Type (byte 2): 0xFF
> [spd][0xAE] Detecting SPD.. not found (DRAM memory type = 0xFF)
> Detected the following SPD devices:
> DIMM0: 0xA0
> DIMM2: 0xA4
> [CHIPSEC] (spd) time elapsed 0.018
> [helper] Linux Helper stopped/unloaded
> [helper] Linux Helper deleted
> $

**Comment by dscott90** [comment]
This issue was resolved with https://github.com/chipsec/chipsec/pull/593
