### ISSUE TITLE
ShellBinPkg not available upstream anymore

### ISSUE THREAD

**Issue by tweksteen** [chipsec/chipsec#573]
EDK2 has removed the references to the pre-built EFI shell. Our documentation (manual and wiki) currently points it. I believe the UDK releases will now contain the binaries. Should we change the references to https://github.com/tianocore/edk2/blob/UDK2018/ShellBinPkg/UefiShell/X64/Shell.efi?

**Comment by ErikBjorge** [comment]
Sounds good to me.  Updating the Wiki now.  Will update the manual as well.

**Comment by frinzell** [comment]
Closing as fixed.
