### ISSUE TITLE
Comet Lake CPU support ?

### ISSUE THREAD

**Issue by HenryZhang-W** [chipsec/chipsec#614]
Hi，Does chipsec have any plans to support the new Comet Lake processors?
May I know your plan for this ?
Thank you!!!

**Comment by BrentHoltsclaw** [comment]
Yes we are working on the support.  Do you have specific needs or concerns?

**Comment by HenryZhang-W** [comment]
Cause we have a test fail and show unsupported platform on the result.
May I know the schedule for release new version to support new platform ?

**Comment by BrentHoltsclaw** [comment]
Please send a mail to chipsec@intel.com to continue the discussion

**Comment by BrentHoltsclaw** [comment]
Please reopen if you have farther comments/concerns.
