### ISSUE TITLE
Shouldn't this line contain a trailing whitespace?

### ISSUE THREAD

**Issue by 0xfede7c8** [chipsec/chipsec#623]
https://github.com/chipsec/chipsec/blob/master/chipsec/helper/linux/helper.py#L1138

I'm using a fork of chipsec with modifications on my own and getting errors because of not having that space.

**Comment by 0xfede7c8** [comment]
```
ERROR: Exception occurred during chipsec.modules.tools.uefi.whitelist.run(): 'Command '/usr/local/lib/python2.7/dist-packages/chipsec-1.3.7-py2.7-linux-x86_64.egg/chipsec_tools/compression/bin/TianoCompress -d -o sect00_hcty --uefisect00_hcty.gz' returned non-zero exit status 2'
```

**Comment by BrentHoltsclaw** [comment]
Looks like you are right, do you want to put in a pull request or would you like us to do it?

**Comment by 0xfede7c8** [comment]
I can do it! Thanks for the confirmation.

**Comment by BrentHoltsclaw** [comment]
Thanks for the help

**Comment by 0xfede7c8** [comment]
Should I create a PR for python3-rc also?
