### ISSUE TITLE
Empty return statements in io write 

### ISSUE THREAD

**Issue by mgawlinska** [chipsec/chipsec#625]
I was going through  chipsec/chipsec/hal/io.py and came across empty return-statements in write_port_byte/word/dword methods, though the _write_port method returns status.
I found it a bit inconsistent, therefore, I would like to know whether it was overlooked and the status should be returned in all of the cases. 

```
def _write_port(self, io_port, value, size ):
        if logger().HAL: logger().log( "[io] OUT 0x%04X: value = 0x%08X, size = 0x%02x" % (io_port, value, size) )
        status = self.helper.write_io_port( io_port, value, size )
        return status
```

```
    def write_port_byte(self, io_port, value ):
        if logger().HAL:
            logger().log( "[io] writing byte to I/O port 0x%04X <- 0x%02X" % (io_port, value) )
        self.helper.write_io_port( io_port, value, 1 )
        return
```

**Comment by BrentHoltsclaw** [comment]
Good Catch.  We should be consistent with our interfaces.
