### ISSUE TITLE
Chipsec-v1.3.8-chipsec_main.py-reports-not-support-error-on-Intel-ICL-CML-platforms-and-CPU-I9

### ISSUE THREAD

**Issue by witwan1031** [chipsec/chipsec#655]
Chipsec-v1.3.8-chipsec_main.py-reports-not-support-error-on-Intel-ICL-CML-platforms-and-CPU-I9.

**Comment by BrentHoltsclaw** [comment]
Please send a mail to chipsec@intel.com to continue the discussion
