### ISSUE TITLE
Chipsec package on PyPI is not maintained

### ISSUE THREAD

**Issue by 2xyo** [chipsec/chipsec#666]
The latest release of chipsec on https://pypi.org/project/chipsec/ is 1.3.0 on apr 4, 2017. 

It would be great to upload the current release as [wheel](https://pythonwheels.com/) package :)

**Comment by BrentHoltsclaw** [comment]
@2xyo we will be supporting PyPI going forward with the caveat that the user will be responsible for building and installing the driver separately.

**Comment by npmitche** [comment]
We have recently added the step to update pypi package during our normal release process.
