### ISSUE TITLE
INI/CFG/JSON data files are not copied when installing CHIPSEC as a package

### ISSUE THREAD

**Issue by c7zero** [chipsec/chipsec#67]
When installing chipsec as "setup.py install" data files for the modules are not copied.
Options:
1. Move to setuptools and use "include_package_data = True" or recursive package_data
2. Specify paths to each data file while using distutils in package_data
3. Enumerate all ini/cfg/json files recursively for package_data

**Comment by tweksteen** [comment]
Moving to setuptools would be the best option. This would clear up the path for further improvements regarding packaging in general.

**Comment by c7zero** [comment]
Closed with PR #70: switched to using setuptools
