### ISSUE TITLE
Release tag labels sometimes with leading `v`, sometimes without

### ISSUE THREAD

**Issue by JohnAZoidberg** [chipsec/chipsec#694]
In our distribution package files we interpolate the version number into the git release tag. If some releases are tagged as `1.4.1` and some as `v1.4.2`, they require unnecessary manual intervention.

In general, I'd say that it's good to keep consistency so that even humans are able to predict the tag name.

**Comment by BrentHoltsclaw** [comment]
Apologies for that, will ensure that tags will not have 'v' in the future

**Comment by JohnAZoidberg** [comment]
Great, thanks :)
