### ISSUE TITLE
Module directory structure

### ISSUE THREAD

**Issue by BrentHoltsclaw** [chipsec/chipsec#710]
Please review [proposed changes](https://github.com/chipsec/chipsec/wiki/Reorganize-Module-Directory-Structure) and provide comments if something is missing or this will impact any projects.

**Comment by skochinsky** [comment]
You have the same names in` modules/` and `tools/`, which is it supposed to be?

**Comment by BrentHoltsclaw** [comment]
The goal would be to move the tools directory out of the modules directory and for each to share a similar sub-directory structure that better defines the component the module or tool is evaluating.

The modules directory would be used for settings/validation type testing where the test is searching for a specific configuration and passing back results.  

The tools directory would be used for test cases which could be harmful to or modify system configurations and passing back results.

**Comment by Sae86** [comment]
Closing this issue since PR was closed from lack of support.
