### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by c7zero** [chipsec/chipsec#78]
chipsec-manual.pdf and README in Linux driver are out of date

**Comment by nkaretnikov** [comment]
To give concrete examples of this (on fda2e251) :
* The driver directory (step 4 of "Installing CHIPSEC") is incorrect.
* Multiple options are confusing, like using `./run.sh` vs. `make install`. Moreover, it's much harder to maintain. For instance, `./compile_linux_driver.sh` refers to an incorrect driver directory, too.

**Comment by c7zero** [comment]
Fixed with PR #96
