### ISSUE TITLE
Create a test suite for the UEFI parser

### ISSUE THREAD

**Issue by 0xfede7c8** [chipsec/chipsec#781]
The UEFI parser has suffered a lot of changes in the recent time.

Idea is that future changes in the parser can be easily tested.

Features:

- Easy inclusion of new test cases (images and data) 
- Test cases should be included on the repository for portability (limitations on having binaries on the repo?)

**Comment by 0xfede7c8** [comment]
You can assign me to this if you agree.

**Comment by BrentHoltsclaw** [comment]
Any idea the size of test cases you would like to create.  I'm wondering if it would be better to create a repository opposed to increasing the size of CHIPSEC?

**Comment by 0xfede7c8** [comment]
The images are between 8-32MB each.
I think the test cases would contain ~25 images at first.
I will be an average of ~400MB

I'm ok with other repo. Maybe a submodule.

**Comment by BrentHoltsclaw** [comment]
As discussed offline, I think defining a format/metrics makes sense.  Please let @npmitche know if you would like any help.  

@hughsie Do you have an opinion?

**Comment by npmitche** [comment]
Created a private repo with a small set of binary files for testing.
