### ISSUE TITLE
win32helper: unnecessary check for STATUS_PRIVILEGED_INSTRUCTION?

### ISSUE THREAD

**Issue by assafcarlsbad** [chipsec/chipsec#821]
After issuing an unsuccessful IOCTL to the driver using `win32file.DeviceIoControl`, the helper attempts to compare the error status to `STATUS_PRIVILEGED_INSTRUCTION`. However, nowhere in its IOCTL dispatch routine the driver sets or returns this particular error code. Any chance this check is not relevant anymore?

**Comment by BrentHoltsclaw** [comment]
@johnloucaides @ErikBjorge can one of you help answer this question?

**Comment by johnloucaides** [comment]
Unless I'm mistaken, it's possible for one of the multiple calls to `GetExceptionCode()` to return STATUS_PRIVILEGED_INSTRUCTION according to docs here: https://docs.microsoft.com/en-us/windows/win32/debug/getexceptioncode

I think this used to come up with some of our fuzzing, actually.
