### ISSUE TITLE
uefi decode fail from Dell Latitude 5480

### ISSUE THREAD

**Issue by NicholasArmour** [chipsec/chipsec#828]
Attached **latitude5480_rom.bin** is from `chipsec_util spi dump latitude5480_rom.bin`

`chipsec_util uefi decode latitude5480_rom.bin` fails to decompress some sections, e.g:
                  TianoCompress: ERROR 3000: Invalid
                  The input file sect01_sixa.gz data is invalid.
                   corrupt input [sect01_sixa.gz]

[latitude5480_rom.zip](https://github.com/chipsec/chipsec/files/4069014/latitude5480_rom.zip)

**Comment by lautalom** [comment]
same problem with Latitude 7400

**Comment by npmitche** [comment]
Tested again and is working now. Closing.
