### ISSUE TITLE
Linux 5.6 deprecated ioremap_nocache

### ISSUE THREAD

**Issue by siro20** [chipsec/chipsec#873]
See [https://github.com/torvalds/linux/commit/4bdc0d676a643140bdf17dbf7eafedee3d496a3c](https://github.com/torvalds/linux/commit/4bdc0d676a643140bdf17dbf7eafedee3d496a3c)
The chipsec kernel module needs update to support +5.6 kernels.

**Comment by mrsmith0x00** [comment]
+. DKMS module failed to build on Arch LInux (due to `ioremap_nocache`). Please, update :)
