### ISSUE TITLE
Attempt to read certain MSR  causes kernel panic

### ISSUE THREAD

**Issue by sushmith** [chipsec/chipsec#887]
Here is an example: Attempt to read PRMRR_UNCORE_PHYBASE” and “PRMRR_UNCORE_MASK” registers using msr-tool fails with error "Cannot read MSR" on a platform
Attempt to read the same MSR using chipsec crashes the entire machine.
![image](https://user-images.githubusercontent.com/13529329/79012132-6c9fce80-7b1a-11ea-806f-cdcfe7bf78a8.png)

**Comment by iherna2** [comment]
Would something like this be acceptable?
diff --git a/chipsec/helper/oshelper.py b/chipsec/helper/oshelper.py
index 0afd6f8..a6de720 100644
--- a/chipsec/helper/oshelper.py
+++ b/chipsec/helper/oshelper.py
@@ -328,7 +328,7 @@ class OsHelper:
     # Read/Write MSR on a specific CPU thread
     #
     def read_msr( self, cpu_thread_id, msr_addr ):
-        if self.use_native_api() and hasattr(self.helper, 'native_read_msr'):
+        if (self.is_linux() or self.use_native_api()) and hasattr(self.helper, 'native_read_msr'):
             ret = self.helper.native_read_msr( cpu_thread_id, msr_addr )
         else:
             ret = self.helper.read_msr( cpu_thread_id, msr_addr )
@@ -337,7 +337,7 @@ class OsHelper:
         return ret
 
     def write_msr( self, cpu_thread_id, msr_addr, eax, edx ):
-        if self.use_native_api() and hasattr(self.helper, 'native_write_msr'):
+        if (self.is_linux() or self.use_native_api()) and hasattr(self.helper, 'native_write_msr'):
             ret = self.helper.native_write_msr( cpu_thread_id, msr_addr, eax, edx )
         else:
             ret = self.helper.write_msr( cpu_thread_id, msr_addr, eax, edx )

**Comment by BrentHoltsclaw** [comment]
Does this help? #889

**Comment by sushmith** [comment]
I think so. msr-tools( in the screenshot above) uses "rdmsr_on_cpu" and "wrmsr_on_cpu" calls and it works just fine. 
But I was just wondering if "rdmsr_safe_on_cpu" and "wrmsr_safe_on_cpu" are better choices? I read somewhere that the "safe" variants should be used when the target MSR may not actually exist as they have better error handling.

**Comment by Sae86** [comment]
Closing as issue was fixed
