### ISSUE TITLE
Apl.xml & Glk.xml SPIBAR wrong mask

### ISSUE THREAD

**Issue by Kelvinhack** [chipsec/chipsec#895]
I doubt the correctness of SPIBAR valid bit mask in Apl.xml and Glk.xml, unlike other Intel Atom chipset , Apollo and Gemini Lake datasheet stated that the mask should be bit [31:12] (0xFFFFF000) , instead of bit[31:9] (0xFFFFFE00)

![image](https://user-images.githubusercontent.com/22551808/80280156-2e2c1700-86b7-11ea-98fd-0ae1bf90a33c.png)

![image](https://user-images.githubusercontent.com/22551808/80280171-4b60e580-86b7-11ea-80b9-f54769066b76.png)

Please correct me if I'm wrong.

**Comment by BrentHoltsclaw** [comment]
@Kelvinhack yes the masks are incorrect.

**Comment by frinzell** [comment]
Closing as fixed.
