### ISSUE TITLE
Chipsec support platform

### ISSUE THREAD

**Issue by chris0435** [chipsec/chipsec#917]
Hi,
Have one question, Does Intel TGL are ready in version 1.5.0, because i check Chipsec_main.py, not found TGL option.

**Comment by BrentHoltsclaw** [comment]
Please email chipsec@intel.com

**Comment by frinzell** [comment]
This should be addressed in PR #1106

**Comment by Sae86** [comment]
Hi @chris0435 TGL is supported so I'm closing this issue. Please feel free to reopen if needed. Thanks!
