### ISSUE TITLE
ApolloLake / GeminiLake / CherryTrail / Braswell BFPREG Mask Issue

### ISSUE THREAD

**Issue by Kelvinhack** [chipsec/chipsec#926]
The mask of BFPREG in ApolloLake / GeminiLake / CherryTrail / Braswell cannot directly inherit the common.xml as the datasheet state that should be in size 15 bit for both limit and base. Please Correct me if I'm wrong.

CherryTrail / Braswell 
![image](https://user-images.githubusercontent.com/22551808/83839352-a3c0d500-a6b0-11ea-9cb2-440af84eee21.png)

Gemini Lake
![image](https://user-images.githubusercontent.com/22551808/83839964-3d3cb680-a6b2-11ea-8f8a-fddd72a0e9a7.png)

Apollo Lake
![image](https://user-images.githubusercontent.com/22551808/83839949-30b85e00-a6b2-11ea-93c9-b2a6c2b234e7.png)

**Comment by frinzell** [comment]
Closing.  Should be fixed with PR #1140.  Reopen if needed.
