### ISSUE TITLE
Denverton SPIBAR mask issue

### ISSUE THREAD

**Issue by Kelvinhack** [chipsec/chipsec#927]
Denverton SPIBAR mask should be 0xFFFFF000 as datasheet stated

![image](https://user-images.githubusercontent.com/22551808/83841882-90186d00-a6b6-11ea-9218-a605f7bc4d16.png)

**Comment by Sae86** [comment]
Thanks @Kelvinhack, would you like to open a PR? If not, I'd be happy to help making the change.

**Comment by Sae86** [comment]
I'll go ahead and make the change, thanks for bringing it up!
