### ISSUE TITLE
help me to analyze the summary result of ChipSec 

### ISSUE THREAD

**Issue by Azad-Readhat** [chipsec/chipsec#942]
Hi dears
I've done the test of ChipSec on a HP Proliant DL360P G8 server in order to find the security level.
I provided the log-file result of the ChipSec in the following.
[result_server.txt](https://github.com/chipsec/chipsec/files/4844009/result_server.txt)

Indeed, I'm confused to analyze **NOT implemented and NOT applicable modules**
Please help me to find answer of these questions
1- What is the reason of these two different modules??
2- Are these modules threatening?
3- is there any way to fix them?
Tnx to all

**Comment by BrentHoltsclaw** [comment]
SKIPPED_NOT_IMPLEMENTED - CHIPSEC currently has not implemented support for this test on this platform.

SKIPPED_NOT_APPLICABLE -The issue checked by this module is not applicable to this platform. This result can be ignored.

To check if a module should be implemented, the registers/device being checked must be present on the system and hold the same security implications.  They would need to be assessed on a case by case basis to determine whether or not they are not applicable or should be run on the system.  For the uefi related modules, the system must be booted in UEFI mode for them to run.

**Comment by Azad-Readhat** [comment]
dear Brent Holtsclaw
I'm grateful of your helpful description

**Comment by Azad-Readhat** [comment]
> SKIPPED_NOT_IMPLEMENTED - CHIPSEC currently has not implemented support for this test on this platform.
> 
> SKIPPED_NOT_APPLICABLE -The issue checked by this module is not applicable to this platform. This result can be ignored.
> 
> To check if a module should be implemented, the registers/device being checked must be present on the system and hold the same security implications. They would need to be assessed on a case by case basis to determine whether or not they are not applicable or should be run on the system. For the uefi related modules, the system must be booted in UEFI mode for them to run.

dear Brent Holtsclaw
Thank you for your help.
How can I test the security of these NOT implemented modules by ChipSec?
Is there any software to do that?

**Comment by BrentHoltsclaw** [comment]
For the cpu/pch within the log?

**Comment by Azad-Readhat** [comment]
> For the cpu/pch within the log?

Hi BrentHoltsclaw
Yse
for example in a platform, ME (Management Engine) module isn't implemented by ChipSec. in this case (/for other modules that ChipSec cannot to evaluate them) is there any valid method to test?

**Comment by Sae86** [comment]
Hi @Azad-Readhat, do you still need assistance with this issue? Are you still getting the same not implemented modules with latest releases?

**Comment by Sae86** [comment]
Closing as inactive. Please reopen if needed.
