### ISSUE TITLE
chipsec_km.c doesn't compile under Linux 5.7

### ISSUE THREAD

**Issue by siro20** [chipsec/chipsec#972]
Linux 5.7 removed support for kallsyms_lookup_name().
See 
[https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0bd476e6c67190b5eb7b6e105c8db8ff61103281](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0bd476e6c67190b5eb7b6e105c8db8ff61103281)

**Comment by yu17** [comment]
#953 
Basically the same issue.

**Comment by npmitche** [comment]
I believe this and #953 have been fixed over the last few releases. Please re-open if that's not the case or submit a new issue if other errors occur.
