### ISSUE TITLE
can't decode the rom.bin,!! error:API mode: using OS native API (not using CHIPSEC kernel module) 

### ISSUE THREAD

**Issue by RockySYR** [chipsec/chipsec#973]
run the following command :sudo python chipsec_util.py uefi decode rom.bin

report an error :API mode: using OS native API (not using CHIPSEC kernel module)
段错误

i need some help, thx

**Comment by BrentHoltsclaw** [comment]
Would you mind sharing the rom?

**Comment by RockySYR** [comment]
> Would you mind sharing the rom?

@BrentHoltsclaw Is it related to the rom file?，would you like to send my rom file to your mail
