### ISSUE TITLE
run ：sudo chipsec_main;; report error :ERROR: Message: "Cannot find chipsec.ko module"

### ISSUE THREAD

**Issue by RockySYR** [chipsec/chipsec#974]
run ：sudo chipsec_main;; report error :ERROR: Message: "Cannot find chipsec.ko module"
i need some help ,thx

**Comment by npmitche** [comment]
You must build the driver. Please follow the steps outlined in the wiki here: https://github.com/chipsec/chipsec/wiki/Installing-CHIPSEC-in-Linux

**Comment by RockySYR** [comment]
I have run these two commands ，apt-get install build-essential python-dev python gcc linux-headers-$(uname -r) nasm  AND python setup.py build_ext -i
No errors are reported, and I can run successfully # python chipsec_util.py spi dump rom.bin

**Comment by RockySYR** [comment]
> You must build the driver. Please follow the steps outlined in the wiki here: https://github.com/chipsec/chipsec/wiki/Installing-CHIPSEC-in-Linux

i saw /divers/linux/readme.md ,
To build:
	make

To load kernel module:
	sudo insmod ./chipsec.ko
but But the same error occurs

**Comment by BrentHoltsclaw** [comment]
@RockySYR what is the kernel version?  Chipsec currently does not support above version 5.7

**Comment by RockySYR** [comment]
> kernel version

@BrentHoltsclaw ##Linux version 5.4.0-42-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
