### ISSUE TITLE
cpuid_fuzz module global name logger not found problem

### ISSUE THREAD

**Issue by syjzwjj** [chipsec/chipsec#99]
when I run chipsec_main with cpuid_fuzz module ,it gets error global name 'logger' not found problem in the log. So I checked the code and modified https://github.com/chipsec/chipsec/blob/master/source/tool/chipsec/modules/tools/vmm/cpuid_fuzz.py#L80 and https://github.com/chipsec/chipsec/blob/master/source/tool/chipsec/modules/tools/vmm/cpuid_fuzz.py#L83
to self.logger.xxxxx then the error disappear. So I guess there're some mistakes in your code and you can see if there're some code to modifly.

**Comment by c7zero** [comment]
Fixed with https://github.com/chipsec/chipsec/commit/96dedad18d29b72e628726b5570c913301692fba
Thanks!
