### ISSUE TITLE
can't build driver.

### ISSUE THREAD

**Issue by RockySYR** [chipsec/chipsec#995]
run:$ sudo python setup.py install
fs/aufs/Makefile:3: fs/aufs/magic.mk: No such file or directory
make[3]: ***There are no rules to make goals“fs/aufs/magic.mk”. Stop.
make[2]: *** [scripts/Makefile.clean:67：fs/aufs] [Errno 2]
make[1]: *** [Makefile:1738：_clean_fs] [Errno 2]
make: *** [Makefile:30：clean] [Errno 2]

**Comment by npmitche** [comment]
Please provide more details:
* What environment are you running in? (OS, Python version)
* Have you verified you have all of the prerequisites as defined in the [wiki](https://github.com/chipsec/chipsec/wiki#Installation)?
